Failures in [node-test-pull-request/63031](https://ci.nodejs.org/job/node-test-pull-request/63031/) to [node-test-pull-request/63130](https://ci.nodejs.org/job/node-test-pull-request/63130/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-10-16.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-10-16 00:09 | 0       | 22      | 23       | 8       | 47      | 23.91%     |


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/55343/](https://ci.nodejs.org/job/node-test-pull-request/63045/), [https://github.com/nodejs/node/pull/55333/](https://ci.nodejs.org/job/node-test-pull-request/63052/), [https://github.com/nodejs/node/pull/55359/](https://ci.nodejs.org/job/node-test-pull-request/63065/), [https://github.com/nodejs/node/pull/55362/](https://ci.nodejs.org/job/node-test-pull-request/63066/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/), [https://github.com/nodejs/node/pull/55312/](https://ci.nodejs.org/job/node-test-pull-request/63078/), [https://github.com/nodejs/node/pull/50853/](https://ci.nodejs.org/job/node-test-pull-request/63079/), [https://github.com/nodejs/node/pull/55175/](https://ci.nodejs.org/job/node-test-pull-request/63103/), [https://github.com/nodejs/node/pull/55387/](https://ci.nodejs.org/job/node-test-pull-request/63116/)) |
| Appeared | [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17166/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61547/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61522/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63045/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63116/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17166/console">Example</a></summary>

```
not ok 4207 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3229.95500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx-arm/nodes/osx11/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v23.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/55312/](https://ci.nodejs.org/job/node-test-pull-request/63056/), [https://github.com/nodejs/node/pull/55379/](https://ci.nodejs.org/job/node-test-pull-request/63085/), [https://github.com/nodejs/node/pull/55207/](https://ci.nodejs.org/job/node-test-pull-request/63092/), [https://github.com/nodejs/node/pull/55244/](https://ci.nodejs.org/job/node-test-pull-request/63095/), [https://github.com/nodejs/node/pull/55375/](https://ci.nodejs.org/job/node-test-pull-request/63101/), [https://github.com/nodejs/node/pull/55175/](https://ci.nodejs.org/job/node-test-pull-request/63103/), [https://github.com/nodejs/node/pull/54545/](https://ci.nodejs.org/job/node-test-pull-request/63125/)) |
| Appeared | [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55378/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55358/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/46959/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55344/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/61179/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63056/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63125/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55378/console">Example</a></summary>

```
not ok 1491 parallel/test-file-write-stream4
  ---
  duration_ms: 360105.38100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55244/](https://ci.nodejs.org/job/node-test-pull-request/63100/), [https://github.com/nodejs/node/pull/55175/](https://ci.nodejs.org/job/node-test-pull-request/63104/), [https://github.com/nodejs/node/pull/54927/](https://ci.nodejs.org/job/node-test-pull-request/63119/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/46975/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55359/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57305/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63070/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63119/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/46975/console">Example</a></summary>

```
not ok 3890 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 120090.38400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55332/](https://ci.nodejs.org/job/node-test-pull-request/63047/), [https://github.com/nodejs/node/pull/55071/](https://ci.nodejs.org/job/node-test-pull-request/63067/), [https://github.com/nodejs/node/pull/55379/](https://ci.nodejs.org/job/node-test-pull-request/63085/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63087/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46944/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46942/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46926/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46905/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63047/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63087/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46944/console">Example</a></summary>

```
not ok 4173 wpt/test-compression
  ---
  duration_ms: 1440038.65700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to throw
    [PASS] "a" should cause the constructor to throw
    [PASS] no inpu...
```
</details>

-------

| Reason | <code>parallel/test-fs-promises-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54478/](https://ci.nodejs.org/job/node-test-pull-request/63064/), [https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63064/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63076/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console">Example</a></summary>

```
not ok 1189 parallel/test-fs-promises-watch
  ---
  duration_ms: 558.97200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/watchers:357
          const error = new UVException({
                        ^
    
    Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.1191/watch1/foo'
        at watch (node:internal/fs/watchers:357:21)
        at watch.next (<anonymous>)
        at _watch (node:internal/fs/promises:1260:10)
        at _watch.next (<anonymous>)
        at test (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-fs-promises-watch.js:60:44)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-fs-promises-watch.js:81:3)
        at Module._compile (node:internal/modules/cjs/loader:1568:14)
        at Object..js (node:internal/modules/cjs/loader:1711:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/l...
```
</details>

-------

| Reason | <code>parallel/test-fs-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54478/](https://ci.nodejs.org/job/node-test-pull-request/63064/), [https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63064/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63076/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console">Example</a></summary>

```
not ok 1293 parallel/test-fs-watch
  ---
  duration_ms: 401.59000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/watchers:255
        throw error;
        ^
    
    Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.1295/watch1/foo'
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at Object.watch (node:fs:2477:36)
        at doWatchTest (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-fs-watch.js:47:22)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-fs-watch.js:97:5)
        at Module._compile (node:internal/modules/cjs/loader:1568:14)
        at Object..js (node:internal/modules/cjs/loader:1711:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/loader:1138:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/m...
```
</details>

-------

| Reason | <code>parallel/test-fs-watch-recursive-delete</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54478/](https://ci.nodejs.org/job/node-test-pull-request/63064/), [https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63064/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63076/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console">Example</a></summary>

```
not ok 1306 parallel/test-fs-watch-recursive-delete
  ---
  duration_ms: 378.17500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/recursive_watch:217
            throw error;
            ^
    
    Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.1307/parent'
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at watch (node:fs:2477:36)
        at #watchFile (node:internal/fs/recursive_watch:163:21)
        at [kFSWatchStart] (node:internal/fs/recursive_watch:210:22)
        at Object.watch (node:fs:2474:36)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-fs-watch-recursive-delete.js:28:20)
        at Module._compile (node:internal/modules/cjs/loader:1568:14)
        at Object..js (node:internal/modules/cjs/loader:1711:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/loader:1138:12) {
      errno: -2,
      s...
```
</details>

-------

| Reason | <code>parallel/test-watch-mode-files_watcher</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54478/](https://ci.nodejs.org/job/node-test-pull-request/63064/), [https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63064/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63076/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console">Example</a></summary>

```
not ok 3527 parallel/test-watch-mode-files_watcher
  ---
  duration_ms: 586.93600
  severity: fail
  exitcode: 1
  stack: |-
    ▶ watch mode file watcher
      ✖ should watch changed files (5.307359ms)
        Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.3522/file1'
            at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
            at watch (node:fs:2477:36)
            at FilesWatcher.watchPath (node:internal/watch_mode/files_watcher:109:21)
            at FilesWatcher.filterFile (node:internal/watch_mode/files_watcher:128:12)
            at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-watch-mode-files_watcher.mjs:49:13)
            at Test.runInAsyncScope (node:async_hooks:211:14)
            at Test.run (node:internal/test_runner/test:934:25)
            at async Promise.all (index 0)
            at async Suite.run (node:internal/test_runner/test:1320:7)
            at async startSubtestAfterB...
```
</details>

-------

| Reason | <code>pummel/test-fs-watch-non-recursive</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54478/](https://ci.nodejs.org/job/node-test-pull-request/63064/), [https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63064/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63076/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console">Example</a></summary>

```
not ok 3894 pummel/test-fs-watch-non-recursive
  ---
  duration_ms: 192.00000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/watchers:255
        throw error;
        ^
    
    Error: ENOSPC: System limit for number of file watchers reached, watch '/home/iojs/build/.tmp.3893'
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at Object.watch (node:fs:2477:36)
        at doWatch (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/pummel/test-fs-watch-non-recursive.js:42:22)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/pummel/test-fs-watch-non-recursive.js:60:3)
        at Module._compile (node:internal/modules/cjs/loader:1568:14)
        at Object..js (node:internal/modules/cjs/loader:1711:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/loader:1138:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14...
```
</details>

-------

| Reason | <code>sequential/test-fs-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54478/](https://ci.nodejs.org/job/node-test-pull-request/63064/), [https://github.com/nodejs/node/pull/55368/](https://ci.nodejs.org/job/node-test-pull-request/63070/), [https://github.com/nodejs/node/pull/55371/](https://ci.nodejs.org/job/node-test-pull-request/63076/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63064/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63076/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54223/console">Example</a></summary>

```
not ok 4210 sequential/test-fs-watch
  ---
  duration_ms: 191.34500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/fs/watchers:255
        throw error;
        ^
    
    Error: ENOENT: no such file or directory, watch '/home/iojs/build/.tmp.4209/watch.txt'
        at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
        at Object.watch (node:fs:2477:36)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/sequential/test-fs-watch.js:59:22)
        at Module._compile (node:internal/modules/cjs/loader:1568:14)
        at Object..js (node:internal/modules/cjs/loader:1711:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/loader:1138:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5) {
  ...
```
</details>

-------

| Reason | <code>es-module/test-typescript</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55332/](https://ci.nodejs.org/job/node-test-pull-request/63047/), [https://github.com/nodejs/node/pull/54657/](https://ci.nodejs.org/job/node-test-pull-request/63097/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/30836/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46905/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63047/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63097/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/30836/console">Example</a></summary>

```
not ok 180 es-module/test-typescript
  ---
  duration_ms: 11619.11000
  severity: fail
  exitcode: 1
  stack: |-
    ✔ expect process.features.typescript to be 'strip' when --experimental-strip-types (181.1983ms)
    ✔ expect process.features.typescript to be 'transform' when --experimental-transform-types (154.7594ms)
    ✔ execute a TypeScript file (292.818ms)
    ✔ execute a TypeScript file with imports (425.0012ms)
    ✔ execute a TypeScript file with imports (192.7343ms)
    ✔ execute a TypeScript file with imports with default-type module (358.4557ms)
    ✔ execute a TypeScript file with node_modules (350.0396ms)
    ✔ execute a TypeScript file with node_modules with default-type module (324.8963ms)
    ✔ expect error when executing a TypeScript file with imports with no extensions (334.758ms)
    ✔ expect error when executing a TypeScript file with imports with no extensions with default-type module (305.0242ms)
    ✔ expect error when executing a TypeScript file with enum (332.3169ms)
    ✔ expect err...
```
</details>

-------

| Reason | <code>parallel/test-http2-large-write-multiple-requests</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55061/](https://ci.nodejs.org/job/node-test-pull-request/63109/), [https://github.com/nodejs/node/pull/54862/](https://ci.nodejs.org/job/node-test-pull-request/63129/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/46981/console), [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61199/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63109/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63129/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/46981/console">Example</a></summary>

```
not ok 2812 parallel/test-http2-large-write-multiple-requests
  ---
  duration_ms: 125999.26800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    server sends content 1
    server sends content 2
    server sends content 3
    server sends content 4
    server sends content 5
    server sends content 6
    server sends content 7
    server sends content 8
    server sends content 9
    server sends content 10
    server sends content 11
    server sends content 12
    server sends content 13
    server sends content 14
    server sends content 15
    server sends content 16
    server sends content 17
    server sends content 18
    server sends content 19
    server sends content 20
    server sends content 21
    server sends content 22
    server sends content 23
    server sends content 24
    server sends content 25
    server sends content 26
    server sends content 27
    server sends content 28
    server sends content 29
    server sends content 30
    server sends content 31
    server s...
```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55320/](https://ci.nodejs.org/job/node-test-pull-request/63040/), [https://github.com/nodejs/node/pull/55205/](https://ci.nodejs.org/job/node-test-pull-request/63054/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55312/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57278/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63040/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63054/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55312/console">Example</a></summary>

```
not ok 4113 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360046.43100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------


### Jenkins Failure


### Git Failure


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/55156/](https://ci.nodejs.org/job/node-test-pull-request/63038/), [https://github.com/nodejs/node/pull/55348/](https://ci.nodejs.org/job/node-test-pull-request/63039/), [https://github.com/nodejs/node/pull/50853/](https://ci.nodejs.org/job/node-test-pull-request/63075/), [https://github.com/nodejs/node/pull/55378/](https://ci.nodejs.org/job/node-test-pull-request/63114/), [https://github.com/nodejs/node/pull/54545/](https://ci.nodejs.org/job/node-test-pull-request/63125/), [https://github.com/nodejs/node/pull/55397/](https://ci.nodejs.org/job/node-test-pull-request/63128/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46980/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46971/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/46896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63038/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63128/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46980/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>Error: invalid syntax</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/55359/](https://ci.nodejs.org/job/node-test-pull-request/63073/), [https://github.com/nodejs/node/pull/55379/](https://ci.nodejs.org/job/node-test-pull-request/63085/), [https://github.com/nodejs/node/pull/55061/](https://ci.nodejs.org/job/node-test-pull-request/63109/), [https://github.com/nodejs/node/pull/54927/](https://ci.nodejs.org/job/node-test-pull-request/63119/), [https://github.com/nodejs/node/pull/55397/](https://ci.nodejs.org/job/node-test-pull-request/63128/)) |
| Appeared | [test-rackspace-debian10-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian10-x64/60964/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63073/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63128/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian10-x64/60964/console">Example</a></summary>

```
Error: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/iojs/build/workspace/node/deps/npm/node_modules/node-gyp/lib/configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
</details>

-------

| Reason | <code>ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54657/](https://ci.nodejs.org/job/node-test-pull-request/63097/), [https://github.com/nodejs/node/pull/55175/](https://ci.nodejs.org/job/node-test-pull-request/63103/), [https://github.com/nodejs/node/pull/55397/](https://ci.nodejs.org/job/node-test-pull-request/63128/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/30850/console), [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2019-x86/30850/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/30823/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2019-x86/30850/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63097/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63128/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/30850/console">Example</a></summary>

```
ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54862/](https://ci.nodejs.org/job/node-test-pull-request/63124/), [https://github.com/nodejs/node/pull/53226/](https://ci.nodejs.org/job/node-test-pull-request/63130/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/75238/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63124/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63130/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/75238/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

