Failures in [node-test-pull-request/63384](https://ci.nodejs.org/job/node-test-pull-request/63384/) to [node-test-pull-request/63472](https://ci.nodejs.org/job/node-test-pull-request/63472/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-11-08.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-11-08 00:09 | 2       | 8       | 29       | 9       | 52      | 8.99%      |


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 11 ([https://github.com/nodejs/node/pull/55679/](https://ci.nodejs.org/job/node-test-pull-request/63390/), [https://github.com/nodejs/node/pull/53079/](https://ci.nodejs.org/job/node-test-pull-request/63391/), [https://github.com/nodejs/node/pull/55681/](https://ci.nodejs.org/job/node-test-pull-request/63396/), [https://github.com/nodejs/node/pull/55589/](https://ci.nodejs.org/job/node-test-pull-request/63404/), [https://github.com/nodejs/node/pull/55710/](https://ci.nodejs.org/job/node-test-pull-request/63414/), [https://github.com/nodejs/node/pull/55711/](https://ci.nodejs.org/job/node-test-pull-request/63416/), [https://github.com/nodejs/node/pull/55728/](https://ci.nodejs.org/job/node-test-pull-request/63435/), [https://github.com/nodejs/node/pull/55605/](https://ci.nodejs.org/job/node-test-pull-request/63438/), [https://github.com/nodejs/node/pull/55739/](https://ci.nodejs.org/job/node-test-pull-request/63456/), [https://github.com/nodejs/node/pull/55548/](https://ci.nodejs.org/job/node-test-pull-request/63469/), [https://github.com/nodejs/node/pull/55740/](https://ci.nodejs.org/job/node-test-pull-request/63470/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61957/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17531/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61895/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63390/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63470/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61957/console">Example</a></summary>

```
not ok 4230 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3099.15500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55681/](https://ci.nodejs.org/job/node-test-pull-request/63384/), [https://github.com/nodejs/node/pull/55618/](https://ci.nodejs.org/job/node-test-pull-request/63387/), [https://github.com/nodejs/node/pull/55738/](https://ci.nodejs.org/job/node-test-pull-request/63447/), [https://github.com/nodejs/node/pull/55362/](https://ci.nodejs.org/job/node-test-pull-request/63463/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55698/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17508/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/61478/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55623/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63384/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63463/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55698/console">Example</a></summary>

```
not ok 3948 parallel/test-file-write-stream4
  ---
  duration_ms: 360061.32400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55679/](https://ci.nodejs.org/job/node-test-pull-request/63390/), [https://github.com/nodejs/node/pull/53079/](https://ci.nodejs.org/job/node-test-pull-request/63399/), [https://github.com/nodejs/node/pull/55710/](https://ci.nodejs.org/job/node-test-pull-request/63412/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55649/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/31120/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55631/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63390/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63412/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55649/console">Example</a></summary>

```
not ok 4125 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360111.72700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>benchmark/test-benchmark-http2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54793/](https://ci.nodejs.org/job/node-test-pull-request/63394/), [https://github.com/nodejs/node/pull/55708/](https://ci.nodejs.org/job/node-test-pull-request/63460/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/25540/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/25496/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63394/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63460/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/25540/console">Example</a></summary>

```
not ok 184 benchmark/test-benchmark-http2
  ---
  duration_ms: 2156.00900
  severity: fail
  exitcode: 1
  stack: |-
    Error: test-double-http2 failed with 3221226505.
        at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-native-suites\node\benchmark\_http-benchmarkers.js:251:16)
        at Object.onceWrapper (node:events:632:26)
        at ChildProcess.emit (node:events:517:28)
        at maybeClose (node:internal/child_process:1098:16)
        at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    node:assert:125
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    3221226505 !== 0
    
        at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-native-suites\node\test\common\benchmark.js:28:12)
        at ChildProcess.emit (node:events:517:28)
        at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTIO...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55749/](https://ci.nodejs.org/job/node-test-pull-request/63457/), [https://github.com/nodejs/node/pull/55748/](https://ci.nodejs.org/job/node-test-pull-request/63458/)) |
| Appeared | [test-ibm-rhel8-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61552/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63457/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63458/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61552/console">Example</a></summary>

```
not ok 954 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 120046.17100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:3494674) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    (node:3494674) [DEP0030] DeprecationWarning: SlowBuffer() is deprecated. Please use Buffer.allocUnsafeSlow()
  ...

```
</details>

-------

| Reason | <code>parallel/test-os</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55719/](https://ci.nodejs.org/job/node-test-pull-request/63433/), [https://github.com/nodejs/node/pull/55739/](https://ci.nodejs.org/job/node-test-pull-request/63468/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/31181/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/31181/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/31181/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/31181/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31181/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/31172/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/31172/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31172/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/31169/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/31169/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022/31169/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31169/console), [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/31156/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/31156/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31156/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63433/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63468/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/31181/console">Example</a></summary>

```
not ok 601 parallel/test-os
  ---
  duration_ms: 157.01100
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:90
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    0 !== 5
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-os.js:90:10)
        at Module._compile (node:internal/modules/cjs/loader:1550:14)
        at Object..js (node:internal/modules/cjs/loader:1702:10)
        at Module.load (node:internal/modules/cjs/loader:1307:32)
        at Function._load (node:internal/modules/cjs/loader:1121:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
        at node:internal/main/run_main_module:36:49 {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 0,
      exp...
```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55719/](https://ci.nodejs.org/job/node-test-pull-request/63433/), [https://github.com/nodejs/node/pull/54896/](https://ci.nodejs.org/job/node-test-pull-request/63453/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55691/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63433/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63453/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55691/console">Example</a></summary>

```
not ok 4128 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 360064.83100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-util-getcallsites</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/53079/](https://ci.nodejs.org/job/node-test-pull-request/63391/), [https://github.com/nodejs/node/pull/55589/](https://ci.nodejs.org/job/node-test-pull-request/63407/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/31128/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/31128/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022/31128/console), [test-rackspace-win2022_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/31128/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/31128/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/31127/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022/31127/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/31125/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/47265/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63391/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63407/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/31128/console">Example</a></summary>

```
not ok 860 parallel/test-util-getcallsites
  ---
  duration_ms: 988.00500
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:768
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /typescript\/ts\/test-get-callsite\.ts/. Input:
    
    'getCallSite:  [Object: null prototype] {\n' +
      "  functionName: '',\n" +
      "  scriptName: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\fixtures\\\\typescript\\\\ts\\\\test-get-callsite.ts',\n" +
      '  lineNumber: 2,\n' +
      '  column: 18\n' +
      '}\n'
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-util-getcallsites.js:146:10)
        at Module._compile (node:internal/modules/cjs/loader:1584:14)
        at Object..js (node:internal/modules/cjs/loader:1736:10)
        at Module.load (node:internal/modules/cjs/loader:1307:32)
        at Function._load (node:internal/modules/cjs/loader:1121:12)
      ...
```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55679/](https://ci.nodejs.org/job/node-test-pull-request/63390/), [https://github.com/nodejs/node/pull/53079/](https://ci.nodejs.org/job/node-test-pull-request/63391/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47265/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63390/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63391/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47265/console">Example</a></summary>

```
not ok 3905 parallel/test-without-async-context-frame
  ---
  duration_ms: 120068.32800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ without AsyncContextFrame
      ✔ async-hooks/test-async-local-storage-socket.js (4940.073003ms)
      ✔ async-hooks/test-async-local-storage-async-functions.js (5423.789148ms)
      ✔ async-hooks/test-async-local-storage-gcable.js (4345.289505ms)
      ✔ async-hooks/test-async-local-storage-nested.js (5311.63463ms)
      ✔ async-hooks/test-async-local-storage-http.js (7470.063989ms)
      ✔ async-hooks/test-async-local-storage-dgram.js (6371.226688ms)
      ✔ async-hooks/test-async-local-storage-misc-stores.js (5015.713218ms)
      ✔ async-hooks/test-async-local-storage-no-mix-contexts.js (5551.639561ms)
      ✔ async-hooks/test-async-local-storage-tlssocket.js (6173.194515ms)
      ✔ async-hooks/test-async-local-storage-errors.js (5228.199649ms)
      ✔ async-hooks/test-async-local-storage-thenable.js (5024.532414ms)
      ✔ async-hooks/test-async-local-stora...
```
</details>

-------


### Jenkins Failure


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55679/](https://ci.nodejs.org/job/node-test-pull-request/63390/), [https://github.com/nodejs/node/pull/52587/](https://ci.nodejs.org/job/node-test-pull-request/63400/), [https://github.com/nodejs/node/pull/55711/](https://ci.nodejs.org/job/node-test-pull-request/63413/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/61505/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61492/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63390/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63413/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/61505/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1239)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1310)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/55551/](https://ci.nodejs.org/job/node-test-pull-request/63393/), [https://github.com/nodejs/node/pull/55711/](https://ci.nodejs.org/job/node-test-pull-request/63413/), [https://github.com/nodejs/node/pull/44878/](https://ci.nodejs.org/job/node-test-pull-request/63421/), [https://github.com/nodejs/node/pull/55514/](https://ci.nodejs.org/job/node-test-pull-request/63428/), [https://github.com/nodejs/node/pull/54896/](https://ci.nodejs.org/job/node-test-pull-request/63446/), [https://github.com/nodejs/node/pull/55728/](https://ci.nodejs.org/job/node-test-pull-request/63454/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47332/console), [test-orka-macos11-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61934/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61929/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61516/console), [test-orka-macos10.15-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61907/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/56307/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/47296/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47266/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63393/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63454/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47332/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/52587/](https://ci.nodejs.org/job/node-test-pull-request/63400/), [https://github.com/nodejs/node/pull/55605/](https://ci.nodejs.org/job/node-test-pull-request/63405/), [https://github.com/nodejs/node/pull/44878/](https://ci.nodejs.org/job/node-test-pull-request/63421/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55661/console), [test-equinix-ubuntu1804_sharedlibs_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu1804-arm64/55661/console), [test-osuosl-aix72-ppc64_be-3](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/54534/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=debian11-armv7l/14464/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14447/console), [test-osuosl-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/14447/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/14434/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63400/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63421/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55661/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54793/](https://ci.nodejs.org/job/node-test-pull-request/63394/), [https://github.com/nodejs/node/pull/44878/](https://ci.nodejs.org/job/node-test-pull-request/63421/), [https://github.com/nodejs/node/pull/55708/](https://ci.nodejs.org/job/node-test-pull-request/63427/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/46649/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/46644/console), [test-digitalocean-freebsd12-x64-2](https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd12-x64/57495/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63394/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63427/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/46649/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54793/](https://ci.nodejs.org/job/node-test-pull-request/63394/), [https://github.com/nodejs/node/pull/55602/](https://ci.nodejs.org/job/node-test-pull-request/63452/), [https://github.com/nodejs/node/pull/55708/](https://ci.nodejs.org/job/node-test-pull-request/63460/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2022-x86/25209/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63394/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63460/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2022-x86/25209/console">Example</a></summary>

```
ERROR: Step �Publish JUnit test result report� failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54896/](https://ci.nodejs.org/job/node-test-pull-request/63389/), [https://github.com/nodejs/node/pull/44878/](https://ci.nodejs.org/job/node-test-pull-request/63421/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39222/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63389/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63421/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39222/console">Example</a></summary>

```
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for node-test-commit-custom-suites-freestyle #39222
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>ERROR: Step ‘Record fingerprints of files to track usage’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54896/](https://ci.nodejs.org/job/node-test-pull-request/63389/), [https://github.com/nodejs/node/pull/55602/](https://ci.nodejs.org/job/node-test-pull-request/63452/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/61540/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/61484/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63389/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63452/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/61540/console">Example</a></summary>

```
ERROR: Step ‘Record fingerprints of files to track usage’ failed: no workspace for node-test-commit-linux/nodes=debian11-x64 #61540
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>Error: Command failed: /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/function_args</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55708/](https://ci.nodejs.org/job/node-test-pull-request/63460/), [https://github.com/nodejs/node/pull/55740/](https://ci.nodejs.org/job/node-test-pull-request/63470/)) |
| Appeared | [test-orka-macos10.15-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61949/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63460/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63470/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61949/console">Example</a></summary>

```
Error: Command failed: /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/function_args
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@18.20.5-pre | darwin | x64
gyp info chdir /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/function_args
gyp info find Python using Python version 3.7.7 found at "/usr/local/opt/python/bin/python3.7"
```
</details>

-------

| Reason | <code>Error: Command failed: /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/function_call</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55708/](https://ci.nodejs.org/job/node-test-pull-request/63427/), [https://github.com/nodejs/node/pull/55602/](https://ci.nodejs.org/job/node-test-pull-request/63472/)) |
| Appeared | [test-orka-macos10.15-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61959/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63427/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63472/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61959/console">Example</a></summary>

```
Error: Command failed: /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/function_call
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@18.20.5-pre | darwin | x64
gyp info chdir /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/function_call
gyp info find Python using Python version 3.7.7 found at "/usr/local/opt/python/bin/python3.7"
```
</details>

-------

| Reason | <code>Error: list index out of range</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/52587/](https://ci.nodejs.org/job/node-test-pull-request/63400/), [https://github.com/nodejs/node/pull/44878/](https://ci.nodejs.org/job/node-test-pull-request/63421/)) |
| Appeared | [test-equinix-debian11_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/14464/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63400/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63421/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/14464/console">Example</a></summary>

```
Error: list index out of range
POST BUILD TASK : FAILURE
END OF POST BUILD TASK : 0
Recording test results
[Checks API] No suitable checks publisher found.
[PostBuildScript] - [INFO] Executing post build scripts.
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54896/](https://ci.nodejs.org/job/node-test-pull-request/63389/), [https://github.com/nodejs/node/pull/55551/](https://ci.nodejs.org/job/node-test-pull-request/63393/)) |
| Appeared | [test-digitalocean-rhel9_arm_cross_container-x64-2](https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel9-armv7-gcc-12-glibc-2.28/50663/console), [test-digitalocean-ubi81_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/47266/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/47263/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/47263/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63389/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63393/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel9-armv7-gcc-12-glibc-2.28/50663/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------

