Failures in [node-test-pull-request/62882](https://ci.nodejs.org/job/node-test-pull-request/62882/) to [node-test-pull-request/62980](https://ci.nodejs.org/job/node-test-pull-request/62980/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-10-08.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-10-08 00:09 | 0       | 17      | 17       | 3       | 63      | 17.53%     |


### JSTest Failure

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/55170/](https://ci.nodejs.org/job/node-test-pull-request/62889/), [https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62890/), [https://github.com/nodejs/node/pull/55260/](https://ci.nodejs.org/job/node-test-pull-request/62916/), [https://github.com/nodejs/node/pull/55202/](https://ci.nodejs.org/job/node-test-pull-request/62921/), [https://github.com/nodejs/node/pull/55261/](https://ci.nodejs.org/job/node-test-pull-request/62929/), [https://github.com/nodejs/node/pull/54721/](https://ci.nodejs.org/job/node-test-pull-request/62939/), [https://github.com/nodejs/node/pull/55055/](https://ci.nodejs.org/job/node-test-pull-request/62947/), [https://github.com/nodejs/node/pull/54505/](https://ci.nodejs.org/job/node-test-pull-request/62964/)) |
| Appeared | [test-macstadium-macos11.0-arm64-4](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17033/console), [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/61437/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17007/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62889/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62964/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17033/console">Example</a></summary>

```
not ok 4202 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3280.89700
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx-arm/nodes/osx11/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v23.0.0-pre
  ...

```
</details>

-------

| Reason | <code>es-module/test-loaders-workers-spawned</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/55255/](https://ci.nodejs.org/job/node-test-pull-request/62912/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62920/), [https://github.com/nodejs/node/pull/55274/](https://ci.nodejs.org/job/node-test-pull-request/62928/), [https://github.com/nodejs/node/pull/55276/](https://ci.nodejs.org/job/node-test-pull-request/62930/), [https://github.com/nodejs/node/pull/55231/](https://ci.nodejs.org/job/node-test-pull-request/62933/), [https://github.com/nodejs/node/pull/54721/](https://ci.nodejs.org/job/node-test-pull-request/62939/), [https://github.com/nodejs/node/pull/55217/](https://ci.nodejs.org/job/node-test-pull-request/62972/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/46844/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/46819/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46811/console), [test-ibm-alpine319_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/61049/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62912/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62972/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/46844/console">Example</a></summary>

```
not ok 236 es-module/test-loaders-workers-spawned
  ---
  duration_ms: 1561.50700
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: Worker threads do not spawn infinitely
        # Subtest: should not trigger an infinite loop when using a loader exports no recognized hooks
        ok 1 - should not trigger an infinite loop when using a loader exports no recognized hooks
          ---
          duration_ms: 240.688935
          ...

```
</details>

-------

| Reason | <code>node-api/test_threadsafe_function/test</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/54563/](https://ci.nodejs.org/job/node-test-pull-request/62882/), [https://github.com/nodejs/node/pull/54679/](https://ci.nodejs.org/job/node-test-pull-request/62919/), [https://github.com/nodejs/node/pull/54777/](https://ci.nodejs.org/job/node-test-pull-request/62940/), [https://github.com/nodejs/node/pull/55228/](https://ci.nodejs.org/job/node-test-pull-request/62948/), [https://github.com/nodejs/node/pull/55250/](https://ci.nodejs.org/job/node-test-pull-request/62971/), [https://github.com/nodejs/node/pull/55217/](https://ci.nodejs.org/job/node-test-pull-request/62972/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/14065/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62882/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62972/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=native,nodes=ubuntu2204-armv7l/14065/console">Example</a></summary>

```
not ok 144 node-api/test_threadsafe_function/test
  ---
  duration_ms: 360016.09000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/55071/](https://ci.nodejs.org/job/node-test-pull-request/62883/), [https://github.com/nodejs/node/pull/54295/](https://ci.nodejs.org/job/node-test-pull-request/62897/), [https://github.com/nodejs/node/pull/55234/](https://ci.nodejs.org/job/node-test-pull-request/62901/), [https://github.com/nodejs/node/pull/55202/](https://ci.nodejs.org/job/node-test-pull-request/62914/), [https://github.com/nodejs/node/pull/54630/](https://ci.nodejs.org/job/node-test-pull-request/62949/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62965/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55244/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57215/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/46813/console), [test-equinix_mnx-smartos20-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57187/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46774/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55171/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62883/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62965/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/55244/console">Example</a></summary>

```
not ok 4112 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 360028.75900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55114/](https://ci.nodejs.org/job/node-test-pull-request/62910/), [https://github.com/nodejs/node/pull/55255/](https://ci.nodejs.org/job/node-test-pull-request/62911/), [https://github.com/nodejs/node/pull/55228/](https://ci.nodejs.org/job/node-test-pull-request/62948/), [https://github.com/nodejs/node/pull/55287/](https://ci.nodejs.org/job/node-test-pull-request/62976/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55254/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55229/console), [test-equinix_mnx-smartos20-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos20-64/57179/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62910/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62976/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55254/console">Example</a></summary>

```
not ok 4091 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360116.36900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62917/), [https://github.com/nodejs/node/pull/54679/](https://ci.nodejs.org/job/node-test-pull-request/62919/), [https://github.com/nodejs/node/pull/55114/](https://ci.nodejs.org/job/node-test-pull-request/62963/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46834/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46796/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62917/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62963/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46834/console">Example</a></summary>

```
not ok 568 parallel/test-async-context-frame
  ---
  duration_ms: 120155.62600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    ▶ AsyncContextFrame
      ✔ async-hooks/test-async-local-storage-socket.js (5154.733459ms)
      ✔ async-hooks/test-async-local-storage-async-functions.js (4230.147158ms)
      ✔ async-hooks/test-async-local-storage-gcable.js (4911.843873ms)
      ✔ async-hooks/test-async-local-storage-nested.js (4631.327168ms)
      ✔ async-hooks/test-async-local-storage-http.js (5361.551007ms)
      ✔ async-hooks/test-async-local-storage-dgram.js (5389.472123ms)
      ✔ async-hooks/test-async-local-storage-misc-stores.js (5452.254525ms)
      ✔ async-hooks/test-async-local-storage-no-mix-contexts.js (5167.043554ms)
      ✔ async-hooks/test-async-local-storage-tlssocket.js (4984.096727ms)
      ✔ async-hooks/test-async-local-storage-errors.js (4903.992053ms)
      ✔ async-hooks/test-async-local-storage-thenable.js (4911.232649ms)
      ✔ async-hooks/test-async-local-storage-promises.js (...
```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54630/](https://ci.nodejs.org/job/node-test-pull-request/62949/), [https://github.com/nodejs/node/pull/55287/](https://ci.nodejs.org/job/node-test-pull-request/62957/), [https://github.com/nodejs/node/pull/55171/](https://ci.nodejs.org/job/node-test-pull-request/62980/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46849/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/30709/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62949/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62980/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46849/console">Example</a></summary>

```
not ok 4171 wpt/test-compression
  ---
  duration_ms: 1440029.39200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to throw
    [PASS] "a" should cause the constructor to throw
    [PASS] no inpu...
```
</details>

-------

| Reason | <code>parallel/test-performance-eventlooputil</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55170/](https://ci.nodejs.org/job/node-test-pull-request/62889/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62934/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61052/console), [test-ibm-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/61000/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62889/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62934/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61052/console">Example</a></summary>

```
not ok 2429 parallel/test-performance-eventlooputil
  ---
  duration_ms: 178.93400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: 75.8161449432373 < 75.81614502539063
        at Timeout.runCalcTest (/home/iojs/build/workspace/node/test/parallel/test-performance-eventlooputil.js:85:10)
        at Timeout.runCalcTest [as _onTimeout] (/home/iojs/build/workspace/node/test/common/index.js:491:15)
        at listOnTimeout (node:internal/timers:616:11)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v23.0.0-pre
  ...

```
</details>

-------

| Reason | <code>pummel/test-hash-seed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62888/), [https://github.com/nodejs/node/pull/54777/](https://ci.nodejs.org/job/node-test-pull-request/62940/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61060/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62888/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62940/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/61060/console">Example</a></summary>

```
not ok 3891 pummel/test-hash-seed
  ---
  duration_ms: 68483.19100
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/errors:983
      const err = new Error(message);
                  ^
    
    Error: Command failed: /home/iojs/build/workspace/node/out/Release/node --allow-natives-syntax /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js
    /home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163
      throw new Error('no candidates remaining');
      ^
    
    Error: no candidates remaining
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/fixtures/guess-hash-seed.js:163:9)
        at Module._compile (node:internal/modules/cjs/loader:1560:14)
        at Object..js (node:internal/modules/cjs/loader:1703:10)
        at Module.load (node:internal/modules/cjs/loader:1328:32)
        at Function._load (node:internal/modules/cjs/loader:1138:12)
        at TracingChannel.traceSync (node:diagnostics_channel:315:14)
        at wrapModuleLoad (node:internal/mod...
```
</details>

-------

| Reason | <code>pummel/test-heapdump-shadow-realm</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/50853/](https://ci.nodejs.org/job/node-test-pull-request/62923/), [https://github.com/nodejs/node/pull/55291/](https://ci.nodejs.org/job/node-test-pull-request/62955/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/15383/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62923/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62955/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/15383/console">Example</a></summary>

```
not ok 3896 pummel/test-heapdump-shadow-realm
  ---
  duration_ms: 5517.29100
  severity: crashed
  exitcode: -5
  stack: |-
    (node:1001567) internal/test/binding: These APIs are for internal testing only. Do not use them.
    (Use `node --trace-warnings ...` to show where the warning was created)
    
    
    #
    # Fatal error in ../deps/v8/src/profiler/heap-snapshot-generator.cc, line 625
    # Debug check failed: is_native_object_bool == entry_info.id % 2 == 0 (1 vs. 0).
    #
    #
    #
    #FailureMessage Object: 0xfffff82e0cc8
    ----- Native stack trace -----
    
     1: 0xaaaac3a8efe4 node::DumpNativeBacktrace(_IO_FILE*) [out/Debug/node]
     2: 0xaaaac3ce7874  [out/Debug/node]
     3: 0xaaaac3ce78a8  [out/Debug/node]
     4: 0xaaaac62d60d0 V8_Fatal(char const*, int, char const*, ...) [out/Debug/node]
     5: 0xaaaac62d6118  [out/Debug/node]
     6: 0xaaaac4be5c38 v8::internal::HeapObjectsMap::FindOrAddEntry(unsigned long, unsigned int, v8::internal::HeapObjectsMap::MarkEntryAccessed, v8::int...
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55231/](https://ci.nodejs.org/job/node-test-pull-request/62894/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62936/), [https://github.com/nodejs/node/pull/50853/](https://ci.nodejs.org/job/node-test-pull-request/62956/), [https://github.com/nodejs/node/pull/55160/](https://ci.nodejs.org/job/node-test-pull-request/62962/)) |
| Appeared | [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61076/console), [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61071/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62894/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62962/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61076/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1239)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1310)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
```
</details>

-------


### Build Failure

| Reason | <code>Error: invalid syntax</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 13 ([https://github.com/nodejs/node/pull/53848/](https://ci.nodejs.org/job/node-test-pull-request/62888/), [https://github.com/nodejs/node/pull/55170/](https://ci.nodejs.org/job/node-test-pull-request/62891/), [https://github.com/nodejs/node/pull/55231/](https://ci.nodejs.org/job/node-test-pull-request/62894/), [https://github.com/nodejs/node/pull/55255/](https://ci.nodejs.org/job/node-test-pull-request/62912/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62920/), [https://github.com/nodejs/node/pull/55274/](https://ci.nodejs.org/job/node-test-pull-request/62928/), [https://github.com/nodejs/node/pull/55276/](https://ci.nodejs.org/job/node-test-pull-request/62930/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62936/), [https://github.com/nodejs/node/pull/54777/](https://ci.nodejs.org/job/node-test-pull-request/62940/), [https://github.com/nodejs/node/pull/50853/](https://ci.nodejs.org/job/node-test-pull-request/62956/), [https://github.com/nodejs/node/pull/55161/](https://ci.nodejs.org/job/node-test-pull-request/62961/), [https://github.com/nodejs/node/pull/55160/](https://ci.nodejs.org/job/node-test-pull-request/62962/), [https://github.com/nodejs/node/pull/53160/](https://ci.nodejs.org/job/node-test-pull-request/62975/)) |
| Appeared | [test-rackspace-debian10-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian10-x64/60964/console), [test-orka-macos10.15-x64-1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61380/console), [test-orka-macos10.15-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx1015/61376/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62888/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62975/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian10-x64/60964/console">Example</a></summary>

```
Error: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/home/iojs/build/workspace/node/deps/npm/node_modules/node-gyp/lib/configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/55014/](https://ci.nodejs.org/job/node-test-pull-request/62895/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62920/), [https://github.com/nodejs/node/pull/55202/](https://ci.nodejs.org/job/node-test-pull-request/62921/), [https://github.com/nodejs/node/pull/55239/](https://ci.nodejs.org/job/node-test-pull-request/62952/), [https://github.com/nodejs/node/pull/55172/](https://ci.nodejs.org/job/node-test-pull-request/62953/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55233/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/46827/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/57082/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/46797/console), [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/16969/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62895/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62953/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/55233/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55260/](https://ci.nodejs.org/job/node-test-pull-request/62916/), [https://github.com/nodejs/node/pull/55262/](https://ci.nodejs.org/job/node-test-pull-request/62918/), [https://github.com/nodejs/node/pull/55161/](https://ci.nodejs.org/job/node-test-pull-request/62961/), [https://github.com/nodejs/node/pull/54505/](https://ci.nodejs.org/job/node-test-pull-request/62964/)) |
| Appeared | [test-ibm-rhel9_arm_cross_container-x64-1](https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel9-armv7-gcc-12-glibc-2.28/50305/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/46833/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/46833/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-7](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/46795/console), [test-digitalocean-rhel8_arm_cross_container-x64-1](https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel8-armv7-gcc-10-glibc-2.28/50268/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62916/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62964/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-cross-compile/nodes=cross-compiler-rhel9-armv7-gcc-12-glibc-2.28/50305/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54295/](https://ci.nodejs.org/job/node-test-pull-request/62887/), [https://github.com/nodejs/node/pull/55241/](https://ci.nodejs.org/job/node-test-pull-request/62931/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/75008/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/62887/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/62931/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/75008/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

