Failures in [node-test-pull-request/63524](https://ci.nodejs.org/job/node-test-pull-request/63524/) to [node-test-pull-request/63615](https://ci.nodejs.org/job/node-test-pull-request/63615/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2024-11-19.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2024-11-19 00:10 | 4       | 14      | 19       | 25      | 38      | 19.72%     |


### Jenkins Failure

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 3575467, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55828/](https://ci.nodejs.org/job/node-test-pull-request/63547/), [https://github.com/nodejs/node/pull/55851/](https://ci.nodejs.org/job/node-test-pull-request/63548/)) |
| Appeared | [test-ibm-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/61628/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63547/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63548/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/61628/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 3575467, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.462.3//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.462.3//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.462.3//hudson.Launcher$LocalLauncher.launch(Launcher.java:994)
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/55828/](https://ci.nodejs.org/job/node-test-pull-request/63534/), [https://github.com/nodejs/node/pull/55778/](https://ci.nodejs.org/job/node-test-pull-request/63537/), [https://github.com/nodejs/node/pull/55811/](https://ci.nodejs.org/job/node-test-pull-request/63538/), [https://github.com/nodejs/node/pull/55714/](https://ci.nodejs.org/job/node-test-pull-request/63539/), [https://github.com/nodejs/node/pull/55217/](https://ci.nodejs.org/job/node-test-pull-request/63541/), [https://github.com/nodejs/node/pull/51192/](https://ci.nodejs.org/job/node-test-pull-request/63542/), [https://github.com/nodejs/node/pull/55757/](https://ci.nodejs.org/job/node-test-pull-request/63543/), [https://github.com/nodejs/node/pull/55851/](https://ci.nodejs.org/job/node-test-pull-request/63544/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/75780/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63534/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63544/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/75780/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55850/](https://ci.nodejs.org/job/node-test-pull-request/63549/), [https://github.com/nodejs/node/pull/51192/](https://ci.nodejs.org/job/node-test-pull-request/63589/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47453/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63549/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63589/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/47453/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/55757/](https://ci.nodejs.org/job/node-test-pull-request/63561/), [https://github.com/nodejs/node/pull/55270/](https://ci.nodejs.org/job/node-test-pull-request/63566/), [https://github.com/nodejs/node/pull/54181/](https://ci.nodejs.org/job/node-test-pull-request/63585/), [https://github.com/nodejs/node/pull/55895/](https://ci.nodejs.org/job/node-test-pull-request/63607/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55825/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55807/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/39358/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/61646/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63561/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63607/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/55825/console">Example</a></summary>

```
not ok 3945 parallel/test-file-write-stream4
  ---
  duration_ms: 360089.58400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-http-server-request-timeouts-mixed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55828/](https://ci.nodejs.org/job/node-test-pull-request/63529/), [https://github.com/nodejs/node/pull/55778/](https://ci.nodejs.org/job/node-test-pull-request/63565/)) |
| Appeared | [test-macstadium-macos11.0-arm64-3](https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17619/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/63529/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/63565/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx-arm/nodes=osx11/17619/console">Example</a></summary>

```
not ok 4229 sequential/test-http-server-request-timeouts-mixed
  ---
  duration_ms: 3245.39900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(request2.completed)
    
        at Timeout._onTimeout (/Users/iojs/build/workspace/node-test-commit-osx-arm/nodes/osx11/test/sequential/test-http-server-request-timeouts-mixed.js:108:5)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

