Failures in [node-test-pull-request/69028](https://ci.nodejs.org/job/node-test-pull-request/69028/) to [node-test-pull-request/69122](https://ci.nodejs.org/job/node-test-pull-request/69122/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-09-08.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-09-08 00:12 | 2       | 20      | 19       | 3       | 56      | 21.05%     |


### JSTest Failure

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-cli</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/59071/](https://ci.nodejs.org/job/node-test-pull-request/69042/), [https://github.com/nodejs/node/pull/59751/](https://ci.nodejs.org/job/node-test-pull-request/69043/), [https://github.com/nodejs/node/pull/59600/](https://ci.nodejs.org/job/node-test-pull-request/69049/), [https://github.com/nodejs/node/pull/59744/](https://ci.nodejs.org/job/node-test-pull-request/69051/), [https://github.com/nodejs/node/pull/59578/](https://ci.nodejs.org/job/node-test-pull-request/69054/), [https://github.com/nodejs/node/pull/59379/](https://ci.nodejs.org/job/node-test-pull-request/69055/), [https://github.com/nodejs/node/pull/57666/](https://ci.nodejs.org/job/node-test-pull-request/69060/), [https://github.com/nodejs/node/pull/59710/](https://ci.nodejs.org/job/node-test-pull-request/69061/), [https://github.com/nodejs/node/pull/59447/](https://ci.nodejs.org/job/node-test-pull-request/69062/), [https://github.com/nodejs/node/pull/59750/](https://ci.nodejs.org/job/node-test-pull-request/69065/), [https://github.com/nodejs/node/pull/59495/](https://ci.nodejs.org/job/node-test-pull-request/69066/), [https://github.com/nodejs/node/pull/59766/](https://ci.nodejs.org/job/node-test-pull-request/69067/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60655/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60653/console), [test-osuosl-rhel8-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60639/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69042/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69067/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60655/console">Example</a></summary>

```
not ok 4752 sequential/test-single-executable-application-exec-argv-extension-cli
  ---
  duration_ms: 11232.61900
  severity: fail
  exitcode: 1
  stack: |-
    Copied /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/out/Release/node to /home/iojs/node-tmp/.tmp.4751/sea
    Injected /home/iojs/node-tmp/.tmp.4751/sea-prep.blob into /home/iojs/node-tmp/.tmp.4751/sea
    [process 1326364]: --- stderr ---
    
    [process 1326364]: --- stdout ---
    
    [process 1326364]: status = null, signal = SIGSEGV
    /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/test/sequential/test-single-executable-application-exec-argv-extension-cli.js:50:1)
        at Module._compile (node:internal/m...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-env</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/59071/](https://ci.nodejs.org/job/node-test-pull-request/69042/), [https://github.com/nodejs/node/pull/59751/](https://ci.nodejs.org/job/node-test-pull-request/69043/), [https://github.com/nodejs/node/pull/59600/](https://ci.nodejs.org/job/node-test-pull-request/69049/), [https://github.com/nodejs/node/pull/59744/](https://ci.nodejs.org/job/node-test-pull-request/69051/), [https://github.com/nodejs/node/pull/59578/](https://ci.nodejs.org/job/node-test-pull-request/69054/), [https://github.com/nodejs/node/pull/59379/](https://ci.nodejs.org/job/node-test-pull-request/69055/), [https://github.com/nodejs/node/pull/57666/](https://ci.nodejs.org/job/node-test-pull-request/69060/), [https://github.com/nodejs/node/pull/59710/](https://ci.nodejs.org/job/node-test-pull-request/69061/), [https://github.com/nodejs/node/pull/59447/](https://ci.nodejs.org/job/node-test-pull-request/69062/), [https://github.com/nodejs/node/pull/59750/](https://ci.nodejs.org/job/node-test-pull-request/69065/), [https://github.com/nodejs/node/pull/59495/](https://ci.nodejs.org/job/node-test-pull-request/69066/), [https://github.com/nodejs/node/pull/59766/](https://ci.nodejs.org/job/node-test-pull-request/69067/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60655/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60653/console), [test-osuosl-rhel8-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60639/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69042/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69067/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60655/console">Example</a></summary>

```
not ok 4753 sequential/test-single-executable-application-exec-argv-extension-env
  ---
  duration_ms: 10938.95100
  severity: fail
  exitcode: 1
  stack: |-
    Copied /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/out/Release/node to /home/iojs/node-tmp/.tmp.4752/sea
    Injected /home/iojs/node-tmp/.tmp.4752/sea-prep.blob into /home/iojs/node-tmp/.tmp.4752/sea
    [process 1326389]: --- stderr ---
    
    [process 1326389]: --- stdout ---
    
    [process 1326389]: status = null, signal = SIGSEGV
    /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/test/sequential/test-single-executable-application-exec-argv-extension-env.js:50:1)
        at Module._compile (node:internal/m...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-none</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/59071/](https://ci.nodejs.org/job/node-test-pull-request/69042/), [https://github.com/nodejs/node/pull/59751/](https://ci.nodejs.org/job/node-test-pull-request/69043/), [https://github.com/nodejs/node/pull/59600/](https://ci.nodejs.org/job/node-test-pull-request/69049/), [https://github.com/nodejs/node/pull/59744/](https://ci.nodejs.org/job/node-test-pull-request/69051/), [https://github.com/nodejs/node/pull/59578/](https://ci.nodejs.org/job/node-test-pull-request/69054/), [https://github.com/nodejs/node/pull/59379/](https://ci.nodejs.org/job/node-test-pull-request/69055/), [https://github.com/nodejs/node/pull/57666/](https://ci.nodejs.org/job/node-test-pull-request/69060/), [https://github.com/nodejs/node/pull/59710/](https://ci.nodejs.org/job/node-test-pull-request/69061/), [https://github.com/nodejs/node/pull/59447/](https://ci.nodejs.org/job/node-test-pull-request/69062/), [https://github.com/nodejs/node/pull/59750/](https://ci.nodejs.org/job/node-test-pull-request/69065/), [https://github.com/nodejs/node/pull/59495/](https://ci.nodejs.org/job/node-test-pull-request/69066/), [https://github.com/nodejs/node/pull/59766/](https://ci.nodejs.org/job/node-test-pull-request/69067/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60655/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60653/console), [test-osuosl-rhel8-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60639/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69042/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69067/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60655/console">Example</a></summary>

```
not ok 4754 sequential/test-single-executable-application-exec-argv-extension-none
  ---
  duration_ms: 10930.94600
  severity: fail
  exitcode: 1
  stack: |-
    Copied /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/out/Release/node to /home/iojs/node-tmp/.tmp.4753/sea
    Injected /home/iojs/node-tmp/.tmp.4753/sea-prep.blob into /home/iojs/node-tmp/.tmp.4753/sea
    [process 1326414]: --- stderr ---
    
    [process 1326414]: --- stdout ---
    
    [process 1326414]: status = null, signal = SIGSEGV
    /home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-plinux/nodes/rhel8-ppc64le/test/sequential/test-single-executable-application-exec-argv-extension-none.js:50:1)
        at Module._compile (node:internal...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59602/](https://ci.nodejs.org/job/node-test-pull-request/69070/), [https://github.com/nodejs/node/pull/59767/](https://ci.nodejs.org/job/node-test-pull-request/69073/), [https://github.com/nodejs/node/pull/59773/](https://ci.nodejs.org/job/node-test-pull-request/69094/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/69109/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58935/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69070/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69109/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58935/console">Example</a></summary>

```
not ok 4809 wpt/test-streams
  ---
  duration_ms: 1544.21900
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] a signal argument 'null' should cause pipeTo() to reject
    [PASS] a signal argument 'AbortSignal' should cause pipeTo() to reject
    [PASS] a signal argument 'true' should cause pipeTo() to reject
    [PASS] a signal argument '-1' should cause pipeTo() to reject
    [PASS] a signal argument '[object AbortSi...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59447/](https://ci.nodejs.org/job/node-test-pull-request/69045/), [https://github.com/nodejs/node/pull/59755/](https://ci.nodejs.org/job/node-test-pull-request/69048/), [https://github.com/nodejs/node/pull/59766/](https://ci.nodejs.org/job/node-test-pull-request/69089/)) |
| Appeared | [vm-hewo4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66655/console), [vm-6jxbv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66626/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69045/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69089/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66655/console">Example</a></summary>

```
not ok 4340 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 563.02100
  severity: fail
  exitcode: 1
  stack: |-
    #6 eneded response for: 'https://local\nhost:55405/newline-in-host'
    #5 eneded response for: 'https://local\r\nhost:55405/crlf-in-host'
    #4 eneded response for: 'https://local\rhost:55405/carriage-return-in-host'
    #3 eneded response for: 'https://localhost:5\r5405/carriage-return-in-port'
    #2 eneded response for: 'https://localhost:5\r\n5405/crlf-in-port'
    #1 eneded response for: 'https://localhost:5\n5405/newline-in-port'
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Set(8) {
    - Set(6) {
        {
    +     error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    +         at _write (node:internal/streams/writable:487:11)
    +         at Writable.write (node:internal/streams/writable:508:10)
    +      ...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59750/](https://ci.nodejs.org/job/node-test-pull-request/69047/), [https://github.com/nodejs/node/pull/57666/](https://ci.nodejs.org/job/node-test-pull-request/69057/), [https://github.com/nodejs/node/pull/59684/](https://ci.nodejs.org/job/node-test-pull-request/69116/)) |
| Appeared | [vm-6fm1x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66678/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60235/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69047/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69116/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66678/console">Example</a></summary>

```
not ok 3368 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 120061.11400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>async-hooks/test-emit-before-on-destroyed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59775/](https://ci.nodejs.org/job/node-test-pull-request/69080/), [https://github.com/nodejs/node/pull/59684/](https://ci.nodejs.org/job/node-test-pull-request/69116/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58942/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58910/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69080/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69116/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58942/console">Example</a></summary>

```
not ok 38 async-hooks/test-emit-before-on-destroyed
  ---
  duration_ms: 423.86700
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 1
    
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/async-hooks/test-emit-before-on-destroyed.js:56:12)
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/common/index.js:472:15)
        at ChildProcess.emit (node:events:508:28)
        at maybeClose (node:internal/child_process:1085:16)
        at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 1,
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69095/), [https://github.com/nodejs/node/pull/59684/](https://ci.nodejs.org/job/node-test-pull-request/69116/)) |
| Appeared | [vm-6fm1x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66678/console), [vm-y4wb2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66660/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69095/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69116/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66678/console">Example</a></summary>

```
not ok 2781 parallel/test-runner-run-watch
  ---
  duration_ms: 32548.54900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 230.254431,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>parallel/test-worker-nearheaplimit-deadlock</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59379/](https://ci.nodejs.org/job/node-test-pull-request/69055/), [https://github.com/nodejs/node/pull/59647/](https://ci.nodejs.org/job/node-test-pull-request/69086/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51430/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60670/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/52609/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69055/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69086/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51430/console">Example</a></summary>

```
not ok 3785 parallel/test-worker-nearheaplimit-deadlock
  ---
  duration_ms: 514.24800
  severity: crashed
  exitcode: -6
  stack: |-
    
    <--- Last few GCs --->
    
    [736788:0x3ff5c001000]       12 ms: Mark-Compact 1.4 (3.5) -> 1.4 (3.5) MB, pooled: 0.0 MB, 0.84 / 0.00 ms (average mu = 0.508, current mu = 0.252) background allocation failure; GC in old space requested
    [736788:0x3ff5c001000]       13 ms: Mark-Compact 1.4 (3.5) -> 1.4 (3.5) MB, pooled: 0.0 MB, 0.71 / 0.00 ms (average mu = 0.398, current mu = 0.114) background allocation failure; GC in old space requested
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 0x1dc1e56 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [out/Release/node]
     2: 0x219ab04 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [out/Release/node]
     3: 0x257ccba  [out/Release/node]
     4: 0x25c060e v8::internal:...
```
</details>

-------

| Reason | <code>pummel/test-timers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59663/](https://ci.nodejs.org/job/node-test-pull-request/69036/), [https://github.com/nodejs/node/pull/57666/](https://ci.nodejs.org/job/node-test-pull-request/69060/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60237/console), [vm-6n303](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66617/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69036/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69060/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60237/console">Example</a></summary>

```
not ok 4404 pummel/test-timers
  ---
  duration_ms: 2119.12300
  severity: fail
  exitcode: 1
  stack: |-
    diff: 1002
    diff: 1980
    node:internal/assert/utils:273
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert.ok(Math.abs(diff - t) < WINDOW * interval_count)
    
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm/test/pummel/test-timers.js:64:12)
        at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:472:15)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59710/](https://ci.nodejs.org/job/node-test-pull-request/69059/), [https://github.com/nodejs/node/pull/59495/](https://ci.nodejs.org/job/node-test-pull-request/69075/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36707/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69059/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69075/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36707/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59578/](https://ci.nodejs.org/job/node-test-pull-request/69054/), [https://github.com/nodejs/node/pull/59760/](https://ci.nodejs.org/job/node-test-pull-request/69071/), [https://github.com/nodejs/node/pull/59689/](https://ci.nodejs.org/job/node-test-pull-request/69088/), [https://github.com/nodejs/node/pull/59779/](https://ci.nodejs.org/job/node-test-pull-request/69107/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52650/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52632/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52608/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69054/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69107/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52650/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59710/](https://ci.nodejs.org/job/node-test-pull-request/69028/), [https://github.com/nodejs/node/pull/59071/](https://ci.nodejs.org/job/node-test-pull-request/69034/)) |
| Appeared | [test-azure-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60219/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69028/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69034/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60219/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59689/](https://ci.nodejs.org/job/node-test-pull-request/69093/), [https://github.com/nodejs/node/pull/59578/](https://ci.nodejs.org/job/node-test-pull-request/69117/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/52660/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/52636/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/52636/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69093/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69117/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/52660/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------

