Failures in [node-test-pull-request/64999](https://ci.nodejs.org/job/node-test-pull-request/64999/) to [node-test-pull-request/65100](https://ci.nodejs.org/job/node-test-pull-request/65100/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-10.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-10 00:10 | 9       | 15      | 14       | 16      | 46      | 20.00%     |


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65001/), [https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65016/), [https://github.com/nodejs/node/pull/56832/](https://ci.nodejs.org/job/node-test-pull-request/65027/), [https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/65030/), [https://github.com/nodejs/node/pull/56918/](https://ci.nodejs.org/job/node-test-pull-request/65047/), [https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65063/), [https://github.com/nodejs/node/pull/56970/](https://ci.nodejs.org/job/node-test-pull-request/65095/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65001/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65095/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65016/), [https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/65025/), [https://github.com/nodejs/node/pull/56832/](https://ci.nodejs.org/job/node-test-pull-request/65027/), [https://github.com/nodejs/node/pull/56918/](https://ci.nodejs.org/job/node-test-pull-request/65047/), [https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65063/), [https://github.com/nodejs/node/pull/56970/](https://ci.nodejs.org/job/node-test-pull-request/65095/)) |
| Appeared | [vm-9ml99](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63611/console), [vm-wsnp8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63583/console), [vm-cn7q6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63569/console), [vm-8vdtn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63550/console), [vm-jbbmk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63548/console), [vm-wtknr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63539/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65016/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65095/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63611/console">Example</a></summary>

```
not ok 2593 parallel/test-runner-run-watch
  ---
  duration_ms: 29959.73200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:292:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:307
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 229.350341,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/65008/), [https://github.com/nodejs/node/pull/56833/](https://ci.nodejs.org/job/node-test-pull-request/65039/), [https://github.com/nodejs/node/pull/56978/](https://ci.nodejs.org/job/node-test-pull-request/65090/), [https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65093/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57166/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57116/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65008/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65093/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57166/console">Example</a></summary>

```
not ok 4201 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360022.83900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65016/), [https://github.com/nodejs/node/pull/56805/](https://ci.nodejs.org/job/node-test-pull-request/65030/), [https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65092/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57165/console), [vm-4grcl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63553/console), [test-osuosl-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/57099/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65016/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65092/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57165/console">Example</a></summary>

```
not ok 4031 parallel/test-file-write-stream4
  ---
  duration_ms: 360032.97400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65022/), [https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65080/), [https://github.com/nodejs/node/pull/56765/](https://ci.nodejs.org/job/node-test-pull-request/65091/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/17177/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48961/console), [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48021/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65022/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/17177/console">Example</a></summary>

```
not ok 2569 parallel/test-runner-output
  ---
  duration_ms: 9191.27200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/test-runner-plan-timeout.js'
    Location: test/parallel/test-runner-output.mjs:312:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'TAP version 13\n' +
        '# Subtest: planning with wait\n' +
        '    # Subtest: planning with wait and passing\n' +
        '    ok 1 - planning with wait and passing\n' +
        '      ---\n' +
    ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-hex-string</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56968/](https://ci.nodejs.org/job/node-test-pull-request/65074/), [https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65092/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48974/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48958/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65074/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65092/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48974/console">Example</a></summary>

```
not ok 3566 parallel/test-net-write-fully-async-hex-string
  ---
  duration_ms: 120039.34100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56911/](https://ci.nodejs.org/job/node-test-pull-request/65009/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65010/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48896/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48895/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65009/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65010/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48896/console">Example</a></summary>

```
not ok 3626 parallel/test-without-async-context-frame
  ---
  duration_ms: 120106.83300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-zlib-brotli-16GB</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/65008/), [https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65022/)) |
| Appeared | [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48021/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48006/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65008/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65022/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48021/console">Example</a></summary>

```
not ok 3577 parallel/test-zlib-brotli-16GB
  ---
  duration_ms: 2390.49100
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:128
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    2 !== 4
    
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-commit-linuxone/test/parallel/test-zlib-brotli-16GB.js:22:3)
        at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-linuxone/test/common/index.js:435:15)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 2,
      expected: 4,
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65010/), [https://github.com/nodejs/node/pull/56911/](https://ci.nodejs.org/job/node-test-pull-request/65026/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48915/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/48896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65010/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65026/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48915/console">Example</a></summary>

```
not ok 4339 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7299.82500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:614:17)
        at process.processTimers (node:internal/timers:549:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-vm-timeout-escape-promise-module-2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65080/), [https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65093/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48081/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48069/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65080/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65093/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48081/console">Example</a></summary>

```
not ok 4386 sequential/test-vm-timeout-escape-promise-module-2
  ---
  duration_ms: 195.89700
  severity: fail
  exitcode: 1
  stack: |-
    (node:1941625) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    /home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-vm-timeout-escape-promise-module-2.js:22
          throw new Error(
                ^
    
    Error: escaped timeout at 100 milliseconds!
        at loop (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-vm-timeout-escape-promise-module-2.js:22:13)
        at vm:module(0):1:30
        at SourceTextModule.evaluate (node:internal/vm/module:227:23)
        at assert.rejects.code (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-vm-timeout-escape-promise-module-2.js:38:16)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    
    Node....
```
</details>

-------


### Jenkins Failure

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 2228979, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56765/](https://ci.nodejs.org/job/node-test-pull-request/65091/), [https://github.com/nodejs/node/pull/56961/](https://ci.nodejs.org/job/node-test-pull-request/65096/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/63120/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65091/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65096/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/63120/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 2228979, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.492.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.492.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.492.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56929/](https://ci.nodejs.org/job/node-test-pull-request/65021/), [https://github.com/nodejs/node/pull/56927/](https://ci.nodejs.org/job/node-test-pull-request/65038/), [https://github.com/nodejs/node/pull/56833/](https://ci.nodejs.org/job/node-test-pull-request/65039/), [https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/65070/), [https://github.com/nodejs/node/pull/56765/](https://ci.nodejs.org/job/node-test-pull-request/65091/)) |
| Appeared | [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/63126/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/48954/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48954/console), [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/63076/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/63075/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65021/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/63126/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>Error: list index out of range</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/65000/), [https://github.com/nodejs/node/pull/56912/](https://ci.nodejs.org/job/node-test-pull-request/65011/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console), [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console), [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console), [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65000/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65011/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2022-x86/32509/console">Example</a></summary>

```
Error: list index out of range

> if errorlevel 1 exit /b 

> if errorlevel 1 exit /b
```
</details>

-------

| Reason | <code>Failed to trigger sub builds</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56117/](https://ci.nodejs.org/job/node-test-pull-request/65018/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/65054/)) |
| Appeared | [undefined](https://ci.nodejs.org/job/node-test-commit/77694/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65018/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65054/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit/77694/console">Example</a></summary>

```
Failed to trigger sub builds
```
</details>

-------

| Reason | <code>error: remote GitHub already exists.</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56832/](https://ci.nodejs.org/job/node-test-pull-request/65027/), [https://github.com/nodejs/node/pull/56942/](https://ci.nodejs.org/job/node-test-pull-request/65046/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60336/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65027/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65046/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60336/console">Example</a></summary>

```
error: remote GitHub already exists.

> git fetch --prune --no-tags GitHub 

> git fetch --prune --no-tags https://github.com/nodejs/build.git +refs/heads/main:refs/remotes/jenkins_tmp
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56842/](https://ci.nodejs.org/job/node-test-pull-request/65008/), [https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65100/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48982/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48894/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65008/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65100/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48982/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

