Failures in [node-test-pull-request/65281](https://ci.nodejs.org/job/node-test-pull-request/65281/) to [node-test-pull-request/65376](https://ci.nodejs.org/job/node-test-pull-request/65376/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-23.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-23 00:11 | 1       | 7       | 22       | 18      | 52      | 8.64%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65281/), [https://github.com/nodejs/node/pull/57126/](https://ci.nodejs.org/job/node-test-pull-request/65301/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65316/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32764/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65281/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65316/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/32764/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/57110/](https://ci.nodejs.org/job/node-test-pull-request/65283/), [https://github.com/nodejs/node/pull/57120/](https://ci.nodejs.org/job/node-test-pull-request/65296/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65311/), [https://github.com/nodejs/node/pull/57132/](https://ci.nodejs.org/job/node-test-pull-request/65312/), [https://github.com/nodejs/node/pull/57141/](https://ci.nodejs.org/job/node-test-pull-request/65324/), [https://github.com/nodejs/node/pull/57144/](https://ci.nodejs.org/job/node-test-pull-request/65357/), [https://github.com/nodejs/node/pull/56496/](https://ci.nodejs.org/job/node-test-pull-request/65360/), [https://github.com/nodejs/node/pull/57168/](https://ci.nodejs.org/job/node-test-pull-request/65364/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60588/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60584/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60581/console), [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60539/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65283/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65364/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60588/console">Example</a></summary>

```
error C1060: compiler is out of heap space [C:\workspace\node-compile-windows\node\tools\v8_gypfiles\v8_initializers.vcxproj]
     Creating library ..\..\out\Release\mksnapshot_host.lib and object ..\..\out\Release\mksnapshot_host.exp
  typed-array-of-tq-csa.cc
  typed-array-slice-tq-csa.cc
  typed-array-set-tq-csa.cc
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57082/](https://ci.nodejs.org/job/node-test-pull-request/65293/), [https://github.com/nodejs/node/pull/56628/](https://ci.nodejs.org/job/node-test-pull-request/65315/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65318/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49178/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/59027/console), [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49169/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49156/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65293/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65318/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49178/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>Error: EBUSY: resource busy or locked, rmdir '\\?\c:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.638'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57122/](https://ci.nodejs.org/job/node-test-pull-request/65313/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65316/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2019/32761/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/32760/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65313/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65316/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2019/32761/console">Example</a></summary>

```
Error: EBUSY: resource busy or locked, rmdir '\\?\c:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.638'
        at rmdirSync (node:fs:1222:10)
        at _rmdirSync (node:internal/fs/rimraf:235:5)
        at rimrafSync (node:internal/fs/rimraf:193:7)
        at Object.rmSync (node:fs:1271:10)
        at rmSync (c:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:9:6)
```
</details>

-------


### CCTest Failure


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/57115/](https://ci.nodejs.org/job/node-test-pull-request/65288/), [https://github.com/nodejs/node/pull/56932/](https://ci.nodejs.org/job/node-test-pull-request/65295/), [https://github.com/nodejs/node/pull/57122/](https://ci.nodejs.org/job/node-test-pull-request/65298/), [https://github.com/nodejs/node/pull/57132/](https://ci.nodejs.org/job/node-test-pull-request/65312/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65338/), [https://github.com/nodejs/node/pull/57149/](https://ci.nodejs.org/job/node-test-pull-request/65354/), [https://github.com/nodejs/node/pull/57058/](https://ci.nodejs.org/job/node-test-pull-request/65359/), [https://github.com/nodejs/node/pull/57144/](https://ci.nodejs.org/job/node-test-pull-request/65362/), [https://github.com/nodejs/node/pull/57170/](https://ci.nodejs.org/job/node-test-pull-request/65365/), [https://github.com/nodejs/node/pull/56496/](https://ci.nodejs.org/job/node-test-pull-request/65376/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65288/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65376/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/57115/](https://ci.nodejs.org/job/node-test-pull-request/65288/), [https://github.com/nodejs/node/pull/57096/](https://ci.nodejs.org/job/node-test-pull-request/65290/), [https://github.com/nodejs/node/pull/57126/](https://ci.nodejs.org/job/node-test-pull-request/65301/), [https://github.com/nodejs/node/pull/57144/](https://ci.nodejs.org/job/node-test-pull-request/65336/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65338/), [https://github.com/nodejs/node/pull/57148/](https://ci.nodejs.org/job/node-test-pull-request/65346/), [https://github.com/nodejs/node/pull/57170/](https://ci.nodejs.org/job/node-test-pull-request/65365/), [https://github.com/nodejs/node/pull/56496/](https://ci.nodejs.org/job/node-test-pull-request/65376/)) |
| Appeared | [vm-xckgw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63853/console), [vm-tsxs9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63850/console), [vm-4hkjh](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63841/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57364/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49199/console), [vm-nb8mt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63814/console), [vm-pjh5g](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63811/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/49153/console), [vm-4m2fj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63772/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65288/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65376/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63853/console">Example</a></summary>

```
not ok 4014 parallel/test-file-write-stream4
  ---
  duration_ms: 360048.25500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/57132/](https://ci.nodejs.org/job/node-test-pull-request/65312/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65316/), [https://github.com/nodejs/node/pull/57149/](https://ci.nodejs.org/job/node-test-pull-request/65354/), [https://github.com/nodejs/node/pull/57144/](https://ci.nodejs.org/job/node-test-pull-request/65357/), [https://github.com/nodejs/node/pull/57058/](https://ci.nodejs.org/job/node-test-pull-request/65359/), [https://github.com/nodejs/node/pull/56496/](https://ci.nodejs.org/job/node-test-pull-request/65375/)) |
| Appeared | [vm-gm8h6](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63852/console), [vm-2wql4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63850/console), [vm-bhhlx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63835/console), [vm-ftl9c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63832/console), [vm-xltw7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63794/console), [vm-5zg4q](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63787/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65312/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65375/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63852/console">Example</a></summary>

```
not ok 2589 parallel/test-runner-run-watch
  ---
  duration_ms: 22984.80800
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched noop function calls. Expected exactly 1, actual 2.
        at Module.mustCall (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/index.js:393:10)
        at TestContext.<anonymous> (file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:308:37)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:989:25)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:680:7)
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/57071/](https://ci.nodejs.org/job/node-test-pull-request/65284/), [https://github.com/nodejs/node/pull/57101/](https://ci.nodejs.org/job/node-test-pull-request/65287/), [https://github.com/nodejs/node/pull/57126/](https://ci.nodejs.org/job/node-test-pull-request/65301/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65318/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2019/32765/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/16042/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65284/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65318/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2019/32765/console">Example</a></summary>

```
not ok 105 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 371.00600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:377
          throw err;
          ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
      Comparison {
    +   name: 'RangeError'
    -   code: 'ERR_STRING_TOO_LONG',
    -   name: 'Error'
      }
        at Object.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-rangeerror.js:21:8)
        at Module._compile (node:internal/modules/cjs/loader:1578:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1662:10)
        at Module.load (node:internal/modules/cjs/loader:1290:32)
        at Module._load (node:internal/modules/cjs/loader:1106:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: true,
      code: 'ERR_ASSE...
```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56932/](https://ci.nodejs.org/job/node-test-pull-request/65295/), [https://github.com/nodejs/node/pull/57122/](https://ci.nodejs.org/job/node-test-pull-request/65313/), [https://github.com/nodejs/node/pull/56147/](https://ci.nodejs.org/job/node-test-pull-request/65361/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48290/console), [vm-6hglr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63777/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65295/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65361/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48290/console">Example</a></summary>

```
not ok 2548 parallel/test-runner-output
  ---
  duration_ms: 3626.76900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/timeout_in_before_each_should_not_affect_further_tests.js'
    Location: test/parallel/test-runner-output.mjs:312:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'gonna timeout\n' +
        'TAP version 13\n' +
        'not gonna timeout\n' +
        'before each test second 2\n' +
        'after each test first 0\n' +
    ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56932/](https://ci.nodejs.org/job/node-test-pull-request/65295/), [https://github.com/nodejs/node/pull/57149/](https://ci.nodejs.org/job/node-test-pull-request/65354/), [https://github.com/nodejs/node/pull/57144/](https://ci.nodejs.org/job/node-test-pull-request/65362/)) |
| Appeared | [vm-bhhlx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63838/console), [vm-ftl9c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63826/console), [vm-6hglr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63777/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65295/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65362/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63838/console">Example</a></summary>

```
not ok 4366 sequential/test-perf-hooks
  ---
  duration_ms: 603.48900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (269.97509765625) - process.uptime() * 1000 (170.529427) = 99.44567065625 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1734:14)
        at Object..js (node:internal/modules/cjs/loader:1899:10)
        at Module.load (node:internal/modules/cjs/loader:1469:32)
        at Function._load (node:internal/modules/cjs/loader:1286:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
        at node:internal/main/run_main_module:3...
```
</details>

-------

| Reason | <code>parallel/test-http-get-pipeline-problem</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57122/](https://ci.nodejs.org/job/node-test-pull-request/65313/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65316/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/32761/console), [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/32760/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65313/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65316/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2016-COMPILED_BY-vs2019-x86/32761/console">Example</a></summary>

```
not ok 352 parallel/test-http-get-pipeline-problem
  ---
  duration_ms: 361.00300
  severity: fail
  exitcode: 3221226505
  stack: |-
    image.length = 45658
    recv 0
    done 0
    recv 1
    done 1
    recv 2
    done 2
    recv 3
    done 3
    recv 4
    done 4
    recv 5
    done 5
    recv 6
    done 6
    recv 7
    done 7
    recv 8
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-server-connection-list-when-close</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57122/](https://ci.nodejs.org/job/node-test-pull-request/65298/), [https://github.com/nodejs/node/pull/57016/](https://ci.nodejs.org/job/node-test-pull-request/65316/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/32761/console), [vm-kjdb9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63780/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65298/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65316/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2019/32761/console">Example</a></summary>

```
not ok 902 parallel/test-http-server-connection-list-when-close
  ---
  duration_ms: 120177.22600
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-server-headers-timeout-keepalive</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57122/](https://ci.nodejs.org/job/node-test-pull-request/65305/), [https://github.com/nodejs/node/pull/56467/](https://ci.nodejs.org/job/node-test-pull-request/65345/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49201/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48234/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65305/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65345/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/49201/console">Example</a></summary>

```
not ok 1454 parallel/test-http-server-headers-timeout-keepalive
  ---
  duration_ms: 15853.95900
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:128
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'HTTP/1.1 200 OK\r\n' +
    +   'Content-Type: text/plain\r\n' +
    +   'Date: Thu, 20 Feb 2025 16:37:27 GMT\r\n' +
    +   'Connection: close\r\n' +
    +   'Transfer-Encoding: chunked\r\n' +
    +   '\r\n' +
    +   '0\r\n' +
    +   '\r\n'
    - 'HTTP/1.1 408 Request Timeout\r\nConnection: close\r\n\r\n'
    
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-http-server-headers-timeout-keepalive.js:82:12)
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:435:15)
        at Socket.emit (node:events:519:35)
        at endReadableNT (node:internal/streams/readable:1701:12...
```
</details>

-------

| Reason | <code>parallel/test-pipe-file-to-http</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57115/](https://ci.nodejs.org/job/node-test-pull-request/65288/), [https://github.com/nodejs/node/pull/57144/](https://ci.nodejs.org/job/node-test-pull-request/65357/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/16088/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/16033/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65288/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65357/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/16088/console">Example</a></summary>

```
not ok 4056 parallel/test-pipe-file-to-http
  ---
  duration_ms: 360042.21300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-unpipe-resume</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57096/](https://ci.nodejs.org/job/node-test-pull-request/65282/), [https://github.com/nodejs/node/pull/57148/](https://ci.nodejs.org/job/node-test-pull-request/65346/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57364/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/49143/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65282/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65346/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57364/console">Example</a></summary>

```
not ok 4199 parallel/test-stream-readable-unpipe-resume
  ---
  duration_ms: 360026.01200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57126/](https://ci.nodejs.org/job/node-test-pull-request/65301/), [https://github.com/nodejs/node/pull/57096/](https://ci.nodejs.org/job/node-test-pull-request/65303/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49162/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/56074/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65301/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65303/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49162/console">Example</a></summary>

```
not ok 4298 wpt/test-compression
  ---
  duration_ms: 1440026.58700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to throw
    [PASS] CompressionStream constructor should throw on invalid format...
```
</details>

-------

| Reason | <code>wpt/test-timers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57126/](https://ci.nodejs.org/job/node-test-pull-request/65301/), [https://github.com/nodejs/node/pull/56764/](https://ci.nodejs.org/job/node-test-pull-request/65307/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48236/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2019/32748/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65301/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65307/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48236/console">Example</a></summary>

```
not ok 4421 wpt/test-timers
  ---
  duration_ms: 1090.93600
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] negative-settimeout.any.js: unreliable in Node.js; Refs: https://github.com/nodejs/node/issues/37672
    [PASS] Clear timeout with clearInterval
    [PASS] Clear interval with clearTimeout
    [PASS] Calling setInterval with no interval should be the same as if called with 0 interval
    [PASS] Calling setInterval with undefined interval should be the same as if called with 0 interval
    [PASS] negative-setinterval
    [UNEXPECTED_FAILURE][UNCAUGHT] evaluation in WPTRunner.runJsTests()
    assert_unreached: Reached unreachable code
    {
      message: 'assert_unreached: Reached unreachable code',
      stack: '    at listOnTimeout (node:internal/timers:614:17)\n' +
        '    at process.processTimers (node:internal/timers:549:7)'
    }
    Command: /home/iojs/build/workspace/node-test-commit-linuxone/out/Release/node --test-reporter=./test/common/test-error-reporter.js,--test-reporter-desti...
```
</details>

-------

