Failures in [node-test-pull-request/68543](https://ci.nodejs.org/job/node-test-pull-request/68543/) to [node-test-pull-request/68638](https://ci.nodejs.org/job/node-test-pull-request/68638/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-08-15.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-08-15 00:12 | 2       | 0       | 34       | 6       | 58      | 0.00%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59436/](https://ci.nodejs.org/job/node-test-pull-request/68546/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68593/), [https://github.com/nodejs/node/pull/59138/](https://ci.nodejs.org/job/node-test-pull-request/68615/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68624/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/36228/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68546/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68624/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/36228/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59440/](https://ci.nodejs.org/job/node-test-pull-request/68548/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68565/), [https://github.com/nodejs/node/pull/59473/](https://ci.nodejs.org/job/node-test-pull-request/68636/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022_clang-arm64/63117/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/52221/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68548/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68636/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022_clang-arm64/63117/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68569/), [https://github.com/nodejs/node/pull/57866/](https://ci.nodejs.org/job/node-test-pull-request/68586/), [https://github.com/nodejs/node/pull/50353/](https://ci.nodejs.org/job/node-test-pull-request/68606/), [https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68611/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52264/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52260/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52245/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59856/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68569/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68611/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52264/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59428/](https://ci.nodejs.org/job/node-test-pull-request/68582/), [https://github.com/nodejs/node/pull/59472/](https://ci.nodejs.org/job/node-test-pull-request/68632/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59898/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/52241/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68582/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68632/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59898/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: no workspace for node-test-commit-arm/nodes=rhel8-arm64 #59898
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>FATAL: Channel "hudson.remoting.Channel@1907e711:JNLP4-connect connection from ... Remote call on JNLP4-connect connection from e.1a.7534.ip4.static.sl-reverse.com/52.117.26.14:53500 failed. The channel is closing down or has closed down</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59449/](https://ci.nodejs.org/job/node-test-pull-request/68583/), [https://github.com/nodejs/node/pull/59453/](https://ci.nodejs.org/job/node-test-pull-request/68584/)) |
| Appeared | [test-ibm-ubuntu2204-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/61970/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68583/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68584/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/61970/console">Example</a></summary>

```
FATAL: Channel "hudson.remoting.Channel@1907e711:JNLP4-connect connection from e.1a.7534.ip4.static.sl-reverse.com/52.117.26.14:53500": Remote call on JNLP4-connect connection from e.1a.7534.ip4.static.sl-reverse.com/52.117.26.14:53500 failed. The channel is closing down or has closed down
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:155)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:181)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:804)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
```
</details>

-------


### JSTest Failure

| Reason | <code>wasi/test-wasi</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 15 ([https://github.com/nodejs/node/pull/59436/](https://ci.nodejs.org/job/node-test-pull-request/68546/), [https://github.com/nodejs/node/pull/59404/](https://ci.nodejs.org/job/node-test-pull-request/68555/), [https://github.com/nodejs/node/pull/59414/](https://ci.nodejs.org/job/node-test-pull-request/68559/), [https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68561/), [https://github.com/nodejs/node/pull/59453/](https://ci.nodejs.org/job/node-test-pull-request/68584/), [https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68588/), [https://github.com/nodejs/node/pull/59448/](https://ci.nodejs.org/job/node-test-pull-request/68589/), [https://github.com/nodejs/node/pull/58748/](https://ci.nodejs.org/job/node-test-pull-request/68591/), [https://github.com/nodejs/node/pull/59449/](https://ci.nodejs.org/job/node-test-pull-request/68601/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68617/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68622/), [https://github.com/nodejs/node/pull/58169/](https://ci.nodejs.org/job/node-test-pull-request/68630/), [https://github.com/nodejs/node/pull/59471/](https://ci.nodejs.org/job/node-test-pull-request/68631/), [https://github.com/nodejs/node/pull/59472/](https://ci.nodejs.org/job/node-test-pull-request/68635/), [https://github.com/nodejs/node/pull/59475/](https://ci.nodejs.org/job/node-test-pull-request/68638/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59903/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59903/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19887/console), [test-equinix-ubuntu2204_container-arm64-8](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19849/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59861/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68546/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68638/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59903/console">Example</a></summary>

```
not ok 413 wasi/test-wasi
  ---
  duration_ms: 46401.35000
  severity: fail
  exitcode: 1
  stack: |-
    Testing with --turbo-fast-api-calls: clock_getres
    Testing with --no-turbo-fast-api-calls: clock_getres
    Testing with --turbo-fast-api-calls: getrusage
    Testing with --no-turbo-fast-api-calls: getrusage
    Testing with --turbo-fast-api-calls: readdir
    Testing with --no-turbo-fast-api-calls: readdir
    Testing with --turbo-fast-api-calls: cant_dotdot
    Testing with --no-turbo-fast-api-calls: cant_dotdot
    Testing with --turbo-fast-api-calls: fd_prestat_get_refresh
    Testing with --no-turbo-fast-api-calls: fd_prestat_get_refresh
    Testing with --turbo-fast-api-calls: ftruncate
    Testing with --no-turbo-fast-api-calls: ftruncate
    Testing with --turbo-fast-api-calls: getentropy
    Testing with --no-turbo-fast-api-calls: getentropy
    Testing with --turbo-fast-api-calls: gettimeofday
    Testing with --no-turbo-fast-api-calls: gettimeofday
    Testing with --turbo-fast-api-calls: m...
```
</details>

-------

| Reason | <code>parallel/test-http-keep-alive-empty-line</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59404/](https://ci.nodejs.org/job/node-test-pull-request/68555/), [https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68561/), [https://github.com/nodejs/node/pull/59363/](https://ci.nodejs.org/job/node-test-pull-request/68580/), [https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68588/), [https://github.com/nodejs/node/pull/59448/](https://ci.nodejs.org/job/node-test-pull-request/68589/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68610/), [https://github.com/nodejs/node/pull/59475/](https://ci.nodejs.org/job/node-test-pull-request/68638/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59903/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19887/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59879/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68555/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68638/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59903/console">Example</a></summary>

```
not ok 1855 parallel/test-http-keep-alive-empty-line
  ---
  duration_ms: 1635.11500
  severity: fail
  exitcode: 1
  stack: |-
    node:events:486
          throw er; // Unhandled 'error' event
          ^
    
    Error [ERR_STREAM_WRITE_AFTER_END]: write after end
        at _write (node:internal/streams/writable:487:11)
        at Writable.write (node:internal/streams/writable:508:10)
        at Timeout._onTimeout (file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-keep-alive-empty-line.mjs:32:14)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7)
    Emitted 'error' event on Socket instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_STREAM_WRITE_AFTER_END'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-mock-timers-scheduler</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59404/](https://ci.nodejs.org/job/node-test-pull-request/68555/), [https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68561/), [https://github.com/nodejs/node/pull/59453/](https://ci.nodejs.org/job/node-test-pull-request/68584/), [https://github.com/nodejs/node/pull/58748/](https://ci.nodejs.org/job/node-test-pull-request/68591/), [https://github.com/nodejs/node/pull/59449/](https://ci.nodejs.org/job/node-test-pull-request/68601/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68620/), [https://github.com/nodejs/node/pull/59475/](https://ci.nodejs.org/job/node-test-pull-request/68638/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19887/console), [test-equinix-ubuntu2204_container-arm64-8](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19849/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68555/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68638/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19887/console">Example</a></summary>

```
not ok 3121 parallel/test-runner-mock-timers-scheduler
  ---
  duration_ms: 6364.06200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should advance in time and trigger timers when calling the .tick function'
    Location: test/parallel/test-runner-mock-timers-scheduler.js:10:3
    AssertionError [ERR_ASSERTION]: time should be advanced less than the 100ms
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-runner-mock-timers-scheduler.js:21:14
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/common/index.js:437:15
        at async Test.run (node:internal/test_runner/test:1088:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1485:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:332:3) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
  ...

```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68549/), [https://github.com/nodejs/node/pull/59404/](https://ci.nodejs.org/job/node-test-pull-request/68555/), [https://github.com/nodejs/node/pull/59440/](https://ci.nodejs.org/job/node-test-pull-request/68558/), [https://github.com/nodejs/node/pull/59414/](https://ci.nodejs.org/job/node-test-pull-request/68559/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68567/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68613/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/36215/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/36163/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/52222/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58545/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2022-COMPILED_BY-vs2022_clang/36159/console), [vm-nqsts](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66225/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/52216/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/52215/console), [vm-zktul](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66222/console), [test-osuosl-rhel9-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/60295/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59829/console), [test-ibm-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/66058/console), [test-mnx-smartos22-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/61941/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68549/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68613/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/36215/console">Example</a></summary>

```
not ok 1116 sequential/test-tls-session-timeout
  ---
  duration_ms: 374.28400
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at c:\workspace\node-test-binary-windows-js-suites\node\test\sequential\test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\sequential\test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:508:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-outgoing-end-cork</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59414/](https://ci.nodejs.org/job/node-test-pull-request/68559/), [https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68561/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68597/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68610/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59879/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18390/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59836/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68559/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68610/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59879/console">Example</a></summary>

```
not ok 1890 parallel/test-http-outgoing-end-cork
  ---
  duration_ms: 2115.05700
  severity: fail
  exitcode: 1
  stack: |-
    Sending req no 1
    node:assert:177
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: () => {
        reject(new Error('Request timed out'));
      } at /home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-outgoing-end-cork.js:53
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68544/), [https://github.com/nodejs/node/pull/59436/](https://ci.nodejs.org/job/node-test-pull-request/68553/), [https://github.com/nodejs/node/pull/59404/](https://ci.nodejs.org/job/node-test-pull-request/68555/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68556/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/36125/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68544/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68556/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/36125/console">Example</a></summary>

```
not ok 685 parallel/test-runner-run
  ---
  duration_ms: 4593.00400
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: require('node:test').run
        # Subtest: should run with no tests
        ok 1 - should run with no tests
          ---
          duration_ms: 467.1812
          ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68543/), [https://github.com/nodejs/node/pull/59436/](https://ci.nodejs.org/job/node-test-pull-request/68551/), [https://github.com/nodejs/node/pull/59448/](https://ci.nodejs.org/job/node-test-pull-request/68589/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68618/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/52271/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51049/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/52246/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/52202/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68543/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68618/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/52271/console">Example</a></summary>

```
not ok 4662 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7327.61300
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:273
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-http-proxy-request-connection-refused</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59436/](https://ci.nodejs.org/job/node-test-pull-request/68553/), [https://github.com/nodejs/node/pull/59451/](https://ci.nodejs.org/job/node-test-pull-request/68578/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51016/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36145/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68553/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68578/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51016/console">Example</a></summary>

```
not ok 4061 client-proxy/test-http-proxy-request-connection-refused
  ---
  duration_ms: 513.87600
  severity: fail
  exitcode: 1
  stack: |-
    [STDOUT] Status Code: 200
    Headers: {
      'content-length': '41',
      'content-type': 'application/wasm',
      date: 'Tue, 12 Aug 2025 10:28:56 GMT',
      connection: 'keep-alive',
      'keep-alive': 'timeout=5'
    }
     asm
    [CLOSE] 0 null
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /Error.*connect ECONNREFUSED/. Input:
    
    ''
    
        at file:///home/iojs/build/workspace/node-test-commit-linuxone/test/client-proxy/test-http-proxy-request-connection-refused.mjs:33:8
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: '',
      expected: /Error.*connect ECONNREFUSED/,
      operator: 'match',
      diff: 'sim...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-connection-refused</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68545/), [https://github.com/nodejs/node/pull/59436/](https://ci.nodejs.org/job/node-test-pull-request/68553/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36145/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19811/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68545/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68553/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36145/console">Example</a></summary>

```
not ok 87 client-proxy/test-https-proxy-request-connection-refused
  ---
  duration_ms: 5822.00500
  severity: fail
  exitcode: 1
  stack: |-
    [CLOSE] 0 null
    [STDERR] Request timed out
    
    [STDERR] Request Error Error [ERR_PROXY_TUNNEL]: Connection to establish proxy tunnel timed out after 5000ms
        at Socket.onTimeout (node:https:374:19)
        at Object.onceWrapper (node:events:622:28)
        at Socket.emit (node:events:520:35)
        at Socket._onTimeout (node:net:604:8)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      code: 'ERR_PROXY_TUNNEL',
      proxyTunnelTimeout: 5000
    }
    
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /Error.*connect ECONNREFUSED/. Input:
    
    'Request timed out\n' +
      'Request Error Error [ERR_PROXY_TUNNEL]: Connection to establish proxy tunnel timed ...
```
</details>

-------

| Reason | <code>parallel/test-http-server-headers-timeout-keepalive</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59414/](https://ci.nodejs.org/job/node-test-pull-request/68559/), [https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68561/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59836/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59833/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68559/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68561/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59836/console">Example</a></summary>

```
not ok 2045 parallel/test-http-server-headers-timeout-keepalive
  ---
  duration_ms: 17262.90900
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'HTTP/1.1 200 OK\r\n' +
    +   'Content-Type: text/plain\r\n' +
    +   'Date: Mon, 11 Aug 2025 12:49:13 GMT\r\n' +
    +   'Connection: close\r\n' +
    +   'Transfer-Encoding: chunked\r\n' +
    +   '\r\n' +
    +   '0\r\n' +
    +   '\r\n'
    - 'HTTP/1.1 408 Request Timeout\r\nConnection: close\r\n\r\n'
    
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-server-headers-timeout-keepalive.js:82:12)
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:437:15)
        at Socket.emit (node:events:520:35)
        at endReadableNT (node:internal/streams/readable:1701:12)
        at process.process...
```
</details>

-------

| Reason | <code>parallel/test-repl-history-navigation</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59342/](https://ci.nodejs.org/job/node-test-pull-request/68561/), [https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68588/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59858/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68561/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68588/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59858/console">Example</a></summary>

```
not ok 3027 parallel/test-repl-history-navigation
  ---
  duration_ms: 5561.06700
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched runTest function calls. Expected exactly 18, actual 6.
        at Proxy.mustCall (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:395:10)
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-repl-history-navigation.js:840:28)
        at Module._compile (node:internal/modules/cjs/loader:1737:14)
        at Object..js (node:internal/modules/cjs/loader:1870:10)
        at Module.load (node:internal/modules/cjs/loader:1469:32)
        at Module._load (node:internal/modules/cjs/loader:1289:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:238:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59404/](https://ci.nodejs.org/job/node-test-pull-request/68555/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68610/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19865/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68555/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68610/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19865/console">Example</a></summary>

```
not ok 3165 parallel/test-runner-output
  ---
  duration_ms: 74026.02900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/timeout_in_before_each_should_not_affect_further_tests.js'
    Location: test/parallel/test-runner-output.mjs:355:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'gonna timeout\n' +
        'TAP version 13\n' +
        'not gonna timeout\n' +
        'before each test second 2\n' +
        'after each test first 0\n' +
    ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68556/), [https://github.com/panva/node/pull/8/](https://ci.nodejs.org/job/node-test-pull-request/68628/)) |
| Appeared | [vm-wfspl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66274/console), [vm-1iara](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66223/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68628/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66274/console">Example</a></summary>

```
not ok 2770 parallel/test-runner-run-watch
  ---
  duration_ms: 29565.43000
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 299.921876,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>parallel/test-tls-dhe</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68563/), [https://github.com/nodejs/node/pull/58935/](https://ci.nodejs.org/job/node-test-pull-request/68567/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/36151/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68563/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68567/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/36151/console">Example</a></summary>

```
not ok 846 parallel/test-tls-dhe
  ---
  duration_ms: 1004.01600
  severity: fail
  exitcode: 1
  stack: |-
    node:events:496
          throw er; // Unhandled 'error' event
          ^
    
    Error: 3C100000:error:0A00041A:SSL routines:ssl3_read_bytes:tlsv1 alert decode error:C:\workspace\node-compile-windows\node\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1605:SSL alert number 50
    
    Emitted 'error' event on TLSSocket instance at:
        at TLSSocket._emitTLSError (node:_tls_wrap:1034:10)
        at TLSWrap.onerror (node:_tls_wrap:475:11) {
      library: 'SSL routines',
      reason: 'tlsv1 alert decode error',
      code: 'ERR_SSL_TLSV1_ALERT_DECODE_ERROR'
    }
    
    Node.js v22.18.1-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-webcrypto</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59449/](https://ci.nodejs.org/job/node-test-pull-request/68583/), [https://github.com/panva/node/pull/8/](https://ci.nodejs.org/job/node-test-pull-request/68628/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58592/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68583/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68628/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58592/console">Example</a></summary>

```
not ok 4760 wpt/test-webcrypto
  ---
  duration_ms: 10768.63900
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] algorithm-discards-context.https.window.js: Not relevant in Node.js context
    [SKIPPED] historical.any.js: Not relevant in Node.js context
    [PASS] CryptoKey.algorithm getter returns cached object
    [PASS] CryptoKey.usages getter returns cached object
    [PASS] setup - define tests
    [PASS] X25519 deriveBits checks for all-zero value result with a key of order 0
    [PASS] X25519 deriveBits checks for all-zero value result with a key of order 1
    [PASS] X25519 deriveBits checks for all-zero value result with a key of order 8
    [PASS] X25519 deriveBits checks for all-zero value result with a key of order p-1 (order 2)
    [PASS] X25519 deriveBits checks for all-zero value result with a key of order p (=0, order 4)
    [PASS] X25519 deriveBits checks for all-zero value result with a key of order p+1 (=1, order 1)
    [PASS] Key derivation using a X25519 generated keys.
    [P...
```
</details>

-------

