Failures in [node-test-pull-request/65062](https://ci.nodejs.org/job/node-test-pull-request/65062/) to [node-test-pull-request/65163](https://ci.nodejs.org/job/node-test-pull-request/65163/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-13.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-13 00:09 | 7       | 15      | 12       | 18      | 48      | 20.00%     |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/), [https://github.com/nodejs/node/pull/57018/](https://ci.nodejs.org/job/node-test-pull-request/65157/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65160/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65163/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32614/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65149/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65163/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32614/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 2228979, exit value: 1</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56765/](https://ci.nodejs.org/job/node-test-pull-request/65091/), [https://github.com/nodejs/node/pull/56961/](https://ci.nodejs.org/job/node-test-pull-request/65110/)) |
| Appeared | [test-rackspace-debian11-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/63120/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65091/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65110/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian11-x64/63120/console">Example</a></summary>

```
java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/iojs/build/workspace/node"): error=0, Failed to exec spawn helper: pid: 2228979, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at Jenkins v2.492.1//hudson.Proc$LocalProc.<init>(Proc.java:252)
	at Jenkins v2.492.1//hudson.Proc$LocalProc.<init>(Proc.java:221)
	at Jenkins v2.492.1//hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/54990/](https://ci.nodejs.org/job/node-test-pull-request/65070/), [https://github.com/nodejs/node/pull/56765/](https://ci.nodejs.org/job/node-test-pull-request/65091/)) |
| Appeared | [test-digitalocean-fedora40-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/63126/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/48954/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48954/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65070/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/63126/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>sh: line 9: [: -gt: unary operator expected</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/), [https://github.com/nodejs/node/pull/57018/](https://ci.nodejs.org/job/node-test-pull-request/65157/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65160/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65163/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32616/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65149/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65163/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32616/console">Example</a></summary>

```
sh: line 9: [: -gt: unary operator expected
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65100/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49034/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48982/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65100/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65149/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49034/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-native-suites/build'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55873/](https://ci.nodejs.org/job/node-test-pull-request/65151/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win11-vs2022-COMPILED_BY-vs2022/26871/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65151/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65154/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win11-vs2022-COMPILED_BY-vs2022/26871/console">Example</a></summary>

```
fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-native-suites/build'
```
</details>

-------


### CCTest Failure


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65063/), [https://github.com/nodejs/node/pull/56970/](https://ci.nodejs.org/job/node-test-pull-request/65095/), [https://github.com/nodejs/node/pull/56988/](https://ci.nodejs.org/job/node-test-pull-request/65132/), [https://github.com/nodejs/node/pull/57001/](https://ci.nodejs.org/job/node-test-pull-request/65133/), [https://github.com/nodejs/node/pull/56967/](https://ci.nodejs.org/job/node-test-pull-request/65134/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65148/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65155/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65063/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65156/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65063/), [https://github.com/nodejs/node/pull/56970/](https://ci.nodejs.org/job/node-test-pull-request/65095/), [https://github.com/nodejs/node/pull/56988/](https://ci.nodejs.org/job/node-test-pull-request/65132/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65148/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/)) |
| Appeared | [vm-jkb9c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63666/console), [vm-k82v2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63664/console), [vm-cc77j](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63661/console), [vm-bnv4b](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63660/console), [vm-d2ffw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63641/console), [vm-9ml99](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63611/console), [vm-wsnp8](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63583/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65063/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65156/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63666/console">Example</a></summary>

```
not ok 2583 parallel/test-runner-run-watch
  ---
  duration_ms: 28198.04000
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run tests with dependency repeatedly'
    Location: test/parallel/test-runner-run-watch.mjs:200:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 371.462787\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2539/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 2 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 1.029246\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '1..2\n' +
      '# tests 2\n' +
      '# suites 0\n' +
      '# pass 1\n' +
      '# fail 1\n...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65092/), [https://github.com/nodejs/node/pull/56984/](https://ci.nodejs.org/job/node-test-pull-request/65107/), [https://github.com/nodejs/node/pull/56967/](https://ci.nodejs.org/job/node-test-pull-request/65134/), [https://github.com/nodejs/node/pull/56986/](https://ci.nodejs.org/job/node-test-pull-request/65139/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57223/console), [vm-mc524](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63643/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/57177/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57165/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65092/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65154/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57223/console">Example</a></summary>

```
not ok 4040 parallel/test-file-write-stream4
  ---
  duration_ms: 360054.51600
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56978/](https://ci.nodejs.org/job/node-test-pull-request/65090/), [https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65093/), [https://github.com/nodejs/node/pull/55051/](https://ci.nodejs.org/job/node-test-pull-request/65102/), [https://github.com/nodejs/node/pull/56955/](https://ci.nodejs.org/job/node-test-pull-request/65126/)) |
| Appeared | [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57196/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57166/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65090/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65126/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57196/console">Example</a></summary>

```
not ok 4161 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360093.86800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-hex-string</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56968/](https://ci.nodejs.org/job/node-test-pull-request/65074/), [https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65092/), [https://github.com/nodejs/node/pull/55051/](https://ci.nodejs.org/job/node-test-pull-request/65109/), [https://github.com/nodejs/node/pull/56962/](https://ci.nodejs.org/job/node-test-pull-request/65111/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48991/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/48990/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/48974/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/48958/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65074/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65111/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48991/console">Example</a></summary>

```
not ok 3455 parallel/test-net-write-fully-async-hex-string
  ---
  duration_ms: 120040.75200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>benchmark/test-benchmark-http2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/57001/](https://ci.nodejs.org/job/node-test-pull-request/65140/), [https://github.com/nodejs/node/pull/55873/](https://ci.nodejs.org/job/node-test-pull-request/65153/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/26870/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/26857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65140/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65154/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/26870/console">Example</a></summary>

```
not ok 184 benchmark/test-benchmark-http2
  ---
  duration_ms: 2172.80700
  severity: fail
  exitcode: 1
  stack: |-
    Error: test-double-http2 failed with 3221226505.
        at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-native-suites\node\benchmark\_http-benchmarkers.js:251:16)
        at Object.onceWrapper (node:events:632:26)
        at ChildProcess.emit (node:events:517:28)
        at maybeClose (node:internal/child_process:1098:16)
        at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    node:assert:125
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    3221226505 !== 0
    
        at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-native-suites\node\test\common\benchmark.js:28:12)
        at ChildProcess.emit (node:events:517:28)
        at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTIO...
```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54793/](https://ci.nodejs.org/job/node-test-pull-request/65124/), [https://github.com/nodejs/node/pull/55873/](https://ci.nodejs.org/job/node-test-pull-request/65131/), [https://github.com/nodejs/node/pull/57001/](https://ci.nodejs.org/job/node-test-pull-request/65133/)) |
| Appeared | [vm-gdsjr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63642/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/59180/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/59179/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65124/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65133/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63642/console">Example</a></summary>

```
not ok 3940 sequential/test-perf-hooks
  ---
  duration_ms: 693.71800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:399
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (346.18701171875) - process.uptime() * 1000 (245.34834899999998) = 100.83866271875002 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:35:3)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Module._load (node:internal/modules/cjs/loader:1019:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='...
```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/56968/](https://ci.nodejs.org/job/node-test-pull-request/65074/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65147/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48134/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49030/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65074/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65156/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48134/console">Example</a></summary>

```
not ok 4401 wpt/test-compression
  ---
  duration_ms: 3948.00900
  severity: crashed
  exitcode: -4
  stack: |-
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] the result of compressing [,Hello,Hello] with deflate should be 'HelloHello'
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to th...
```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65080/), [https://github.com/nodejs/node/pull/56765/](https://ci.nodejs.org/job/node-test-pull-request/65091/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/17177/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/48961/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65080/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65091/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/17177/console">Example</a></summary>

```
not ok 2569 parallel/test-runner-output
  ---
  duration_ms: 9191.27200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/test-runner-plan-timeout.js'
    Location: test/parallel/test-runner-output.mjs:312:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'TAP version 13\n' +
        '# Subtest: planning with wait\n' +
        '    # Subtest: planning with wait and passing\n' +
        '    ok 1 - planning with wait and passing\n' +
        '      ---\n' +
    ...

```
</details>

-------

| Reason | <code>sequential/test-vm-timeout-escape-promise-module-2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56655/](https://ci.nodejs.org/job/node-test-pull-request/65080/), [https://github.com/nodejs/node/pull/56966/](https://ci.nodejs.org/job/node-test-pull-request/65093/)) |
| Appeared | [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48081/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48069/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65080/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65093/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48081/console">Example</a></summary>

```
not ok 4386 sequential/test-vm-timeout-escape-promise-module-2
  ---
  duration_ms: 195.89700
  severity: fail
  exitcode: 1
  stack: |-
    (node:1941625) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    /home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-vm-timeout-escape-promise-module-2.js:22
          throw new Error(
                ^
    
    Error: escaped timeout at 100 milliseconds!
        at loop (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-vm-timeout-escape-promise-module-2.js:22:13)
        at vm:module(0):1:30
        at SourceTextModule.evaluate (node:internal/vm/module:227:23)
        at assert.rejects.code (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-vm-timeout-escape-promise-module-2.js:38:16)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    
    Node....
```
</details>

-------

