Failures in [node-test-pull-request/68241](https://ci.nodejs.org/job/node-test-pull-request/68241/) to [node-test-pull-request/68338](https://ci.nodejs.org/job/node-test-pull-request/68338/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-08-01.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-08-01 00:14 | 1       | 0       | 27       | 7       | 65      | 0.00%      |


### JSTest Failure

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 15 ([https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68249/), [https://github.com/nodejs/node/pull/59117/](https://ci.nodejs.org/job/node-test-pull-request/68278/), [https://github.com/nodejs/node/pull/59060/](https://ci.nodejs.org/job/node-test-pull-request/68281/), [https://github.com/nodejs/node/pull/59254/](https://ci.nodejs.org/job/node-test-pull-request/68288/), [https://github.com/nodejs/node/pull/59097/](https://ci.nodejs.org/job/node-test-pull-request/68292/), [https://github.com/nodejs/node/pull/59213/](https://ci.nodejs.org/job/node-test-pull-request/68303/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68307/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68315/), [https://github.com/nodejs/node/pull/59284/](https://ci.nodejs.org/job/node-test-pull-request/68322/), [https://github.com/nodejs/node/pull/59240/](https://ci.nodejs.org/job/node-test-pull-request/68327/), [https://github.com/nodejs/node/pull/59291/](https://ci.nodejs.org/job/node-test-pull-request/68330/), [https://github.com/nodejs/node/pull/59017/](https://ci.nodejs.org/job/node-test-pull-request/68332/), [https://github.com/nodejs/node/pull/59276/](https://ci.nodejs.org/job/node-test-pull-request/68333/), [https://github.com/nodejs/node/pull/54857/](https://ci.nodejs.org/job/node-test-pull-request/68334/), [https://github.com/nodejs/node/pull/59261/](https://ci.nodejs.org/job/node-test-pull-request/68337/)) |
| Appeared | [vm-1apdz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66056/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/65889/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/52018/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/35890/console), [test-digitalocean-alpine320_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65888/console), [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/65885/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/35888/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65883/console), [test-mnx-smartos22-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/61772/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/35885/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/52011/console), [test-equinix-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19636/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/35879/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35879/console), [test-ibm-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/65868/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51993/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/60110/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59621/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/43312/console), [test-mnx-smartos22-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/61746/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51982/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51979/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50766/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022/35802/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68249/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68337/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66056/console">Example</a></summary>

```
not ok 4605 sequential/test-tls-session-timeout
  ---
  duration_ms: 69.14800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-arm64/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-arm64/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:508:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wasi/test-wasi</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/59249/](https://ci.nodejs.org/job/node-test-pull-request/68252/), [https://github.com/nodejs/node/pull/59104/](https://ci.nodejs.org/job/node-test-pull-request/68254/), [https://github.com/nodejs/node/pull/59255/](https://ci.nodejs.org/job/node-test-pull-request/68260/), [https://github.com/panva/node/pull/5/](https://ci.nodejs.org/job/node-test-pull-request/68267/), [https://github.com/nodejs/node/pull/59117/](https://ci.nodejs.org/job/node-test-pull-request/68269/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68297/), [https://github.com/nodejs/node/pull/59270/](https://ci.nodejs.org/job/node-test-pull-request/68304/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68309/), [https://github.com/nodejs/node/pull/59243/](https://ci.nodejs.org/job/node-test-pull-request/68320/), [https://github.com/nodejs/node/pull/59017/](https://ci.nodejs.org/job/node-test-pull-request/68332/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19643/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59637/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59621/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/35816/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18157/console), [test-equinix-ubuntu2204_container-arm64-8](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19589/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68252/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68332/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19643/console">Example</a></summary>

```
not ok 358 wasi/test-wasi
  ---
  duration_ms: 38566.83200
  severity: fail
  exitcode: 1
  stack: |-
    Testing with --turbo-fast-api-calls: clock_getres
    Testing with --no-turbo-fast-api-calls: clock_getres
    Testing with --turbo-fast-api-calls: getrusage
    Testing with --no-turbo-fast-api-calls: getrusage
    Testing with --turbo-fast-api-calls: readdir
    Testing with --no-turbo-fast-api-calls: readdir
    Testing with --turbo-fast-api-calls: cant_dotdot
    Testing with --no-turbo-fast-api-calls: cant_dotdot
    Testing with --turbo-fast-api-calls: fd_prestat_get_refresh
    Testing with --no-turbo-fast-api-calls: fd_prestat_get_refresh
    Testing with --turbo-fast-api-calls: ftruncate
    Testing with --no-turbo-fast-api-calls: ftruncate
    Testing with --turbo-fast-api-calls: getentropy
    Testing with --no-turbo-fast-api-calls: getentropy
    Testing with --turbo-fast-api-calls: gettimeofday
    Testing with --no-turbo-fast-api-calls: gettimeofday
    Testing with --turbo-fast-api-calls: m...
```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59117/](https://ci.nodejs.org/job/node-test-pull-request/68241/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68246/), [https://github.com/nodejs/node/pull/59156/](https://ci.nodejs.org/job/node-test-pull-request/68284/), [https://github.com/nodejs/node/pull/52329/](https://ci.nodejs.org/job/node-test-pull-request/68296/), [https://github.com/nodejs/node/pull/59240/](https://ci.nodejs.org/job/node-test-pull-request/68327/), [https://github.com/nodejs/node/pull/59276/](https://ci.nodejs.org/job/node-test-pull-request/68333/), [https://github.com/nodejs/node/pull/59261/](https://ci.nodejs.org/job/node-test-pull-request/68338/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50812/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/52017/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51975/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51967/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51936/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68241/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68338/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50812/console">Example</a></summary>

```
not ok 4597 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 14719.01400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:272
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-keep-alive-empty-line</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68248/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68251/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68258/), [https://github.com/panva/node/pull/5/](https://ci.nodejs.org/job/node-test-pull-request/68267/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68297/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68310/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18190/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59621/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59615/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19592/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19588/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68310/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18190/console">Example</a></summary>

```
not ok 1720 parallel/test-http-keep-alive-empty-line
  ---
  duration_ms: 4390.03100
  severity: fail
  exitcode: 1
  stack: |-
    node:events:496
          throw er; // Unhandled 'error' event
          ^
    
    Error [ERR_STREAM_WRITE_AFTER_END]: write after end
        at _write (node:internal/streams/writable:489:11)
        at Writable.write (node:internal/streams/writable:510:10)
        at Timeout._onTimeout (file:///home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-keep-alive-empty-line.mjs:32:14)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7)
    Emitted 'error' event on Socket instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_STREAM_WRITE_AFTER_END'
    }
    
    Node.js v22.17.2-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-mock-timers-scheduler</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/68246/), [https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68248/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68249/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68251/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68291/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59615/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19588/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19586/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68246/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68311/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console">Example</a></summary>

```
not ok 2944 parallel/test-runner-mock-timers-scheduler
  ---
  duration_ms: 7644.23900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should advance in time and trigger timers when calling the .tick function'
    Location: test/parallel/test-runner-mock-timers-scheduler.js:10:3
    AssertionError [ERR_ASSERTION]: time should be advanced less than the 100ms
        at /home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-runner-mock-timers-scheduler.js:21:14
        at /home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:437:15
        at async Test.run (node:internal/test_runner/test:1054:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1442:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:296:3) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    (node:4163516) ExperimentalWarning: The Mo...
```
</details>

-------

| Reason | <code>parallel/test-http-outgoing-end-cork</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68248/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68258/), [https://github.com/nodejs/node/pull/59255/](https://ci.nodejs.org/job/node-test-pull-request/68260/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68291/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18191/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59615/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19592/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59582/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68311/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18191/console">Example</a></summary>

```
not ok 1746 parallel/test-http-outgoing-end-cork
  ---
  duration_ms: 6098.43100
  severity: fail
  exitcode: 1
  stack: |-
    Sending req no 1
    node:assert:142
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: () => {
        reject(new Error('Request timed out'));
      } at /home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-outgoing-end-cork.js:53
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail'
    }
    
    Node.js v22.17.2-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-cli-eval</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68297/), [https://github.com/nodejs/node/pull/59060/](https://ci.nodejs.org/job/node-test-pull-request/68299/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68315/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35852/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68297/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68315/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35852/console">Example</a></summary>

```
not ok 134 parallel/test-cli-eval
  ---
  duration_ms: 915.04300
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:90
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== ''
    
        at Object.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-cli-eval.js:165:10)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: '',
      operator: 'strictEqual'
    }
    
    Node.js v20.19.5-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-cli-node-print-help</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68297/), [https://github.com/nodejs/node/pull/59060/](https://ci.nodejs.org/job/node-test-pull-request/68299/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68315/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35852/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68297/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68315/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2019/35852/console">Example</a></summary>

```
not ok 133 parallel/test-cli-node-print-help
  ---
  duration_ms: 868.03900
  severity: fail
  exitcode: 1
  stack: |-
    
    #
    # Fatal process OOM in Re-embedded builtins: set permissions
    #
    
    node:internal/process/promises:391
        triggerUncaughtException(err, true /* fromPromise */);
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    2147483651 !== 0
    
        at C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-cli-node-print-help.js:65:10
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 2147483651,
      expected: 0,
      operator: 'strictEqual'
    }
    
    Node.js v20.19.5-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-server-headers-timeout-keepalive</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68248/), [https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68251/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68258/), [https://github.com/nodejs/node/pull/59255/](https://ci.nodejs.org/job/node-test-pull-request/68260/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18157/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19592/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19588/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59582/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68260/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18157/console">Example</a></summary>

```
not ok 1850 parallel/test-http-server-headers-timeout-keepalive
  ---
  duration_ms: 26982.93600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:95
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    
    + 'HTTP/1.1 200 OK\r\n' +
    +   'Content-Type: text/plain\r\n' +
    +   'Date: Mon, 28 Jul 2025 07:10:17 GMT\r\n' +
    +   'Connection: close\r\n' +
    +   'Transfer-Encoding: chunked\r\n' +
    +   '\r\n' +
    +   '0\r\n' +
    +   '\r\n'
    - 'HTTP/1.1 408 Request Timeout\r\nConnection: close\r\n\r\n'
    
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-server-headers-timeout-keepalive.js:82:12)
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:437:15)
        at Socket.emit (node:events:530:35)
        at endReadableNT (node:internal/streams/readable:1698:12)
        at process.pr...
```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59249/](https://ci.nodejs.org/job/node-test-pull-request/68252/), [https://github.com/nodejs/node/pull/59156/](https://ci.nodejs.org/job/node-test-pull-request/68276/), [https://github.com/nodejs/node/pull/59254/](https://ci.nodejs.org/job/node-test-pull-request/68280/), [https://github.com/nodejs/node/pull/59278/](https://ci.nodejs.org/job/node-test-pull-request/68308/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60115/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50766/console), [test-osuosl-rhel9-ppc64_le-1](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/60076/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68252/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68308/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60115/console">Example</a></summary>

```
not ok 4226 parallel/test-stream-readable-to-web
  ---
  duration_ms: 120028.17700
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-http-proxy-request-connection-refused</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59216/](https://ci.nodejs.org/job/node-test-pull-request/68262/), [https://github.com/nodejs/node/pull/59156/](https://ci.nodejs.org/job/node-test-pull-request/68283/), [https://github.com/nodejs/node/pull/52329/](https://ci.nodejs.org/job/node-test-pull-request/68296/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51990/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51974/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50752/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68262/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68296/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51990/console">Example</a></summary>

```
not ok 286 client-proxy/test-http-proxy-request-connection-refused
  ---
  duration_ms: 427.19700
  severity: fail
  exitcode: 1
  stack: |-
    [STDOUT] Status Code: 200
    
    [STDOUT] Headers: {
      'content-type': 'application/wasm',
      date: 'Tue, 29 Jul 2025 13:21:44 GMT',
      connection: 'keep-alive',
      'keep-alive': 'timeout=5',
      'content-length': '36'
    }
    
    [STDOUT]  asm   `   	crash  
      
    
    [CLOSE] 0 null
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /Error.*connect ECONNREFUSED/. Input:
    
    ''
    
        at file:///home/iojs/build/workspace/node-test-commit-linux-containered/test/client-proxy/test-http-proxy-request-connection-refused.mjs:33:8
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: '',
      expecte...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-connection-refused</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59255/](https://ci.nodejs.org/job/node-test-pull-request/68260/), [https://github.com/nodejs/node/pull/59156/](https://ci.nodejs.org/job/node-test-pull-request/68283/), [https://github.com/nodejs/node/pull/59261/](https://ci.nodejs.org/job/node-test-pull-request/68338/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/35897/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51974/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/35815/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68260/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68338/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/35897/console">Example</a></summary>

```
not ok 26 client-proxy/test-https-proxy-request-connection-refused
  ---
  duration_ms: 767.03600
  severity: fail
  exitcode: 1
  stack: |-
    [CLOSE] 0 null
    [STDERR] Request Error Error [ERR_PROXY_TUNNEL]: Failed to establish tunnel to localhost:52923 via http://localhost:52933: CONNECT localhost:52923 HTTP/1.1
        at onProxyData (node:https:252:19)
        at Socket.read (node:https:216:11)
        at Socket.emit (node:events:508:28)
        at emitReadable_ (node:internal/streams/readable:832:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
      code: 'ERR_PROXY_TUNNEL',
      statusCode: NaN
    }
    
    [STDERR] Request Error Error [ERR_PROXY_TUNNEL]: Failed to establish tunnel to localhost:52923 via http://localhost:52933: CONNECT localhost:52923 HTTP/1.1
        at onProxyData (node:https:252:19)
        at Socket.read (node:https:216:11)
        at Socket.emit (node:events:508:28)
        at emitReadable_ (node:internal/streams/readable:832:12)
...
```
</details>

-------

| Reason | <code>parallel/test-http2-forget-closed-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68249/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68291/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59615/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19586/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68249/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68311/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console">Example</a></summary>

```
not ok 2855 parallel/test-http2-forget-closed-streams
  ---
  duration_ms: 360831.17500
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59244/](https://ci.nodejs.org/job/node-test-pull-request/68272/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68291/)) |
| Appeared | [vm-02acp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66021/console), [vm-h25n7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66011/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68272/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68291/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66021/console">Example</a></summary>

```
not ok 4182 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 548.53700
  severity: fail
  exitcode: 1
  stack: |-
    #6 eneded response for: 'https://local\nhost:55402/newline-in-host'
    #5 eneded response for: 'https://local\rhost:55402/carriage-return-in-host'
    #4 eneded response for: 'https://local\r\nhost:55402/crlf-in-host'
    #3 eneded response for: 'https://localhost:5\n5402/newline-in-port'
    #2 eneded response for: 'https://localhost:5\r5402/carriage-return-in-port'
    #1 eneded response for: 'https://localhost:5\r\n5402/crlf-in-port'
    node:assert:95
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Set(8) {
    - Set(6) {
        {
    +     error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    +         at _write (node:internal/streams/writable:487:11)
    +         at Writable.write (node:internal/streams/writable:508:10)
    +       ...
```
</details>

-------

| Reason | <code>parallel/test-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59255/](https://ci.nodejs.org/job/node-test-pull-request/68260/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18191/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68260/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68311/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18191/console">Example</a></summary>

```
not ok 870 parallel/test-async-context-frame
  ---
  duration_ms: 366878.10100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-exceptions</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68315/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/35869/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68311/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68315/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/35869/console">Example</a></summary>

```
not ok 390 parallel/test-debugger-exceptions
  ---
  duration_ms: 15783.72900
  severity: fail
  exitcode: 1
  stack: |-
    C:\workspace\node-test-binary-windows-js-suites\node\test\common\debugger.js:91
              reject(new Error([
                     ^
    
    Error: Timeout (15000) while waiting for /(?:assert|break|break on start|debugCommand|exception|other|promiseRejection|step) in/i; found: < Debugger ending on ws://127.0.0.1:62053/0e342d0c-a690-417d-9a17-ee85a4f89dd0
    < For help, see: https://nodejs.org/en/docs/inspector
    < 
    
    debug> 
    < Debugger listening on ws://127.0.0.1:62056/9d105aa6-54dd-4a05-afef-575993a0122f
    < 
    debug> 
    connecting to 127.0.0.1:62056 ...
    < For help, see: https://nodejs.org/en/docs/inspector
    < 
    debug> 
     ok
    
    debug> 
    < Debugger attached.
    < 
    debug> 
        at Timeout.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\common\debugger.js:91:18)
        at listOnTimeout (node:internal/timers:588...
```
</details>

-------

| Reason | <code>parallel/test-http-client-close-with-default-agent</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68248/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68311/)) |
| Appeared | [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59582/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68311/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18191/console">Example</a></summary>

```
not ok 1602 parallel/test-http-client-close-with-default-agent
  ---
  duration_ms: 7792.95100
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:142
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: function should not have been called at /home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-client-close-with-default-agent.js:23
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail'
    }
    
    Node.js v22.17.2-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59117/](https://ci.nodejs.org/job/node-test-pull-request/68242/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/68249/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19586/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59576/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68242/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68249/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19586/console">Example</a></summary>

```
not ok 2974 parallel/test-runner-output
  ---
  duration_ms: 128887.00100
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/timeout_in_before_each_should_not_affect_further_tests.js'
    Location: test/parallel/test-runner-output.mjs:328:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'gonna timeout\n' +
        'TAP version 13\n' +
        'not gonna timeout\n' +
        'before each test second 2\n' +
        'after each test first 0\n' +
    ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58693/](https://ci.nodejs.org/job/node-test-pull-request/68251/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68291/)) |
| Appeared | [vm-02acp](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66021/console), [vm-nt4nz](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65997/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68251/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68291/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66021/console">Example</a></summary>

```
not ok 2673 parallel/test-runner-run-watch
  ---
  duration_ms: 31780.55900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should support running tests without a file'
    Location: test/parallel/test-runner-run-watch.mjs:210:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test has ran\n' +
      'ok 1 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 1.166588\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 1025.93808\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2639/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 3 - test has ran\n' +
      '  ---\n' +
      '  durat...
```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59065/](https://ci.nodejs.org/job/node-test-pull-request/68248/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68306/)) |
| Appeared | [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65867/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59582/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68306/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65867/console">Example</a></summary>

```
not ok 4572 sequential/test-perf-hooks
  ---
  duration_ms: 266.39400
  severity: fail
  exitcode: 1
  stack: |-
    check initial nodeTiming
    {
      "name": "node",
      "entryType": "node",
      "startTime": 0,
      "duration": 116.935148,
      "nodeStart": 0.8576850891113281,
      "v8Start": 6.7474822998046875,
      "environment": 22.2186279296875,
      "loopStart": -1,
      "loopExit": -1,
      "bootstrapComplete": 37.05044364929199,
      "idleTime": 0,
      "uvMetricsInfo": {
        "loopCount": 0,
        "events": 0,
        "eventsWaiting": 0
      }
    }
    node:internal/assert/utils:272
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: now (147.478866) - timing.duration (116.935148) = 30.543718000000013 >= 10
        at checkNodeTiming (/home/iojs/build/workspace/node/test/sequential/test-perf-hooks.js:61:3)
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/sequential/test-perf-hooks.js:78:1)
        at Module._compile (node:internal/modules/cj...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59117/](https://ci.nodejs.org/job/node-test-pull-request/68241/), [https://github.com/nodejs/node/pull/59104/](https://ci.nodejs.org/job/node-test-pull-request/68254/), [https://github.com/nodejs/node/pull/59156/](https://ci.nodejs.org/job/node-test-pull-request/68287/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68297/), [https://github.com/nodejs/node/pull/59267/](https://ci.nodejs.org/job/node-test-pull-request/68309/), [https://github.com/nodejs/node/pull/59276/](https://ci.nodejs.org/job/node-test-pull-request/68325/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35883/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68241/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68325/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35883/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/panva/node/pull/4/](https://ci.nodejs.org/job/node-test-pull-request/68244/), [https://github.com/nodejs/node/pull/59213/](https://ci.nodejs.org/job/node-test-pull-request/68303/), [https://github.com/nodejs/node/pull/59243/](https://ci.nodejs.org/job/node-test-pull-request/68320/), [https://github.com/nodejs/node/pull/59276/](https://ci.nodejs.org/job/node-test-pull-request/68333/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/52017/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52005/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51993/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/61169/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68244/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68333/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/52017/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>sh: line 1: 429:: command not found</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59117/](https://ci.nodejs.org/job/node-test-pull-request/68241/), [https://github.com/nodejs/node/pull/59257/](https://ci.nodejs.org/job/node-test-pull-request/68297/), [https://github.com/nodejs/node/pull/59213/](https://ci.nodejs.org/job/node-test-pull-request/68298/), [https://github.com/nodejs/node/pull/59060/](https://ci.nodejs.org/job/node-test-pull-request/68299/)) |
| Appeared | [test-mnx-smartos22-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/61754/console), [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/61754/console), [vm-wcda4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66029/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59621/console), [test-digitalocean-ubuntu2204-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2204-64/65825/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68241/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68299/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/61754/console">Example</a></summary>

```
sh: line 1: 429:: command not found
```
</details>

-------

| Reason | <code>Error: - process terminated with status 1, expected 0</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59221/](https://ci.nodejs.org/job/node-test-pull-request/68273/), [https://github.com/nodejs/node/pull/59156/](https://ci.nodejs.org/job/node-test-pull-request/68287/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35821/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68273/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68287/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2019/35821/console">Example</a></summary>

```
Error: - process terminated with status 1, expected 0
  ---
  duration_ms: 47325.61800
  ...
ok 1000 sequential/test-single-executable-application-snapshot-worker # skip Cannot find signtool: Error: - process terminated with status 1, expected 0
  ---
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59040/](https://ci.nodejs.org/job/node-test-pull-request/68279/), [https://github.com/nodejs/node/pull/59213/](https://ci.nodejs.org/job/node-test-pull-request/68314/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/68314/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68279/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68314/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/68314/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------


### undefined

| Reason | <code>Unknown</code> |
| - | :- |
| Type | undefined |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59221/](https://ci.nodejs.org/job/node-test-pull-request/68273/), [https://github.com/nodejs/node/pull/59060/](https://ci.nodejs.org/job/node-test-pull-request/68299/)) |
| Appeared | [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022_clang/35856/), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/35829/), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022_clang/35829/) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68273/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68299/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022_clang/35856/">Example</a></summary>

```
Unknown
```
</details>

-------

