Failures in [node-test-pull-request/67294](https://ci.nodejs.org/job/node-test-pull-request/67294/) to [node-test-pull-request/67390](https://ci.nodejs.org/job/node-test-pull-request/67390/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-06-11.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-06-11 00:11 | 1       | 6       | 39       | 1       | 53      | 6.12%      |


### JSTest Failure

| Reason | <code>parallel/test-buffer-tostring-range</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/58615/](https://ci.nodejs.org/job/node-test-pull-request/67312/), [https://github.com/nodejs/node/pull/58643/](https://ci.nodejs.org/job/node-test-pull-request/67356/), [https://github.com/nodejs/node/pull/58580/](https://ci.nodejs.org/job/node-test-pull-request/67360/), [https://github.com/nodejs/node/pull/58280/](https://ci.nodejs.org/job/node-test-pull-request/67366/), [https://github.com/nodejs/node/pull/58610/](https://ci.nodejs.org/job/node-test-pull-request/67370/), [https://github.com/nodejs/node/pull/58657/](https://ci.nodejs.org/job/node-test-pull-request/67375/), [https://github.com/nodejs/node/pull/58659/](https://ci.nodejs.org/job/node-test-pull-request/67379/), [https://github.com/nodejs/node/pull/58537/](https://ci.nodejs.org/job/node-test-pull-request/67381/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67388/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34731/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67312/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67388/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34731/console">Example</a></summary>

```
not ok 103 parallel/test-buffer-tostring-range
  ---
  duration_ms: 174.00800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/buffer:961
        super(bufferOrLength, byteOffset, length);
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at Function.alloc (node:buffer:397:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-range.js:107:28)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    
    Node.js v20.19.3
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67294/), [https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67337/), [https://github.com/nodejs/node/pull/58588/](https://ci.nodejs.org/job/node-test-pull-request/67344/), [https://github.com/nodejs/node/pull/58657/](https://ci.nodejs.org/job/node-test-pull-request/67375/), [https://github.com/nodejs/node/pull/58659/](https://ci.nodejs.org/job/node-test-pull-request/67376/), [https://github.com/nodejs/node/pull/58661/](https://ci.nodejs.org/job/node-test-pull-request/67380/), [https://github.com/nodejs/node/pull/58537/](https://ci.nodejs.org/job/node-test-pull-request/67381/)) |
| Appeared | [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65094/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49982/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51106/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67294/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67381/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65094/console">Example</a></summary>

```
not ok 4450 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7393.81900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58620/](https://ci.nodejs.org/job/node-test-pull-request/67318/), [https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67324/), [https://github.com/nodejs/node/pull/58633/](https://ci.nodejs.org/job/node-test-pull-request/67327/)) |
| Appeared | [vm-87vwc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65448/console), [vm-jcgjr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65444/console), [vm-4p2n2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65438/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67318/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67327/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65448/console">Example</a></summary>

```
not ok 2651 parallel/test-runner-run-watch
  ---
  duration_ms: 23704.17600
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 248.711538,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58490/](https://ci.nodejs.org/job/node-test-pull-request/67300/), [https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67324/), [https://github.com/nodejs/node/pull/58412/](https://ci.nodejs.org/job/node-test-pull-request/67358/)) |
| Appeared | [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65075/console), [vm-jcgjr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65444/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67300/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67358/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65075/console">Example</a></summary>

```
not ok 4449 sequential/test-perf-hooks
  ---
  duration_ms: 273.95100
  severity: fail
  exitcode: 1
  stack: |-
    check initial nodeTiming
    {
      "name": "node",
      "entryType": "node",
      "startTime": 0,
      "duration": 148.321331,
      "nodeStart": 0.7730073928833008,
      "v8Start": 12.836664199829102,
      "environment": 24.59217643737793,
      "loopStart": -1,
      "loopExit": -1,
      "bootstrapComplete": 64.06853294372559,
      "idleTime": 0,
      "uvMetricsInfo": {
        "loopCount": 0,
        "events": 0,
        "eventsWaiting": 0
      }
    }
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: now (178.79171) - timing.duration (148.321331) = 30.47037900000001 >= 10
        at checkNodeTiming (/home/iojs/build/workspace/node/test/sequential/test-perf-hooks.js:61:3)
        at Object.<anonymous> (/home/iojs/build/workspace/node/test/sequential/test-perf-hooks.js:78:1)
        at Module._compile (node:internal/modules/cjs...
```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67299/), [https://github.com/nodejs/node/pull/58635/](https://ci.nodejs.org/job/node-test-pull-request/67341/), [https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67353/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51122/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51110/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67299/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67353/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51122/console">Example</a></summary>

```
not ok 4473 sequential/test-tls-session-timeout
  ---
  duration_ms: 281.24400
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-config-file</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58637/](https://ci.nodejs.org/job/node-test-pull-request/67354/), [https://github.com/nodejs/node/pull/58610/](https://ci.nodejs.org/job/node-test-pull-request/67370/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34711/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/34711/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/34711/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34711/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34711/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34697/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34660/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/34660/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022_clang/34660/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/34660/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022_clang/34660/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67354/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67370/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34711/console">Example</a></summary>

```
not ok 176 parallel/test-config-file
  ---
  duration_ms: 299.99900
  severity: fail
  exitcode: 1
  stack: |-
    d:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-config-file.js:11
    const isRoot = process.getuid() === 0;
                           ^
    
    TypeError: process.getuid is not a function
        at Object.<anonymous> (d:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-config-file.js:11:24)
        at Module._compile (node:internal/modules/cjs/loader:1733:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1898:10)
        at Module.load (node:internal/modules/cjs/loader:1468:32)
        at Module._load (node:internal/modules/cjs/loader:1285:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:152:5)
        at node:internal/main/run_main_module:33:47
    
  ...
```
</details>

-------

| Reason | <code>parallel/test-debugger-break</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67299/), [https://github.com/nodejs/node/pull/58598/](https://ci.nodejs.org/job/node-test-pull-request/67386/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/34729/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67299/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67386/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/34729/console">Example</a></summary>

```
not ok 214 parallel/test-debugger-break
  ---
  duration_ms: 463.01200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/process/promises:394
        triggerUncaughtException(err, true /* fromPromise */);
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert.ok(cli.output.includes(`#1 ${script}:16`))
    
        at c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-debugger-break.js:64:10
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-autoselectfamily</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67299/), [https://github.com/nodejs/node/pull/58490/](https://ci.nodejs.org/job/node-test-pull-request/67350/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51120/console), [test-mnx-smartos22-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/60999/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67299/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67350/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51120/console">Example</a></summary>

```
not ok 2469 parallel/test-net-autoselectfamily
  ---
  duration_ms: 5239.49400
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
      [
        '2606:4700::6810:85e5:36677',
        '104.20.22.46:36677',
        '2606:4700::6810:84e5:36677',
        '104.20.23.46:36677',
        '::1:36677',
    -   '127.0.0.1:36677'
      ]
    
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/parallel/test-net-autoselectfamily.js:84:14)
        at Socket.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/common/index.js:437:15)
        at Socket.emit (node:events:507:28)
        at afterConnect (node:net:1623:10)
        at afterConnectMultiple (node:net:1729:3) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: [
        '2606:4700::6810:85e5:36677',
    ...
```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58603/](https://ci.nodejs.org/job/node-test-pull-request/67343/), [https://github.com/nodejs/node/pull/58640/](https://ci.nodejs.org/job/node-test-pull-request/67348/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49955/console), [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59360/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67343/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67348/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49955/console">Example</a></summary>

```
not ok 4103 parallel/test-stream-readable-to-web
  ---
  duration_ms: 120108.21100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67324/), [https://github.com/nodejs/node/pull/58630/](https://ci.nodejs.org/job/node-test-pull-request/67325/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51095/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67324/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67325/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51095/console">Example</a></summary>

```
not ok 4094 parallel/test-without-async-context-frame
  ---
  duration_ms: 120091.57300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58615/](https://ci.nodejs.org/job/node-test-pull-request/67312/), [https://github.com/nodejs/node/pull/58537/](https://ci.nodejs.org/job/node-test-pull-request/67381/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57664/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67312/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67381/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57664/console">Example</a></summary>

```
not ok 4527 wpt/test-streams
  ---
  duration_ms: 1464.82600
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; fulfilled cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; rejected cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel = undefined (falsy); ful...
```
</details>

-------

| Reason | <code>wpt/test-wasm-webapi</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67299/), [https://github.com/nodejs/node/pull/58537/](https://ci.nodejs.org/job/node-test-pull-request/67381/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34725/console), [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34644/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67299/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67381/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34725/console">Example</a></summary>

```
not ok 1071 wpt/test-wasm-webapi
  ---
  duration_ms: 366.85400
  severity: crashed
  exitcode: 3221225477
  stack: |-
    [SKIPPED] abort.any.js: WPTRunner does not support fetch()
    [SKIPPED] contenttype.any.js: WPTRunner does not support fetch()
    [SKIPPED] historical.any.js: indexedDB is not defined
    [SKIPPED] idlharness.any.js: not configured
    [SKIPPED] instantiateStreaming-bad-imports.any.js: Flaky on ARM with V8 >= 11.2
    [SKIPPED] origin.sub.any.js: CORS not implemented
    [SKIPPED] status.any.js: WPTRunner does not support fetch()
    [PASS] compileStreaming
    [PASS] instantiateStreaming
    [PASS] compileStreaming: no body
    [PASS] compileStreaming: no body in a promise
    [PASS] compileStreaming: undefined
    [PASS] compileStreaming: undefined in a promise
    [PASS] compileStreaming: null
    [PASS] compileStreaming: null in a promise
    [PASS] compileStreaming: true
    [PASS] compileStreaming: true in a promise
    [PASS] compileStreaming: "test"
    [PASS] compileStreaming: ...
```
</details>

-------

| Reason | <code>wpt/test-webcrypto</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58280/](https://ci.nodejs.org/job/node-test-pull-request/67366/), [https://github.com/nodejs/node/pull/58517/](https://ci.nodejs.org/job/node-test-pull-request/67389/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57669/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67366/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67389/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57669/console">Example</a></summary>

```
not ok 4544 wpt/test-webcrypto
  ---
  duration_ms: 11396.49500
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] algorithm-discards-context.https.window.js: Not relevant in Node.js context
    [SKIPPED] historical.any.js: Not relevant in Node.js context
    [PASS] CryptoKey.algorithm getter returns cached object
    [PASS] CryptoKey.usages getter returns cached object
    [PASS] setup - define tests
    [PASS] X25519 key derivation checks for all-zero value result with a key of order 0
    [PASS] X25519 key derivation checks for all-zero value result with a key of order 1
    [PASS] X25519 key derivation checks for all-zero value result with a key of order 8
    [PASS] X25519 key derivation checks for all-zero value result with a key of order p-1 (order 2)
    [PASS] X25519 key derivation checks for all-zero value result with a key of order p (=0, order 4)
    [PASS] X25519 key derivation checks for all-zero value result with a key of order p+1 (=1, order 1)
    [PASS] X25519 good parameters
    [...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67302/), [https://github.com/nodejs/node/pull/58635/](https://ci.nodejs.org/job/node-test-pull-request/67345/), [https://github.com/nodejs/node/pull/58643/](https://ci.nodejs.org/job/node-test-pull-request/67356/), [https://github.com/nodejs/node/pull/58280/](https://ci.nodejs.org/job/node-test-pull-request/67366/), [https://github.com/nodejs/node/pull/58657/](https://ci.nodejs.org/job/node-test-pull-request/67375/), [https://github.com/nodejs/node/pull/58659/](https://ci.nodejs.org/job/node-test-pull-request/67379/), [https://github.com/nodejs/node/pull/58537/](https://ci.nodejs.org/job/node-test-pull-request/67381/), [https://github.com/nodejs/node/pull/58598/](https://ci.nodejs.org/job/node-test-pull-request/67386/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34729/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67302/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67386/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34729/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67333/), [https://github.com/nodejs/node/pull/58620/](https://ci.nodejs.org/job/node-test-pull-request/67334/), [https://github.com/nodejs/node/pull/58598/](https://ci.nodejs.org/job/node-test-pull-request/67377/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/67377/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67333/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67377/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/67377/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

| Reason | <code>fatal error: Killed signal terminated program cc1plus</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58631/](https://ci.nodejs.org/job/node-test-pull-request/67323/), [https://github.com/nodejs/node/pull/58455/](https://ci.nodejs.org/job/node-test-pull-request/67390/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51151/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51151/console), [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/65041/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51093/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl30_x64/51093/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67323/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67390/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/51151/console">Example</a></summary>

```
fatal error: Killed signal terminated program cc1plus
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67294/), [https://github.com/nodejs/node/pull/58280/](https://ci.nodejs.org/job/node-test-pull-request/67366/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51134/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51065/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67294/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67366/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51134/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

