Failures in [node-test-pull-request/67191](https://ci.nodejs.org/job/node-test-pull-request/67191/) to [node-test-pull-request/67287](https://ci.nodejs.org/job/node-test-pull-request/67287/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-06-06.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-06-06 00:11 | 0       | 13      | 27       | 5       | 55      | 13.68%     |


### JSTest Failure

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/58514/](https://ci.nodejs.org/job/node-test-pull-request/67202/), [https://github.com/nodejs/node/pull/58524/](https://ci.nodejs.org/job/node-test-pull-request/67203/), [https://github.com/nodejs/node/pull/58512/](https://ci.nodejs.org/job/node-test-pull-request/67217/), [https://github.com/nodejs/node/pull/58521/](https://ci.nodejs.org/job/node-test-pull-request/67232/), [https://github.com/nodejs/node/pull/58546/](https://ci.nodejs.org/job/node-test-pull-request/67240/), [https://github.com/nodejs/node/pull/58272/](https://ci.nodejs.org/job/node-test-pull-request/67266/), [https://github.com/nodejs/node/pull/57682/](https://ci.nodejs.org/job/node-test-pull-request/67275/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51044/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49870/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51004/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/50985/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67202/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67275/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51044/console">Example</a></summary>

```
not ok 4437 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7231.24000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58514/](https://ci.nodejs.org/job/node-test-pull-request/67196/), [https://github.com/nodejs/node/pull/58293/](https://ci.nodejs.org/job/node-test-pull-request/67201/), [https://github.com/nodejs/node/pull/58272/](https://ci.nodejs.org/job/node-test-pull-request/67219/), [https://github.com/nodejs/node/pull/58418/](https://ci.nodejs.org/job/node-test-pull-request/67287/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49895/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/49820/console), [test-osuosl-rhel8-ppc64_le-4](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59235/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67196/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67287/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49895/console">Example</a></summary>

```
not ok 4103 parallel/test-stream-readable-to-web
  ---
  duration_ms: 120095.98000
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>async-hooks/test-improper-order</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58357/](https://ci.nodejs.org/job/node-test-pull-request/67192/), [https://github.com/nodejs/node/pull/58404/](https://ci.nodejs.org/job/node-test-pull-request/67198/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57507/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67192/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67198/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57507/console">Example</a></summary>

```
not ok 68 async-hooks/test-improper-order
  ---
  duration_ms: 459.21600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:94
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 1
    
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/async-hooks/test-improper-order.js:55:12)
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/common/index.js:437:15)
        at ChildProcess.emit (node:events:507:28)
        at maybeClose (node:internal/child_process:1101:16)
        at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 1,
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-performance-eventlooputil</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58560/](https://ci.nodejs.org/job/node-test-pull-request/67253/), [https://github.com/nodejs/node/pull/57909/](https://ci.nodejs.org/job/node-test-pull-request/67271/)) |
| Appeared | [test-ibm-rhel9-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/64988/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51021/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67253/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67271/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/64988/console">Example</a></summary>

```
not ok 2386 parallel/test-performance-eventlooputil
  ---
  duration_ms: 175.75200
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: 76.69584846496582 < 76.6958490826416
        at Timeout.runCalcTest (/home/iojs/build/workspace/node/test/parallel/test-performance-eventlooputil.js:85:10)
        at Timeout.runCalcTest [as _onTimeout] (/home/iojs/build/workspace/node/test/common/index.js:437:15)
        at listOnTimeout (node:internal/timers:610:11)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58529/](https://ci.nodejs.org/job/node-test-pull-request/67204/), [https://github.com/nodejs/node/pull/58548/](https://ci.nodejs.org/job/node-test-pull-request/67258/)) |
| Appeared | [vm-c5vdn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65382/console), [vm-4b658](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65338/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67204/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67258/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65382/console">Example</a></summary>

```
not ok 2635 parallel/test-runner-run-watch
  ---
  duration_ms: 27651.71200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run tests with dependency repeatedly'
    Location: test/parallel/test-runner-run-watch.mjs:202:3
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:
    
    '# Subtest: test.js\n' +
      'not ok 2 - test.js\n' +
      '  ---\n' +
      '  duration_ms: 1010.679438\n' +
      "  type: 'test'\n" +
      "  location: '/Users/admin/node-tmp/.tmp.2592/test.js:1:1'\n" +
      "  failureType: 'testCodeFailure'\n" +
      '  exitCode: ~\n' +
      "  signal: 'SIGTERM'\n" +
      "  error: 'test failed'\n" +
      "  code: 'ERR_TEST_FAILURE'\n" +
      '  ...\n' +
      '# Subtest: test has ran\n' +
      'ok 2 - test has ran\n' +
      '  ---\n' +
      '  duration_ms: 1.000948\n' +
      "  type: 'test'\n" +
      '  ...\n' +
      '1..2\n' +
      '# tests 2\n' +
      '# suites 0\n' +
      '# pass 1\n' +
      '# fail 1\...
```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58512/](https://ci.nodejs.org/job/node-test-pull-request/67191/), [https://github.com/nodejs/node/pull/58533/](https://ci.nodejs.org/job/node-test-pull-request/67209/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50980/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50964/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67191/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67209/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/50980/console">Example</a></summary>

```
not ok 4517 sequential/test-tls-session-timeout
  ---
  duration_ms: 169.91800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:94
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58512/](https://ci.nodejs.org/job/node-test-pull-request/67191/), [https://github.com/nodejs/node/pull/58293/](https://ci.nodejs.org/job/node-test-pull-request/67234/), [https://github.com/nodejs/node/pull/58561/](https://ci.nodejs.org/job/node-test-pull-request/67263/), [https://github.com/nodejs/node/pull/58579/](https://ci.nodejs.org/job/node-test-pull-request/67286/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/34624/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67191/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67286/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/34624/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58540/](https://ci.nodejs.org/job/node-test-pull-request/67248/), [https://github.com/nodejs/node/pull/58543/](https://ci.nodejs.org/job/node-test-pull-request/67254/), [https://github.com/nodejs/node/pull/58567/](https://ci.nodejs.org/job/node-test-pull-request/67264/), [https://github.com/nodejs/node/pull/58502/](https://ci.nodejs.org/job/node-test-pull-request/67278/)) |
| Appeared | [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/64998/console), [test-mnx-smartos22-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/60964/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67278/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/64998/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58533/](https://ci.nodejs.org/job/node-test-pull-request/67209/), [https://github.com/nodejs/node/pull/58512/](https://ci.nodejs.org/job/node-test-pull-request/67217/), [https://github.com/nodejs/node/pull/58461/](https://ci.nodejs.org/job/node-test-pull-request/67239/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/60437/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50985/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/50980/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67209/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67239/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-linter/60437/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58491/](https://ci.nodejs.org/job/node-test-pull-request/67195/), [https://github.com/nodejs/node/pull/58461/](https://ci.nodejs.org/job/node-test-pull-request/67233/)) |
| Appeared | [test-mnx-smartos22-x64-3](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/60937/console), [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/60937/console), [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57537/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67195/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67233/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/60937/console">Example</a></summary>

```
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58489/](https://ci.nodejs.org/job/node-test-pull-request/67226/), [https://github.com/nodejs/node/pull/58461/](https://ci.nodejs.org/job/node-test-pull-request/67244/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/67244/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67226/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67244/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/67244/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

