Failures in [node-test-pull-request/69160](https://ci.nodejs.org/job/node-test-pull-request/69160/) to [node-test-pull-request/69256](https://ci.nodejs.org/job/node-test-pull-request/69256/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-09-17.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-09-17 00:10 | 1       | 14      | 25       | 7       | 53      | 15.22%     |


### JSTest Failure

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58797/](https://ci.nodejs.org/job/node-test-pull-request/69186/), [https://github.com/nodejs/node/pull/59824/](https://ci.nodejs.org/job/node-test-pull-request/69192/), [https://github.com/nodejs/node/pull/59860/](https://ci.nodejs.org/job/node-test-pull-request/69193/), [https://github.com/nodejs/node/pull/59857/](https://ci.nodejs.org/job/node-test-pull-request/69201/), [https://github.com/nodejs/node/pull/59856/](https://ci.nodejs.org/job/node-test-pull-request/69254/)) |
| Appeared | [vm-8988l](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66809/console), [vm-ergha](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66747/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60763/console), [vm-weyr3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66743/console), [vm-7amz7](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66738/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69186/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69254/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66809/console">Example</a></summary>

```
not ok 4349 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 616.21500
  severity: fail
  exitcode: 1
  stack: |-
    #6 eneded response for: 'https://local\rhost:62883/carriage-return-in-host'
    #5 eneded response for: 'https://localhost:6\r2883/carriage-return-in-port'
    #4 eneded response for: 'https://localhost:6\n2883/newline-in-port'
    #3 eneded response for: 'https://local\r\nhost:62883/crlf-in-host'
    #2 eneded response for: 'https://localhost:6\r\n2883/crlf-in-port'
    #1 eneded response for: 'https://local\nhost:62883/newline-in-host'
    node:assert:149
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Set(13) {
    - Set(6) {
        {
    +     error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    +         at _write (node:internal/streams/writable:487:11)
    +         at Writable.write (node:internal/streams/writable:508:10)
    +     ...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59816/](https://ci.nodejs.org/job/node-test-pull-request/69164/), [https://github.com/nodejs/node/pull/59703/](https://ci.nodejs.org/job/node-test-pull-request/69169/), [https://github.com/nodejs/node/pull/59841/](https://ci.nodejs.org/job/node-test-pull-request/69172/), [https://github.com/nodejs/node/pull/58850/](https://ci.nodejs.org/job/node-test-pull-request/69207/), [https://github.com/nodejs/node/pull/59867/](https://ci.nodejs.org/job/node-test-pull-request/69210/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59020/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69164/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69210/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59020/console">Example</a></summary>

```
not ok 4815 wpt/test-streams
  ---
  duration_ms: 1434.65100
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] a signal argument 'null' should cause pipeTo() to reject
    [PASS] a signal argument 'AbortSignal' should cause pipeTo() to reject
    [PASS] a signal argument 'true' should cause pipeTo() to reject
    [PASS] a signal argument '-1' should cause pipeTo() to reject
    [PASS] a signal argument '[object AbortSi...
```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59816/](https://ci.nodejs.org/job/node-test-pull-request/69164/), [https://github.com/nodejs/node/pull/58169/](https://ci.nodejs.org/job/node-test-pull-request/69206/), [https://github.com/nodejs/node/pull/59856/](https://ci.nodejs.org/job/node-test-pull-request/69254/)) |
| Appeared | [vm-8988l](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66809/console), [vm-rtc0x](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66753/console), [vm-ofpsc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66717/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69164/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69254/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66809/console">Example</a></summary>

```
not ok 2793 parallel/test-runner-run-watch
  ---
  duration_ms: 31479.26100
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 287.131639,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59826/](https://ci.nodejs.org/job/node-test-pull-request/69180/), [https://github.com/nodejs/node/pull/59892/](https://ci.nodejs.org/job/node-test-pull-request/69238/), [https://github.com/nodejs/node/pull/59856/](https://ci.nodejs.org/job/node-test-pull-request/69254/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20375/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69180/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69254/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20375/console">Example</a></summary>

```
not ok 2936 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 6121.21300
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'can be overridden (to SIGINT)'
    Location: test/parallel/test-runner-watch-mode-kill-signal.mjs:72:3
    AssertionError [ERR_ASSERTION]: The input was expected to not match the regular expression /__SIGTERM received__/. Input:
    
    "Restarting '/home/iojs/node-tmp/.tmp.2936/index.js'\n" +
      '__SIGINT received__\n' +
      '__SIGTERM received__\n'
    
        at TestContext.<anonymous> (file:///home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-runner-watch-mode-kill-signal.mjs:103:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1113:7)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:788:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: "Restarting '/home/iojs/node-tmp/.tmp.2...
```
</details>

-------

| Reason | <code>async-hooks/test-emit-before-on-destroyed</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59835/](https://ci.nodejs.org/job/node-test-pull-request/69165/), [https://github.com/nodejs/node/pull/59703/](https://ci.nodejs.org/job/node-test-pull-request/69167/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58989/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58984/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69165/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69167/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58989/console">Example</a></summary>

```
not ok 39 async-hooks/test-emit-before-on-destroyed
  ---
  duration_ms: 458.94400
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 1
    
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/async-hooks/test-emit-before-on-destroyed.js:56:12)
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/common/index.js:472:15)
        at ChildProcess.emit (node:events:508:28)
        at maybeClose (node:internal/child_process:1085:16)
        at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 1,
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-heap-profiler</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59703/](https://ci.nodejs.org/job/node-test-pull-request/69167/), [https://github.com/nodejs/node/pull/59848/](https://ci.nodejs.org/job/node-test-pull-request/69179/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2019/36786/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69167/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69179/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2019/36786/console">Example</a></summary>

```
not ok 231 parallel/test-debugger-heap-profiler
  ---
  duration_ms: 2194.18000
  severity: fail
  exitcode: 1
  stack: |-
    Can't clean tmpdir: C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.195
    Files blocking: [ 'node.heapsnapshot' ]
    
    C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:69
        throw e;
        ^
    
    Error: EBUSY: resource busy or locked, rmdir 'C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.195'
        at rmdirSync (node:fs:1215:11)
        at _rmdirSync (node:internal/fs/rimraf:237:5)
        at rimrafSync (node:internal/fs/rimraf:195:7)
        at Object.rmSync (node:fs:1264:10)
        at rmSync (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:20:8)
        at onexit (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:54:5)
        at process.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:43:14)
        at process.emit (...
```
</details>

-------

| Reason | <code>parallel/test-worker-nearheaplimit-deadlock</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59872/](https://ci.nodejs.org/job/node-test-pull-request/69236/), [https://github.com/nodejs/node/pull/59901/](https://ci.nodejs.org/job/node-test-pull-request/69256/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60817/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51572/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69236/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69256/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60817/console">Example</a></summary>

```
not ok 4077 parallel/test-worker-nearheaplimit-deadlock
  ---
  duration_ms: 632.58700
  severity: crashed
  exitcode: -6
  stack: |-
    
    <--- Last few GCs --->
    
    [1783095:0x7fff68010000]       15 ms: Mark-Compact 0.7 (3.5) -> 0.7 (3.5) MB, pooled: 0.0 MB, 0.93 / 0.00 ms (average mu = 0.700, current mu = 0.154) background allocation failure; GC in old space requested
    [1783095:0x7fff68010000]       17 ms: Mark-Compact 0.7 (3.5) -> 0.7 (3.5) MB, pooled: 0.0 MB, 1.16 / 0.00 ms (average mu = 0.563, current mu = 0.158) background allocation failure; GC in old space requested
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 0x1100061c node::OOMErrorHandler(char const*, v8::OOMDetails const&) [out/Release/node]
     2: 0x113aa2bc v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [out/Release/node]
     3: 0x116a6d14 v8::internal::HeapAllocator::AllocateRawWith...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/59703/](https://ci.nodejs.org/job/node-test-pull-request/69167/), [https://github.com/nodejs/node/pull/59848/](https://ci.nodejs.org/job/node-test-pull-request/69179/), [https://github.com/nodejs/node/pull/59762/](https://ci.nodejs.org/job/node-test-pull-request/69181/), [https://github.com/nodejs/node/pull/59813/](https://ci.nodejs.org/job/node-test-pull-request/69185/), [https://github.com/nodejs/node/pull/59857/](https://ci.nodejs.org/job/node-test-pull-request/69190/), [https://github.com/nodejs/node/pull/59860/](https://ci.nodejs.org/job/node-test-pull-request/69193/), [https://github.com/nodejs/node/pull/59859/](https://ci.nodejs.org/job/node-test-pull-request/69202/), [https://github.com/nodejs/node/pull/59884/](https://ci.nodejs.org/job/node-test-pull-request/69232/), [https://github.com/nodejs/node/pull/59867/](https://ci.nodejs.org/job/node-test-pull-request/69249/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36872/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/43992/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69167/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69249/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36872/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/59824/](https://ci.nodejs.org/job/node-test-pull-request/69192/), [https://github.com/nodejs/node/pull/59860/](https://ci.nodejs.org/job/node-test-pull-request/69193/), [https://github.com/nodejs/node/pull/59857/](https://ci.nodejs.org/job/node-test-pull-request/69196/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/69226/), [https://github.com/nodejs/node/pull/59692/](https://ci.nodejs.org/job/node-test-pull-request/69228/), [https://github.com/nodejs/node/pull/59882/](https://ci.nodejs.org/job/node-test-pull-request/69229/), [https://github.com/nodejs/node/pull/59884/](https://ci.nodejs.org/job/node-test-pull-request/69232/)) |
| Appeared | [vm-6sx9m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66779/console), [vm-yz1yx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66776/console), [vm-mqa4s](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66746/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69192/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69232/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66779/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Unexpected termination of the channel</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59857/](https://ci.nodejs.org/job/node-test-pull-request/69201/), [https://github.com/nodejs/node/pull/59867/](https://ci.nodejs.org/job/node-test-pull-request/69210/), [https://github.com/nodejs/node/pull/58748/](https://ci.nodejs.org/job/node-test-pull-request/69233/)) |
| Appeared | [vm-yz1yx](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66780/console), [vm-qzvbf](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66757/console), [vm-7bk8a](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66747/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69201/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69233/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66780/console">Example</a></summary>

```
java.io.IOException: Unexpected termination of the channel
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2915)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3410)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:954)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:392)
```
</details>

-------

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59859/](https://ci.nodejs.org/job/node-test-pull-request/69198/), [https://github.com/nodejs/node/pull/58169/](https://ci.nodejs.org/job/node-test-pull-request/69206/)) |
| Appeared | [test-digitalocean-ubuntu2404-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/66583/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/43997/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69198/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69206/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu2404-x64/66583/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 165.227.180.106/165.227.180.106:60326' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy190.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59816/](https://ci.nodejs.org/job/node-test-pull-request/69164/), [https://github.com/nodejs/node/pull/59824/](https://ci.nodejs.org/job/node-test-pull-request/69192/), [https://github.com/nodejs/node/pull/59860/](https://ci.nodejs.org/job/node-test-pull-request/69193/), [https://github.com/nodejs/node/pull/59804/](https://ci.nodejs.org/job/node-test-pull-request/69224/), [https://github.com/nodejs/node/pull/59884/](https://ci.nodejs.org/job/node-test-pull-request/69231/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/66608/console), [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/60790/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52759/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52736/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52735/console), [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/61794/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69164/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69231/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/66608/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>Error: HEAD does not match expected COMMIT_SHA_CHECK'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59874/](https://ci.nodejs.org/job/node-test-pull-request/69216/), [https://github.com/nodejs/node/pull/59876/](https://ci.nodejs.org/job/node-test-pull-request/69230/)) |
| Appeared | [vm-6sx9m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66777/console), [vm-lzyf1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66764/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69216/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69230/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66777/console">Example</a></summary>

```
Error: HEAD does not match expected COMMIT_SHA_CHECK'
Error: HEAD does not match expected COMMIT_SHA_CHECK
+ exit 1
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for : : True
```
</details>

-------

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59778/](https://ci.nodejs.org/job/node-test-pull-request/69213/), [https://github.com/nodejs/node/pull/59894/](https://ci.nodejs.org/job/node-test-pull-request/69252/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/69252/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69213/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69252/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/69252/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

