Failures in [node-test-pull-request/67244](https://ci.nodejs.org/job/node-test-pull-request/67244/) to [node-test-pull-request/67337](https://ci.nodejs.org/job/node-test-pull-request/67337/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-06-09.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-06-09 00:12 | 2       | 13      | 34       | 4       | 47      | 13.83%     |


### JSTest Failure

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58548/](https://ci.nodejs.org/job/node-test-pull-request/67258/), [https://github.com/nodejs/node/pull/58620/](https://ci.nodejs.org/job/node-test-pull-request/67318/), [https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67324/), [https://github.com/nodejs/node/pull/58633/](https://ci.nodejs.org/job/node-test-pull-request/67327/)) |
| Appeared | [vm-87vwc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65448/console), [vm-jcgjr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65444/console), [vm-4p2n2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65438/console), [vm-c5vdn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65382/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67258/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67327/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65448/console">Example</a></summary>

```
not ok 2651 parallel/test-runner-run-watch
  ---
  duration_ms: 23704.17600
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 248.711538,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58583/](https://ci.nodejs.org/job/node-test-pull-request/67280/), [https://github.com/nodejs/node/pull/58597/](https://ci.nodejs.org/job/node-test-pull-request/67293/), [https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67324/), [https://github.com/nodejs/node/pull/58630/](https://ci.nodejs.org/job/node-test-pull-request/67325/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51095/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51064/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51051/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67280/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67325/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51095/console">Example</a></summary>

```
not ok 4094 parallel/test-without-async-context-frame
  ---
  duration_ms: 120091.57300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58272/](https://ci.nodejs.org/job/node-test-pull-request/67266/), [https://github.com/nodejs/node/pull/57682/](https://ci.nodejs.org/job/node-test-pull-request/67275/), [https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67294/), [https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67337/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51106/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65014/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/51044/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/49870/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67266/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67337/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/51106/console">Example</a></summary>

```
not ok 4165 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7352.36000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-range</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58342/](https://ci.nodejs.org/job/node-test-pull-request/67276/), [https://github.com/nodejs/node/pull/58615/](https://ci.nodejs.org/job/node-test-pull-request/67312/), [https://github.com/nodejs/node/pull/58610/](https://ci.nodejs.org/job/node-test-pull-request/67319/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34651/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67276/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67319/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/34651/console">Example</a></summary>

```
not ok 103 parallel/test-buffer-tostring-range
  ---
  duration_ms: 189.01300
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/buffer:961
        super(bufferOrLength, byteOffset, length);
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at Function.alloc (node:buffer:397:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-range.js:107:28)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    
    Node.js v20.19.3-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-performance-eventlooputil</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58560/](https://ci.nodejs.org/job/node-test-pull-request/67253/), [https://github.com/nodejs/node/pull/57909/](https://ci.nodejs.org/job/node-test-pull-request/67271/), [https://github.com/nodejs/node/pull/58490/](https://ci.nodejs.org/job/node-test-pull-request/67305/)) |
| Appeared | [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65023/console), [test-ibm-rhel9-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/64988/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51021/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67253/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67305/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65023/console">Example</a></summary>

```
not ok 2593 parallel/test-performance-eventlooputil
  ---
  duration_ms: 830.35800
  severity: fail
  exitcode: 1
  stack: |-
    
    node:internal/event_target:1101
      process.nextTick(() => { throw err; });
                               ^
    AssertionError [ERR_ASSERTION]: 283.4798240661621 < 283.4798243383178
        at Timeout.runCalcTest (/home/iojs/build/workspace/node/test/parallel/test-performance-eventlooputil.js:85:10)
        at Timeout.runCalcTest [as _onTimeout] (/home/iojs/build/workspace/node/test/common/index.js:437:15)
        at listOnTimeout (node:internal/timers:610:11)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58490/](https://ci.nodejs.org/job/node-test-pull-request/67300/), [https://github.com/nodejs/node/pull/58594/](https://ci.nodejs.org/job/node-test-pull-request/67324/)) |
| Appeared | [vm-jcgjr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65444/console), [test-ibm-alpine320_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/65019/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67300/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67324/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65444/console">Example</a></summary>

```
not ok 4458 sequential/test-perf-hooks
  ---
  duration_ms: 476.42500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (206.18603515625) - process.uptime() * 1000 (93.880592) = 112.30544315625 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1733:14)
        at Object..js (node:internal/modules/cjs/loader:1898:10)
        at Module.load (node:internal/modules/cjs/loader:1468:32)
        at Module._load (node:internal/modules/cjs/loader:1285:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:152:5)
        at node:internal/main/run_main_module:33:47...
```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58461/](https://ci.nodejs.org/job/node-test-pull-request/67245/), [https://github.com/nodejs/node/pull/58615/](https://ci.nodejs.org/job/node-test-pull-request/67312/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57607/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67245/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67312/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57607/console">Example</a></summary>

```
not ok 4526 wpt/test-streams
  ---
  duration_ms: 1275.58900
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] a signal argument 'null' should cause pipeTo() to reject
    [PASS] a signal argument 'AbortSignal' should cause pipeTo() to reject
    [PASS] a signal argument 'true' should cause pipeTo() to reject
    [PASS] a signal argument '-1' should cause pipeTo() to reject
    [PASS] a signal argument '[object AbortSi...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58561/](https://ci.nodejs.org/job/node-test-pull-request/67263/), [https://github.com/nodejs/node/pull/58579/](https://ci.nodejs.org/job/node-test-pull-request/67286/), [https://github.com/nodejs/node/pull/58587/](https://ci.nodejs.org/job/node-test-pull-request/67302/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34646/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67263/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67302/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/34646/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure

| Reason | <code>ERROR: Error fetching remote repo 'origin'</code> |
| - | :- |
| Type | GIT_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58540/](https://ci.nodejs.org/job/node-test-pull-request/67248/), [https://github.com/nodejs/node/pull/58543/](https://ci.nodejs.org/job/node-test-pull-request/67254/), [https://github.com/nodejs/node/pull/58567/](https://ci.nodejs.org/job/node-test-pull-request/67264/), [https://github.com/nodejs/node/pull/58502/](https://ci.nodejs.org/job/node-test-pull-request/67278/)) |
| Appeared | [test-digitalocean-fedora40-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/64998/console), [test-mnx-smartos22-x64-4](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/60964/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67248/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67278/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/64998/console">Example</a></summary>

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
```
</details>

-------


### Build Failure

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/58461/](https://ci.nodejs.org/job/node-test-pull-request/67244/), [https://github.com/nodejs/node/pull/58616/](https://ci.nodejs.org/job/node-test-pull-request/67333/), [https://github.com/nodejs/node/pull/58620/](https://ci.nodejs.org/job/node-test-pull-request/67334/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/67334/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67244/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67334/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/67334/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

