Failures in [node-test-pull-request/68586](https://ci.nodejs.org/job/node-test-pull-request/68586/) to [node-test-pull-request/68685](https://ci.nodejs.org/job/node-test-pull-request/68685/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-08-18.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-08-18 00:12 | 0       | 0       | 39       | 9       | 52      | 0.00%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68593/), [https://github.com/nodejs/node/pull/59138/](https://ci.nodejs.org/job/node-test-pull-request/68615/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68653/), [https://github.com/nodejs/node/pull/59491/](https://ci.nodejs.org/job/node-test-pull-request/68676/), [https://github.com/nodejs/node/pull/59335/](https://ci.nodejs.org/job/node-test-pull-request/68682/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36292/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68593/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68682/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36292/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59473/](https://ci.nodejs.org/job/node-test-pull-request/68636/), [https://github.com/nodejs/node/pull/58920/](https://ci.nodejs.org/job/node-test-pull-request/68657/)) |
| Appeared | [test-digitalocean-ubi81_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/52305/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022_clang-arm64/63117/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68636/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68657/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/52305/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/57866/](https://ci.nodejs.org/job/node-test-pull-request/68586/), [https://github.com/nodejs/node/pull/50353/](https://ci.nodejs.org/job/node-test-pull-request/68606/), [https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68611/), [https://github.com/nodejs/node/pull/59504/](https://ci.nodejs.org/job/node-test-pull-request/68685/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/61468/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52264/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52260/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/52245/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59856/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68586/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68685/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-linter/61468/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------


### JSTest Failure

| Reason | <code>wasi/test-wasi</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68588/), [https://github.com/nodejs/node/pull/59448/](https://ci.nodejs.org/job/node-test-pull-request/68589/), [https://github.com/nodejs/node/pull/58748/](https://ci.nodejs.org/job/node-test-pull-request/68591/), [https://github.com/nodejs/node/pull/59449/](https://ci.nodejs.org/job/node-test-pull-request/68601/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68617/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68622/), [https://github.com/nodejs/node/pull/58169/](https://ci.nodejs.org/job/node-test-pull-request/68630/), [https://github.com/nodejs/node/pull/59472/](https://ci.nodejs.org/job/node-test-pull-request/68635/), [https://github.com/nodejs/node/pull/59475/](https://ci.nodejs.org/job/node-test-pull-request/68638/), [https://github.com/nodejs/node/pull/59471/](https://ci.nodejs.org/job/node-test-pull-request/68648/), [https://github.com/nodejs/node/pull/59485/](https://ci.nodejs.org/job/node-test-pull-request/68661/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68665/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59927/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59927/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19908/console), [test-equinix-ubuntu2204_container-arm64-8](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19849/console), [test-equinix-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59861/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68588/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68665/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59927/console">Example</a></summary>

```
not ok 401 wasi/test-wasi
  ---
  duration_ms: 88654.68700
  severity: fail
  exitcode: 1
  stack: |-
    Testing with --turbo-fast-api-calls: clock_getres
    Testing with --no-turbo-fast-api-calls: clock_getres
    Testing with --turbo-fast-api-calls: getrusage
    Testing with --no-turbo-fast-api-calls: getrusage
    Testing with --turbo-fast-api-calls: readdir
    Testing with --no-turbo-fast-api-calls: readdir
    Testing with --turbo-fast-api-calls: cant_dotdot
    Testing with --no-turbo-fast-api-calls: cant_dotdot
    Testing with --turbo-fast-api-calls: fd_prestat_get_refresh
    Testing with --no-turbo-fast-api-calls: fd_prestat_get_refresh
    Testing with --turbo-fast-api-calls: ftruncate
    Testing with --no-turbo-fast-api-calls: ftruncate
    Testing with --turbo-fast-api-calls: getentropy
    Testing with --no-turbo-fast-api-calls: getentropy
    Testing with --turbo-fast-api-calls: gettimeofday
    Testing with --no-turbo-fast-api-calls: gettimeofday
    Testing with --turbo-fast-api-calls: m...
```
</details>

-------

| Reason | <code>parallel/test-http-keep-alive-empty-line</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/59314/](https://ci.nodejs.org/job/node-test-pull-request/68588/), [https://github.com/nodejs/node/pull/59448/](https://ci.nodejs.org/job/node-test-pull-request/68589/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68610/), [https://github.com/nodejs/node/pull/59475/](https://ci.nodejs.org/job/node-test-pull-request/68638/), [https://github.com/nodejs/node/pull/59471/](https://ci.nodejs.org/job/node-test-pull-request/68648/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68665/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59927/console), [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19908/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59903/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68588/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68665/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/59927/console">Example</a></summary>

```
not ok 1857 parallel/test-http-keep-alive-empty-line
  ---
  duration_ms: 1580.98000
  severity: fail
  exitcode: 1
  stack: |-
    node:events:486
          throw er; // Unhandled 'error' event
          ^
    
    Error [ERR_STREAM_WRITE_AFTER_END]: write after end
        at _write (node:internal/streams/writable:487:11)
        at Writable.write (node:internal/streams/writable:508:10)
        at Timeout._onTimeout (file:///home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-keep-alive-empty-line.mjs:32:14)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7)
    Emitted 'error' event on Socket instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_STREAM_WRITE_AFTER_END'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-mock-timers-scheduler</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58748/](https://ci.nodejs.org/job/node-test-pull-request/68591/), [https://github.com/nodejs/node/pull/59449/](https://ci.nodejs.org/job/node-test-pull-request/68601/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68620/), [https://github.com/nodejs/node/pull/59475/](https://ci.nodejs.org/job/node-test-pull-request/68638/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68665/)) |
| Appeared | [test-equinix-ubuntu2204_container-arm64-4](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19908/console), [test-equinix-ubuntu2204_container-arm64-8](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19849/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68591/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68665/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/19908/console">Example</a></summary>

```
not ok 3123 parallel/test-runner-mock-timers-scheduler
  ---
  duration_ms: 5482.14300
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should advance in time and trigger timers when calling the .tick function'
    Location: test/parallel/test-runner-mock-timers-scheduler.js:10:3
    AssertionError [ERR_ASSERTION]: time should be advanced less than the 100ms
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/parallel/test-runner-mock-timers-scheduler.js:21:14
        at /home/iojs/build/workspace/node-test-commit-arm-debug/test/common/index.js:437:15
        at async Test.run (node:internal/test_runner/test:1088:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1485:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:332:3) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59448/](https://ci.nodejs.org/job/node-test-pull-request/68589/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68618/), [https://github.com/nodejs/node/pull/59471/](https://ci.nodejs.org/job/node-test-pull-request/68648/), [https://github.com/nodejs/node/pull/59456/](https://ci.nodejs.org/job/node-test-pull-request/68658/), [https://github.com/nodejs/node/pull/59504/](https://ci.nodejs.org/job/node-test-pull-request/68685/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51105/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/52271/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/52246/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68589/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68685/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51105/console">Example</a></summary>

```
not ok 4233 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 14720.27000
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:581:17)
        at process.processTimers (node:internal/timers:519:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v20.19.5-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-crypto-dh-generate-keys</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58920/](https://ci.nodejs.org/job/node-test-pull-request/68657/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68659/), [https://github.com/nodejs/node/pull/59466/](https://ci.nodejs.org/job/node-test-pull-request/68660/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68662/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36258/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68657/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68662/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36258/console">Example</a></summary>

```
not ok 1039 parallel/test-crypto-dh-generate-keys
  ---
  duration_ms: 120214.63200
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-esm-loader-hooks-inspect-wait</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58920/](https://ci.nodejs.org/job/node-test-pull-request/68657/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68659/), [https://github.com/nodejs/node/pull/59466/](https://ci.nodejs.org/job/node-test-pull-request/68660/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68662/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/36260/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68657/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68662/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2019/36260/console">Example</a></summary>

```
not ok 257 parallel/test-esm-loader-hooks-inspect-wait
  ---
  duration_ms: 3802.01300
  severity: fail
  exitcode: 1
  stack: |-
    [test] Connecting to a child Node process
    [test] Testing /json/list
    [err] Debugger listening on ws://127.0.0.1:59038/af80bbfa-317c-4a79-92e9-5e40c6088996
    [err] 
    [err] For help, see: https://nodejs.org/en/docs/inspector
    [err] 
    [err] Debugger attached.
    [err] 
    [err] Waiting for the debugger to disconnect...
    [err] 
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    3221225477 !== 0
    
        at runTest (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-esm-loader-hooks-inspect-wait.js:27:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 3221225477,
      expected: 0,
      operator: 'strictEqual'
    }
    1
  ...

```
</details>

-------

| Reason | <code>parallel/test-npm-install</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58920/](https://ci.nodejs.org/job/node-test-pull-request/68657/), [https://github.com/nodejs/node/pull/59461/](https://ci.nodejs.org/job/node-test-pull-request/68659/), [https://github.com/nodejs/node/pull/59466/](https://ci.nodejs.org/job/node-test-pull-request/68660/), [https://github.com/nodejs/node/pull/59368/](https://ci.nodejs.org/job/node-test-pull-request/68662/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/36268/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68657/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68662/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/36268/console">Example</a></summary>

```
not ok 802 parallel/test-npm-install
  ---
  duration_ms: 121871.84900
  severity: fail
  exitcode: 1
  stack: |-
    timeout
    npm warn cli npm v11.5.1 does not support Node.js v25.0.0-pre. This version of npm supports the following node versions: `^20.17.0 || >=22.9.0`. You can find the latest version at https://nodejs.org/.
    npm warn Unknown env config "tmp". This will stop working in the next major version of npm.
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-outgoing-end-cork</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68597/), [https://github.com/nodejs/node/pull/59420/](https://ci.nodejs.org/job/node-test-pull-request/68610/), [https://github.com/nodejs/node/pull/59471/](https://ci.nodejs.org/job/node-test-pull-request/68648/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59911/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18390/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68597/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68648/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/59911/console">Example</a></summary>

```
not ok 1881 parallel/test-http-outgoing-end-cork
  ---
  duration_ms: 1493.58000
  severity: fail
  exitcode: 1
  stack: |-
    Sending req no 1
    node:assert:177
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: () => {
        reject(new Error('Request timed out'));
      } at /home/iojs/build/workspace/node-test-commit-arm/test/parallel/test-http-outgoing-end-cork.js:53
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-arm/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-performance-eventlooputil</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58920/](https://ci.nodejs.org/job/node-test-pull-request/68642/), [https://github.com/nodejs/node/pull/59335/](https://ci.nodejs.org/job/node-test-pull-request/68682/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/66166/console), [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/52292/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68642/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68682/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/66166/console">Example</a></summary>

```
not ok 2726 parallel/test-performance-eventlooputil
  ---
  duration_ms: 134.19800
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:273
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: 49.24276351928711 >= 49.24276351928711
        at Timeout.r (/home/iojs/build/workspace/node/test/parallel/test-performance-eventlooputil.js:52:10)
        at Timeout.r [as _onTimeout] (/home/iojs/build/workspace/node/test/common/index.js:437:15)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59447/](https://ci.nodejs.org/job/node-test-pull-request/68594/), [https://github.com/nodejs/node/pull/59484/](https://ci.nodejs.org/job/node-test-pull-request/68656/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58611/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68656/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58611/console">Example</a></summary>

```
not ok 4746 wpt/test-streams
  ---
  duration_ms: 1419.25600
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; fulfilled cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; rejected cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel = undefined (falsy); ful...
```
</details>

-------

