Failures in [node-test-pull-request/65095](https://ci.nodejs.org/job/node-test-pull-request/65095/) to [node-test-pull-request/65191](https://ci.nodejs.org/job/node-test-pull-request/65191/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-02-14.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-02-14 00:09 | 3       | 18      | 10       | 9       | 60      | 20.45%     |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/), [https://github.com/nodejs/node/pull/57018/](https://ci.nodejs.org/job/node-test-pull-request/65157/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65160/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65161/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65162/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65163/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65176/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32614/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65156/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65176/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/32614/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>sh: line 9: [: -gt: unary operator expected</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/), [https://github.com/nodejs/node/pull/57018/](https://ci.nodejs.org/job/node-test-pull-request/65157/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65160/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65161/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65162/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65163/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65176/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32616/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65156/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65176/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2019/32616/console">Example</a></summary>

```
sh: line 9: [: -gt: unary operator expected
```
</details>

-------

| Reason | <code>fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-native-suites/build'</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/55873/](https://ci.nodejs.org/job/node-test-pull-request/65151/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65158/), [https://github.com/nodejs/node/pull/56843/](https://ci.nodejs.org/job/node-test-pull-request/65165/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65167/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win11-vs2022-COMPILED_BY-vs2022/26880/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65151/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65167/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win11-vs2022-COMPILED_BY-vs2022/26880/console">Example</a></summary>

```
fatal: detected dubious ownership in repository at 'C:/workspace/node-test-binary-windows-native-suites/build'
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56965/](https://ci.nodejs.org/job/node-test-pull-request/65100/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56843/](https://ci.nodejs.org/job/node-test-pull-request/65185/), [https://github.com/nodejs/node/pull/57034/](https://ci.nodejs.org/job/node-test-pull-request/65186/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49067/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49066/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutssl_x64/49034/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/48982/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65100/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65186/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49067/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

| Reason | <code>error: remote GitHub already exists.</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56872/](https://ci.nodejs.org/job/node-test-pull-request/65145/), [https://github.com/nodejs/node/pull/57022/](https://ci.nodejs.org/job/node-test-pull-request/65171/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60439/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65145/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65171/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-compile-windows/nodes=win-vs2022-arm64/60439/console">Example</a></summary>

```
error: remote GitHub already exists.

> git fetch --prune --no-tags GitHub 

> git fetch --prune --no-tags https://github.com/nodejs/build.git +refs/heads/main:refs/remotes/jenkins_tmp
```
</details>

-------


### CCTest Failure


### JSTest Failure

| Reason | <code>parallel/test-assert-fail</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/56970/](https://ci.nodejs.org/job/node-test-pull-request/65095/), [https://github.com/nodejs/node/pull/56988/](https://ci.nodejs.org/job/node-test-pull-request/65132/), [https://github.com/nodejs/node/pull/57001/](https://ci.nodejs.org/job/node-test-pull-request/65133/), [https://github.com/nodejs/node/pull/56967/](https://ci.nodejs.org/job/node-test-pull-request/65134/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65148/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/56906/](https://ci.nodejs.org/job/node-test-pull-request/65155/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65161/), [https://github.com/nodejs/node/pull/57023/](https://ci.nodejs.org/job/node-test-pull-request/65173/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65175/), [https://github.com/nodejs/node/pull/57026/](https://ci.nodejs.org/job/node-test-pull-request/65187/), [https://github.com/nodejs/node/pull/56919/](https://ci.nodejs.org/job/node-test-pull-request/65191/)) |
| Appeared | [test-orka-macos11-x64-2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65095/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65191/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx11-x64/63378/console">Example</a></summary>

```
not ok 18 parallel/test-assert-fail
  ---
  duration_ms: 432.50400
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'Object prototype get'
    Location: test/parallel/test-assert-fail.js:46:1
    Error: fail
        at TestContext.<anonymous> (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx11-x64/test/parallel/test-assert-fail.js:50:9)
        at Test.runInAsyncScope (node:async_hooks:211:14)
        at Test.run (node:internal/test_runner/test:980:25)
        at Test.processPendingSubtests (node:internal/test_runner/test:678:18)
        at Test.postRun (node:internal/test_runner/test:1091:19)
        at Test.run (node:internal/test_runner/test:1019:12)
        at async Test.processPendingSubtests (node:internal/test_runner/test:678:7)
    
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/56970/](https://ci.nodejs.org/job/node-test-pull-request/65095/), [https://github.com/nodejs/node/pull/56988/](https://ci.nodejs.org/job/node-test-pull-request/65132/), [https://github.com/nodejs/node/pull/57012/](https://ci.nodejs.org/job/node-test-pull-request/65148/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65149/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65161/), [https://github.com/nodejs/node/pull/57023/](https://ci.nodejs.org/job/node-test-pull-request/65173/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65175/), [https://github.com/nodejs/node/pull/56919/](https://ci.nodejs.org/job/node-test-pull-request/65191/)) |
| Appeared | [vm-t9xrn](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63693/console), [vm-grdtq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63683/console), [vm-jkb9c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63670/console), [vm-k82v2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63664/console), [vm-cc77j](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63661/console), [vm-bnv4b](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63660/console), [vm-d2ffw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63641/console), [vm-9ml99](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63611/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65095/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65191/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63693/console">Example</a></summary>

```
not ok 2577 parallel/test-runner-run-watch
  ---
  duration_ms: 29310.47700
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:292:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:307
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 254.022207,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/<anonymous>'...
```
</details>

-------

| Reason | <code>benchmark/test-benchmark-http2</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/57001/](https://ci.nodejs.org/job/node-test-pull-request/65140/), [https://github.com/nodejs/node/pull/55873/](https://ci.nodejs.org/job/node-test-pull-request/65153/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65158/), [https://github.com/nodejs/node/pull/56843/](https://ci.nodejs.org/job/node-test-pull-request/65165/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65167/)) |
| Appeared | [test-azure_msft-win2016_vs2017-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/26873/console), [test-azure_msft-win2016_vs2017-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/26857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65140/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65167/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2016-vs2017-COMPILED_BY-vs2019-x86/26873/console">Example</a></summary>

```
not ok 184 benchmark/test-benchmark-http2
  ---
  duration_ms: 2161.55700
  severity: fail
  exitcode: 1
  stack: |-
    Error: test-double-http2 failed with 3221226505.
        at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-native-suites\node\benchmark\_http-benchmarkers.js:251:16)
        at Object.onceWrapper (node:events:632:26)
        at ChildProcess.emit (node:events:517:28)
        at maybeClose (node:internal/child_process:1098:16)
        at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    node:assert:125
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    3221226505 !== 0
    
        at ChildProcess.<anonymous> (C:\workspace\node-test-binary-windows-native-suites\node\test\common\benchmark.js:28:12)
        at ChildProcess.emit (node:events:517:28)
        at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTIO...
```
</details>

-------

| Reason | <code>parallel/test-file-write-stream4</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/56984/](https://ci.nodejs.org/job/node-test-pull-request/65107/), [https://github.com/nodejs/node/pull/56967/](https://ci.nodejs.org/job/node-test-pull-request/65134/), [https://github.com/nodejs/node/pull/56986/](https://ci.nodejs.org/job/node-test-pull-request/65139/), [https://github.com/nodejs/node/pull/56941/](https://ci.nodejs.org/job/node-test-pull-request/65154/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65168/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65176/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/32634/console), [test-equinix-ubuntu2204_container-armv7l-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-armv7l/57233/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57223/console), [vm-mc524](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/63643/console), [test-osuosl-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/57177/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65107/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65176/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/32634/console">Example</a></summary>

```
not ok 998 parallel/test-file-write-stream4
  ---
  duration_ms: 120262.94900
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-rangeerror</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/56942/](https://ci.nodejs.org/job/node-test-pull-request/65122/), [https://github.com/nodejs/node/pull/56999/](https://ci.nodejs.org/job/node-test-pull-request/65166/), [https://github.com/nodejs/node/pull/56996/](https://ci.nodejs.org/job/node-test-pull-request/65167/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65168/)) |
| Appeared | [test-ibm-rhel8-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/63197/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49047/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/49046/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/15945/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49003/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65122/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65168/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel8-x64/63197/console">Example</a></summary>

```
not ok 864 parallel/test-buffer-tostring-rangeerror
  ---
  duration_ms: 120100.78300
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    (node:3240338) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
  ...

```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/55051/](https://ci.nodejs.org/job/node-test-pull-request/65102/), [https://github.com/nodejs/node/pull/56955/](https://ci.nodejs.org/job/node-test-pull-request/65126/), [https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65175/)) |
| Appeared | [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57242/console), [test-equinix-rhel8_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57196/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65102/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65175/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/57242/console">Example</a></summary>

```
not ok 4175 parallel/test-net-write-fully-async-buffer
  ---
  duration_ms: 360050.00900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/54793/](https://ci.nodejs.org/job/node-test-pull-request/65124/), [https://github.com/nodejs/node/pull/55873/](https://ci.nodejs.org/job/node-test-pull-request/65131/), [https://github.com/nodejs/node/pull/57001/](https://ci.nodejs.org/job/node-test-pull-request/65133/)) |
| Appeared | [vm-gdsjr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63642/console), [test-mnx-smartos23-x64-5](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/59180/console), [test-mnx-smartos22-x64-1](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos22-x64/59179/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65124/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65133/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63642/console">Example</a></summary>

```
not ok 3940 sequential/test-perf-hooks
  ---
  duration_ms: 693.71800
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:399
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (346.18701171875) - process.uptime() * 1000 (245.34834899999998) = 100.83866271875002 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:35:3)
        at Module._compile (node:internal/modules/cjs/loader:1364:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
        at Module.load (node:internal/modules/cjs/loader:1203:32)
        at Module._load (node:internal/modules/cjs/loader:1019:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='...
```
</details>

-------

| Reason | <code>parallel/test-net-write-fully-async-hex-string</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55051/](https://ci.nodejs.org/job/node-test-pull-request/65109/), [https://github.com/nodejs/node/pull/56962/](https://ci.nodejs.org/job/node-test-pull-request/65111/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48991/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl31_x64/48990/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65109/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65111/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_smallicu_x64/48991/console">Example</a></summary>

```
not ok 3455 parallel/test-net-write-fully-async-hex-string
  ---
  duration_ms: 120040.75200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-gc-http-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/56988/](https://ci.nodejs.org/job/node-test-pull-request/65121/), [https://github.com/nodejs/node/pull/57026/](https://ci.nodejs.org/job/node-test-pull-request/65187/)) |
| Appeared | [vm-grdtq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63692/console), [vm-mn698](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63632/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65121/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65187/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/63692/console">Example</a></summary>

```
not ok 4310 sequential/test-gc-http-client
  ---
  duration_ms: 1268.30400
  severity: fail
  exitcode: 1
  stack: |-
    done/collected/total: 1/0/168
    done/collected/total: 3/1/168
    done/collected/total: 4/3/168
    done/collected/total: 5/4/168
    done/collected/total: 6/5/168
    done/collected/total: 7/6/168
    done/collected/total: 8/7/168
    done/collected/total: 9/8/168
    done/collected/total: 10/9/168
    done/collected/total: 11/10/168
    done/collected/total: 12/11/168
    done/collected/total: 13/12/168
    done/collected/total: 14/13/168
    done/collected/total: 15/14/168
    done/collected/total: 16/15/168
    done/collected/total: 17/16/168
    done/collected/total: 18/17/168
    done/collected/total: 19/18/168
    done/collected/total: 20/19/168
    done/collected/total: 21/20/168
    done/collected/total: 22/21/168
    done/collected/total: 23/22/168
    done/collected/total: 24/23/168
    done/collected/total: 25/24/168
    done/collected/total: 26/25/168
    done/collected/tota...
```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/55051/](https://ci.nodejs.org/job/node-test-pull-request/65109/), [https://github.com/nodejs/node/pull/57020/](https://ci.nodejs.org/job/node-test-pull-request/65189/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/49069/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65109/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65189/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/49069/console">Example</a></summary>

```
not ok 4417 sequential/test-tls-session-timeout
  ---
  duration_ms: 173.27600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:128
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v24.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-compression</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57005/](https://ci.nodejs.org/job/node-test-pull-request/65147/), [https://github.com/nodejs/node/pull/56954/](https://ci.nodejs.org/job/node-test-pull-request/65156/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48134/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/49030/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/65147/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/65156/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/48134/console">Example</a></summary>

```
not ok 4401 wpt/test-compression
  ---
  duration_ms: 3948.00900
  severity: crashed
  exitcode: -4
  stack: |-
    [SKIPPED] compression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-bad-chunks.tentative.any.js: Execution "hangs", ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] decompression-buffersource.tentative.any.js: ArrayBuffer and TypedArray is not accepted and throws, instead of rejects during writer.write
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] third_party/pako/pako_inflate.min.js: This is not a test file.
    [PASS] the result of compressing [,Hello,Hello] with deflate should be 'HelloHello'
    [PASS] "a" should cause the constructor to throw
    [PASS] no input should cause the constructor to throw
    [PASS] non-string input should cause the constructor to th...
```
</details>

-------

