Failures in [node-test-pull-request/67638](https://ci.nodejs.org/job/node-test-pull-request/67638/) to [node-test-pull-request/67736](https://ci.nodejs.org/job/node-test-pull-request/67736/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-06-30.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-06-30 00:12 | 0       | 0       | 40       | 1       | 59      | 0.00%      |


### JSTest Failure

| Reason | <code>pummel/test-string-decoder-large-buffer</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 17 ([https://github.com/nodejs/node/pull/58813/](https://ci.nodejs.org/job/node-test-pull-request/67638/), [https://github.com/nodejs/node/pull/58612/](https://ci.nodejs.org/job/node-test-pull-request/67639/), [https://github.com/nodejs/node/pull/58707/](https://ci.nodejs.org/job/node-test-pull-request/67653/), [https://github.com/nodejs/node/pull/58839/](https://ci.nodejs.org/job/node-test-pull-request/67671/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67676/), [https://github.com/nodejs/node/pull/58836/](https://ci.nodejs.org/job/node-test-pull-request/67681/), [https://github.com/nodejs/node/pull/58866/](https://ci.nodejs.org/job/node-test-pull-request/67686/), [https://github.com/nodejs/node/pull/58867/](https://ci.nodejs.org/job/node-test-pull-request/67687/), [https://github.com/nodejs/node/pull/58833/](https://ci.nodejs.org/job/node-test-pull-request/67701/), [https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/67706/), [https://github.com/nodejs/node/pull/58878/](https://ci.nodejs.org/job/node-test-pull-request/67714/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67715/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/67720/), [https://github.com/nodejs/node/pull/58882/](https://ci.nodejs.org/job/node-test-pull-request/67721/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67723/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67728/), [https://github.com/nodejs/node/pull/58891/](https://ci.nodejs.org/job/node-test-pull-request/67736/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/35106/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67638/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67736/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022/35106/console">Example</a></summary>

```
not ok 1028 pummel/test-string-decoder-large-buffer
  ---
  duration_ms: 187.99900
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:26
        throw e;
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at createUnsafeBuffer (node:internal/buffer:1097:12)
        at allocate (node:buffer:444:10)
        at Function.allocUnsafe (node:buffer:409:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-string-decoder-large-buffer.js:21:22)
        at Module._compile (node:internal/modules/cjs/loader:1730:14)
        at Object..js (node:internal/modules/cjs/loader:1895:10)
        at Module.load (node:internal/modules/cjs/loader:1465:32)
    
    Node.js v22.17.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-config-file</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/58707/](https://ci.nodejs.org/job/node-test-pull-request/67653/), [https://github.com/nodejs/node/pull/58839/](https://ci.nodejs.org/job/node-test-pull-request/67671/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67676/), [https://github.com/nodejs/node/pull/58833/](https://ci.nodejs.org/job/node-test-pull-request/67701/), [https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/67706/), [https://github.com/nodejs/node/pull/58878/](https://ci.nodejs.org/job/node-test-pull-request/67714/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67715/), [https://github.com/nodejs/node/pull/58847/](https://ci.nodejs.org/job/node-test-pull-request/67720/), [https://github.com/nodejs/node/pull/58882/](https://ci.nodejs.org/job/node-test-pull-request/67721/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67723/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67728/), [https://github.com/nodejs/node/pull/58891/](https://ci.nodejs.org/job/node-test-pull-request/67736/)) |
| Appeared | [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/35106/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/35080/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67653/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67736/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/35106/console">Example</a></summary>

```
not ok 232 parallel/test-config-file
  ---
  duration_ms: 3901.13100
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: '--inspect=true should be parsed correctly'
    Location: test\parallel\test-config-file.js:237:1
    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /^Debugger listening on (ws:\/\/[^\s]+)/. Input:
    
    'Starting inspector on 127.0.0.1:9229 failed: address already in use\r\n'
    
        at TestContext.<anonymous> (C:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-config-file.js:244:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1054:7)
        at async Test.processPendingSubtests (node:internal/test_runner/test:744:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'Starting inspector on 127.0.0.1:9229 failed: address already in use\r\n',
      expected: /^Debugger listening on (ws:\/\/[^\s]+)/,
 ...
```
</details>

-------

| Reason | <code>parallel/test-buffer-tostring-range</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/58813/](https://ci.nodejs.org/job/node-test-pull-request/67638/), [https://github.com/nodejs/node/pull/58612/](https://ci.nodejs.org/job/node-test-pull-request/67639/), [https://github.com/nodejs/node/pull/58839/](https://ci.nodejs.org/job/node-test-pull-request/67671/), [https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67676/), [https://github.com/nodejs/node/pull/58836/](https://ci.nodejs.org/job/node-test-pull-request/67681/), [https://github.com/nodejs/node/pull/58866/](https://ci.nodejs.org/job/node-test-pull-request/67686/), [https://github.com/nodejs/node/pull/58867/](https://ci.nodejs.org/job/node-test-pull-request/67687/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67694/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35058/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67638/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67694/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2019/35058/console">Example</a></summary>

```
not ok 105 parallel/test-buffer-tostring-range
  ---
  duration_ms: 206.91300
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/buffer:961
        super(bufferOrLength, byteOffset, length);
        ^
    
    RangeError: Array buffer allocation failed
        at new ArrayBuffer (<anonymous>)
        at new Uint8Array (<anonymous>)
        at new FastBuffer (node:internal/buffer:961:5)
        at Function.alloc (node:buffer:397:10)
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-buffer-tostring-range.js:107:28)
        at Module._compile (node:internal/modules/cjs/loader:1529:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
        at Module.load (node:internal/modules/cjs/loader:1275:32)
        at Module._load (node:internal/modules/cjs/loader:1096:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    
    Node.js v20.19.4-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67715/), [https://github.com/nodejs/node/pull/58882/](https://ci.nodejs.org/job/node-test-pull-request/67718/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67726/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67728/), [https://github.com/nodejs/node/pull/58891/](https://ci.nodejs.org/job/node-test-pull-request/67732/)) |
| Appeared | [vm-pkmtr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65748/console), [test-digitalocean-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/65389/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_icu_x64/51450/console), [test-digitalocean-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/65388/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51441/console), [test-digitalocean-fedora41-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-latest-x64/65379/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67715/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67732/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/65748/console">Example</a></summary>

```
not ok 2635 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 3250.76900
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'defaults to SIGTERM'
    Location: test/parallel/test-runner-watch-mode-kill-signal.mjs:56:3
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    0 !== 123
    
        at TestContext.<anonymous> (file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-watch-mode-kill-signal.mjs:77:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Test.run (node:internal/test_runner/test:1069:7)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:1466:7)
        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:332:3) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 0,
      expected: 123,
      operator: 'strictEqual'
    }
    
  ...

```
</details>

-------

| Reason | <code>sequential/test-tls-session-timeout</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/58773/](https://ci.nodejs.org/job/node-test-pull-request/67646/), [https://github.com/nodejs/node/pull/58058/](https://ci.nodejs.org/job/node-test-pull-request/67660/), [https://github.com/nodejs/node/pull/58836/](https://ci.nodejs.org/job/node-test-pull-request/67681/), [https://github.com/nodejs/node/pull/58833/](https://ci.nodejs.org/job/node-test-pull-request/67701/), [https://github.com/nodejs/node/pull/58878/](https://ci.nodejs.org/job/node-test-pull-request/67725/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-10](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51448/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51427/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51408/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51384/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl32_x64/51370/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67646/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67725/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl35_x64/51448/console">Example</a></summary>

```
not ok 4552 sequential/test-tls-session-timeout
  ---
  duration_ms: 169.61500
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:92
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    'New' !== 'Reused'
    
        at /home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:150:16
        at ChildProcess.<anonymous> (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-tls-session-timeout.js:134:7)
        at ChildProcess.emit (node:events:507:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 'New',
      expected: 'Reused',
      operator: 'strictEqual'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>es-module/test-vm-contextified-script-leak</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67661/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67715/), [https://github.com/nodejs/node/pull/58886/](https://ci.nodejs.org/job/node-test-pull-request/67728/), [https://github.com/nodejs/node/pull/58891/](https://ci.nodejs.org/job/node-test-pull-request/67736/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35120/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35114/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67661/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67736/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35120/console">Example</a></summary>

```
not ok 65 es-module/test-vm-contextified-script-leak
  ---
  duration_ms: 296.99500
  severity: crashed
  exitcode: 3221225477
  stack: |-
    Created 128 objects
    Created 256 objects
    Found finalized object at 316, stop testing
  ...

```
</details>

-------

| Reason | <code>parallel/test-stream-readable-to-web</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58760/](https://ci.nodejs.org/job/node-test-pull-request/67656/), [https://github.com/nodejs/node/pull/58836/](https://ci.nodejs.org/job/node-test-pull-request/67677/), [https://github.com/nodejs/node/pull/58867/](https://ci.nodejs.org/job/node-test-pull-request/67687/), [https://github.com/nodejs/node/pull/58824/](https://ci.nodejs.org/job/node-test-pull-request/67724/)) |
| Appeared | [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59685/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50251/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/50231/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67656/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67724/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/59685/console">Example</a></summary>

```
not ok 4130 parallel/test-stream-readable-to-web
  ---
  duration_ms: 120034.67900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-message-port-transfer-filehandle</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58836/](https://ci.nodejs.org/job/node-test-pull-request/67681/), [https://github.com/nodejs/node/pull/58867/](https://ci.nodejs.org/job/node-test-pull-request/67687/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67694/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67723/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35107/console), [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35073/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35066/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35060/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67681/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67723/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35107/console">Example</a></summary>

```
not ok 977 parallel/test-worker-message-port-transfer-filehandle
  ---
  duration_ms: 281.99600
  severity: fail
  exitcode: 1
  stack: |-
    <anonymous_script>:0
    
    
    [Error: A FileHandle object was closed during garbage collection. This used to be allowed with a deprecation warning but is now considered an error. Please close FileHandle objects explicitly.] {
      code: 'ERR_INVALID_STATE'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-inspector-connect-to-main-thread</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58845/](https://ci.nodejs.org/job/node-test-pull-request/67678/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67715/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51439/console), [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_openssl111_x64/51405/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67678/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67715/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_zlib_x64/51439/console">Example</a></summary>

```
not ok 1883 parallel/test-inspector-connect-to-main-thread
  ---
  duration_ms: 625.03000
  severity: crashed
  exitcode: -6
  stack: |-
  ...

```
</details>

-------

| Reason | <code>parallel/test-worker-nearheaplimit-deadlock</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58773/](https://ci.nodejs.org/job/node-test-pull-request/67643/), [https://github.com/nodejs/node/pull/58853/](https://ci.nodejs.org/job/node-test-pull-request/67707/)) |
| Appeared | [test-osuosl-rhel8-ppc64_le-2](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59672/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50218/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67643/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67707/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel8-ppc64le/59672/console">Example</a></summary>

```
not ok 3900 parallel/test-worker-nearheaplimit-deadlock
  ---
  duration_ms: 711.04200
  severity: crashed
  exitcode: -6
  stack: |-
    
    <--- Last few GCs --->
    
    [1400081:0x7fff54010000]       20 ms: Mark-Compact 0.7 (3.5) -> 0.7 (3.5) MB, pooled: 0.0 MB, 1.01 / 0.00 ms (average mu = 0.734, current mu = 0.132) background allocation failure; GC in old space requested
    [1400081:0x7fff54010000]       21 ms: Mark-Compact 0.7 (3.5) -> 0.7 (3.5) MB, pooled: 0.0 MB, 0.97 / 0.00 ms (average mu = 0.633, current mu = 0.188) background allocation failure; GC in old space requested
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    ----- Native stack trace -----
    
     1: 0x10ac0ddc node::OOMErrorHandler(char const*, v8::OOMDetails const&) [out/Release/node]
     2: 0x1104f72c v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [out/Release/node]
     3: 0x1104f880 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Is...
```
</details>

-------

| Reason | <code>pummel/test-buffer-large-size-buffer-alloc-unsafe</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67652/), [https://github.com/nodejs/node/pull/58707/](https://ci.nodejs.org/job/node-test-pull-request/67653/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/35026/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67652/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67653/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/35026/console">Example</a></summary>

```
not ok 1024 pummel/test-buffer-large-size-buffer-alloc-unsafe
  ---
  duration_ms: 159.43700
  severity: fail
  exitcode: 1
  stack: |-
    c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc-unsafe.js:15
        throw e;
        ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Comparison {}
    - Comparison {
    -   code: 'ERR_STRING_TOO_LONG'
    - }
    
        at Object.<anonymous> (c:\workspace\node-test-binary-windows-js-suites\node\test\pummel\test-buffer-large-size-buffer-alloc-unsafe.js:12:10)
        at Module._compile (node:internal/modules/cjs/loader:1691:14)
        at Object..js (node:internal/modules/cjs/loader:1823:10)
        at Module.load (node:internal/modules/cjs/loader:1426:32)
        at Module._load (node:internal/modules/cjs/loader:1249:12)
        at TracingChannel.traceSync (node:diagnostics_channel:322:14)
        at wrapModuleLoad (node:internal/modules/cjs/lo...
```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58866/](https://ci.nodejs.org/job/node-test-pull-request/67686/), [https://github.com/nodejs/node/pull/58882/](https://ci.nodejs.org/job/node-test-pull-request/67718/)) |
| Appeared | [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50288/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50261/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67686/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67718/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/50288/console">Example</a></summary>

```
not ok 4493 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 14732.01600
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linuxone/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:608:17)
        at process.processTimers (node:internal/timers:543:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58773/](https://ci.nodejs.org/job/node-test-pull-request/67643/), [https://github.com/nodejs/node/pull/58853/](https://ci.nodejs.org/job/node-test-pull-request/67682/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57894/console), [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57857/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67643/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67682/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57894/console">Example</a></summary>

```
not ok 4553 wpt/test-streams
  ---
  duration_ms: 1491.06800
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; fulfilled cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel omitted; rejected cancel promise
    [PASS] Closing must be propagated backward: starts closed; preventCancel = undefined (falsy); ful...
```
</details>

-------

| Reason | <code>wpt/test-webcrypto</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58713/](https://ci.nodejs.org/job/node-test-pull-request/67657/), [https://github.com/nodejs/node/pull/58842/](https://ci.nodejs.org/job/node-test-pull-request/67665/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57879/console), [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57871/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67657/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67665/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/57879/console">Example</a></summary>

```
not ok 4559 wpt/test-webcrypto
  ---
  duration_ms: 11481.95300
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] algorithm-discards-context.https.window.js: Not relevant in Node.js context
    [SKIPPED] historical.any.js: Not relevant in Node.js context
    [PASS] CryptoKey.algorithm getter returns cached object
    [PASS] CryptoKey.usages getter returns cached object
    [PASS] setup - define tests
    [PASS] X25519 key derivation checks for all-zero value result with a key of order 0
    [PASS] X25519 key derivation checks for all-zero value result with a key of order 1
    [PASS] X25519 key derivation checks for all-zero value result with a key of order 8
    [PASS] X25519 key derivation checks for all-zero value result with a key of order p-1 (order 2)
    [PASS] X25519 key derivation checks for all-zero value result with a key of order p (=0, order 4)
    [PASS] X25519 key derivation checks for all-zero value result with a key of order p+1 (=1, order 1)
    [PASS] X25519 good parameters
    [...
```
</details>

-------


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/58612/](https://ci.nodejs.org/job/node-test-pull-request/67639/), [https://github.com/nodejs/node/pull/58866/](https://ci.nodejs.org/job/node-test-pull-request/67686/), [https://github.com/nodejs/node/pull/58833/](https://ci.nodejs.org/job/node-test-pull-request/67701/), [https://github.com/nodejs/node/pull/58882/](https://ci.nodejs.org/job/node-test-pull-request/67721/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35104/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67639/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67721/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/35104/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>Failed to trigger node-test-commit</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/58822/](https://ci.nodejs.org/job/node-test-pull-request/67644/), [https://github.com/nodejs/node/pull/58087/](https://ci.nodejs.org/job/node-test-pull-request/67716/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-pull-request/67716/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67644/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67716/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-pull-request/67716/console">Example</a></summary>

```
Failed to trigger node-test-commit
```
</details>

-------

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/57298/](https://ci.nodejs.org/job/node-test-pull-request/67652/), [https://github.com/nodejs/node/pull/58516/](https://ci.nodejs.org/job/node-test-pull-request/67722/)) |
| Appeared | [test-digitalocean-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51445/console), [test-ibm-ubuntu2204_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51378/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/67652/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/67722/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_shared_x64/51445/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

