Failures in [node-test-pull-request/68854](https://ci.nodejs.org/job/node-test-pull-request/68854/) to [node-test-pull-request/68952](https://ci.nodejs.org/job/node-test-pull-request/68952/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-08-29.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-08-29 00:11 | 1       | 0       | 26       | 5       | 68      | 0.00%      |


### Jenkins Failure

| Reason | <code>Build timed out (after 30 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59601/](https://ci.nodejs.org/job/node-test-pull-request/68857/), [https://github.com/nodejs/node/pull/59582/](https://ci.nodejs.org/job/node-test-pull-request/68861/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59660/](https://ci.nodejs.org/job/node-test-pull-request/68943/), [https://github.com/nodejs/node/pull/59649/](https://ci.nodejs.org/job/node-test-pull-request/68947/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36598/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68857/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68947/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36598/console">Example</a></summary>

```
Build timed out (after 30 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68924/), [https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68927/), [https://github.com/nodejs/node/pull/59649/](https://ci.nodejs.org/job/node-test-pull-request/68938/), [https://github.com/nodejs/node/pull/59000/](https://ci.nodejs.org/job/node-test-pull-request/68950/)) |
| Appeared | [vm-j2aqe](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66528/console), [vm-i79ab](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66514/console), [vm-9u1fc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66506/console), [vm-5thct](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66505/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68924/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68950/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66528/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------

| Reason | <code>Unexpected termination of the channel</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59181/](https://ci.nodejs.org/job/node-test-pull-request/68922/), [https://github.com/nodejs/node/pull/59662/](https://ci.nodejs.org/job/node-test-pull-request/68952/)) |
| Appeared | [vm-5sm9h](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66529/console), [vm-kkmad](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66504/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68922/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68952/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-arm64/66529/console">Example</a></summary>

```
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:80)
Caused: java.io.IOException: Backing channel 'vm-5sm9h' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy190.isAlive(Unknown Source)
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>fatal error: ld terminated with signal 9 [Killed]</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 9 ([https://github.com/nodejs/node/pull/59576/](https://ci.nodejs.org/job/node-test-pull-request/68856/), [https://github.com/nodejs/node/pull/59603/](https://ci.nodejs.org/job/node-test-pull-request/68867/), [https://github.com/nodejs/node/pull/59609/](https://ci.nodejs.org/job/node-test-pull-request/68874/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68882/), [https://github.com/nodejs/node/pull/59611/](https://ci.nodejs.org/job/node-test-pull-request/68884/), [https://github.com/nodejs/node/pull/59568/](https://ci.nodejs.org/job/node-test-pull-request/68889/), [https://github.com/nodejs/node/pull/59637/](https://ci.nodejs.org/job/node-test-pull-request/68892/), [https://github.com/nodejs/node/pull/59634/](https://ci.nodejs.org/job/node-test-pull-request/68893/), [https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68897/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-1](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=test-azure-ubuntu2204_container-arm64-1/20032/console), [test-azure-ubuntu2204_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20102/console), [test-azure-ubuntu2204_container-arm64-3](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20098/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68856/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68897/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=test-azure-ubuntu2204_container-arm64-1/20032/console">Example</a></summary>

```
fatal error: ld terminated with signal 9 [Killed]
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-inspector-network-fetch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 25 ([https://github.com/nodejs/node/pull/59283/](https://ci.nodejs.org/job/node-test-pull-request/68854/), [https://github.com/nodejs/node/pull/58680/](https://ci.nodejs.org/job/node-test-pull-request/68855/), [https://github.com/nodejs/node/pull/59601/](https://ci.nodejs.org/job/node-test-pull-request/68857/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68866/), [https://github.com/nodejs/node/pull/59603/](https://ci.nodejs.org/job/node-test-pull-request/68867/), [https://github.com/nodejs/node/pull/59607/](https://ci.nodejs.org/job/node-test-pull-request/68871/), [https://github.com/nodejs/node/pull/59609/](https://ci.nodejs.org/job/node-test-pull-request/68874/), [https://github.com/nodejs/node/pull/59582/](https://ci.nodejs.org/job/node-test-pull-request/68875/), [https://github.com/nodejs/node/pull/59568/](https://ci.nodejs.org/job/node-test-pull-request/68876/), [https://github.com/nodejs/node/pull/59616/](https://ci.nodejs.org/job/node-test-pull-request/68877/), [https://github.com/nodejs/node/pull/59632/](https://ci.nodejs.org/job/node-test-pull-request/68881/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68887/), [https://github.com/nodejs/node/pull/59602/](https://ci.nodejs.org/job/node-test-pull-request/68890/), [https://github.com/nodejs/node/pull/59634/](https://ci.nodejs.org/job/node-test-pull-request/68893/), [https://github.com/nodejs/node/pull/59518/](https://ci.nodejs.org/job/node-test-pull-request/68904/), [https://github.com/nodejs/node/pull/59629/](https://ci.nodejs.org/job/node-test-pull-request/68907/), [https://github.com/nodejs/node/pull/59576/](https://ci.nodejs.org/job/node-test-pull-request/68908/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68918/), [https://github.com/nodejs/node/pull/59181/](https://ci.nodejs.org/job/node-test-pull-request/68922/), [https://github.com/nodejs/node/pull/59647/](https://ci.nodejs.org/job/node-test-pull-request/68929/), [https://github.com/nodejs/node/pull/59637/](https://ci.nodejs.org/job/node-test-pull-request/68933/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68937/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68942/), [https://github.com/nodejs/node/pull/59605/](https://ci.nodejs.org/job/node-test-pull-request/68944/)) |
| Appeared | [test-ibm-aix72-ppc64_be-1](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58815/console), [test-osuosl-rhel9-ppc64_le-3](https://ci.nodejs.org/job/node-test-commit-plinux/nodes=rhel9-ppc64le/60558/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022_clang/36592/console), [test-rackspace-win2019_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022_clang/36587/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022_clang/36583/console), [test-rackspace-win2022_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/36579/console), [test-rackspace-win2019_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/36563/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/36562/console), [test-rackspace-win2022_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/36528/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/36506/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68854/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68944/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58815/console">Example</a></summary>

```
not ok 2400 parallel/test-inspector-network-fetch
  ---
  duration_ms: 578.23500
  severity: fail
  exitcode: 1
  stack: |-
    Debugger listening on ws://127.0.0.1:59477/5e0c1ffd-c6a5-4336-a272-1a86903f00b6
    For help, see: https://nodejs.org/en/docs/inspector
    node:internal/deps/undici/undici:15523
          Error.captureStackTrace(err);
                ^
    
    TypeError: fetch failed
        at node:internal/deps/undici/undici:15523:13
        at async testRequest (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-inspector-network-fetch.js:153:3)
        at async testNetworkInspection (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-inspector-network-fetch.js:195:3)
        at async Server.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test/parallel/test-inspector-network-fetch.js:212:7) {
      [cause]: HTTPParserError: Response does not match the HTTP/1.1 protocol (Invalid header value char)
 ...
```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59609/](https://ci.nodejs.org/job/node-test-pull-request/68874/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/), [https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68924/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68942/)) |
| Appeared | [vm-yy37e](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66519/console), [vm-gu19h](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66505/console), [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console), [vm-ciltq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66475/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68874/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68942/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66519/console">Example</a></summary>

```
not ok 2792 parallel/test-runner-run-watch
  ---
  duration_ms: 29204.37400
  severity: fail
  exitcode: 1
  stack: |-
    Mismatched noop function calls. Expected exactly 1, actual 2.
        at Module.mustCall (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/index.js:430:10)
        at TestContext.<anonymous> (file:///Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/parallel/test-runner-run-watch.mjs:374:37)
        at Test.runInAsyncScope (node:async_hooks:213:14)
        at Test.run (node:internal/test_runner/test:1106:25)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:788:7)
  ...

```
</details>

-------

| Reason | <code>sequential/test-performance-eventloopdelay</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59283/](https://ci.nodejs.org/job/node-test-pull-request/68854/), [https://github.com/nodejs/node/pull/59611/](https://ci.nodejs.org/job/node-test-pull-request/68884/), [https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68931/), [https://github.com/nodejs/node/pull/59649/](https://ci.nodejs.org/job/node-test-pull-request/68938/), [https://github.com/nodejs/node/pull/59662/](https://ci.nodejs.org/job/node-test-pull-request/68952/)) |
| Appeared | [test-ibm-ubuntu2204_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/52530/console), [test-ibm-rhel8-s390x-4](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51316/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/51296/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51268/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68854/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68952/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2204_sharedlibs_withoutintl_x64/52530/console">Example</a></summary>

```
not ok 4217 sequential/test-performance-eventloopdelay
  ---
  duration_ms: 7247.15900
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert(histogram.min > 0)
    
        at Timeout.spinAWhile [as _onTimeout] (/home/iojs/build/workspace/node-test-commit-linux-containered/test/sequential/test-performance-eventloopdelay.js:70:7)
        at listOnTimeout (node:internal/timers:581:17)
        at process.processTimers (node:internal/timers:519:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '=='
    }
    
    Node.js v20.19.5-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/59629/](https://ci.nodejs.org/job/node-test-pull-request/68907/), [https://github.com/nodejs/node/pull/59576/](https://ci.nodejs.org/job/node-test-pull-request/68908/), [https://github.com/nodejs/node/pull/59181/](https://ci.nodejs.org/job/node-test-pull-request/68911/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/), [https://github.com/nodejs/node/pull/59579/](https://ci.nodejs.org/job/node-test-pull-request/68918/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/36553/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68907/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68918/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2019-arm64/36553/console">Example</a></summary>

```
not ok 1014 wpt/test-url
  ---
  duration_ms: 1052.03300
  severity: crashed
  exitcode: 3221225477
  stack: |-
    [SKIPPED] javascript-urls.window.js: requires document.body reference
    [SKIPPED] percent-encoding.window.js: TODO: port from .window.js
    [SKIPPED] url-setters-a-area.window.js?include=file: already tested in url-setters.any.js
    [SKIPPED] url-setters-a-area.window.js?include=javascript: already tested in url-setters.any.js
    [SKIPPED] url-setters-a-area.window.js?include=mailto: already tested in url-setters.any.js
    [SKIPPED] url-setters-a-area.window.js?exclude=(file|javascript|mailto): already tested in url-setters.any.js
    [EXPECTED_FAILURE][FAIL] searchParams on location object
    assert_false: location object should not have a searchParams attribute expected false got true
        at Test.<anonymous> (d:\workspace\node-test-binary-windows-js-suites\node\test\fixtures\wpt\url\historical.any.js:3:5)
        at Test.step (d:\workspace\node-test-binary-windows-js-suites\node\tes...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4720 sequential/test-single-executable-application
  ---
  duration_ms: 11503.57000
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4719/sea
    Injected /Users/admin/node-tmp/.tmp.4719/sea-prep.blob into /Users/admin/node-tmp/.tmp.4719/sea
    Signed /Users/admin/node-tmp/.tmp.4719/sea
    [process 32884]: --- stderr ---
    
    [process 32884]: --- stdout ---
    
    [process 32884]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application.js:54:1)
        at Module._compile (node:internal/modules/cjs/loade...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-assets</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4721 sequential/test-single-executable-application-assets
  ---
  duration_ms: 11769.74200
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4720/sea
    Injected /Users/admin/node-tmp/.tmp.4720/sea-prep.blob into /Users/admin/node-tmp/.tmp.4720/sea
    Signed /Users/admin/node-tmp/.tmp.4720/sea
    [process 32904]: --- stderr ---
    
    [process 32904]: --- stdout ---
    
    [process 32904]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-assets.js:114:3)
        at Module._compile (node:internal/mo...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-assets-raw</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4722 sequential/test-single-executable-application-assets-raw
  ---
  duration_ms: 12331.83100
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4721/sea
    Injected /Users/admin/node-tmp/.tmp.4721/sea-prep.blob into /Users/admin/node-tmp/.tmp.4721/sea
    Signed /Users/admin/node-tmp/.tmp.4721/sea
    [process 32922]: --- stderr ---
    
    [process 32922]: --- stdout ---
    
    [process 32922]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-assets-raw.js:60:3)
        at Module._compile (node:inte...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-disable-experimental-sea-warning</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4723 sequential/test-single-executable-application-disable-experimental-sea-warning
  ---
  duration_ms: 12144.51200
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4722/sea
    Injected /Users/admin/node-tmp/.tmp.4722/sea-prep.blob into /Users/admin/node-tmp/.tmp.4722/sea
    Signed /Users/admin/node-tmp/.tmp.4722/sea
    [process 32942]: --- stderr ---
    
    [process 32942]: --- stdout ---
    
    [process 32942]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-disable-experimental-sea-warning.js...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4725 sequential/test-single-executable-application-exec-argv
  ---
  duration_ms: 12153.19200
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4724/sea
    Injected /Users/admin/node-tmp/.tmp.4724/sea-prep.blob into /Users/admin/node-tmp/.tmp.4724/sea
    Signed /Users/admin/node-tmp/.tmp.4724/sea
    [process 32980]: --- stderr ---
    
    [process 32980]: --- stdout ---
    
    [process 32980]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-exec-argv.js:49:1)
        at Module._compile (node:intern...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-empty</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4726 sequential/test-single-executable-application-exec-argv-empty
  ---
  duration_ms: 11952.19000
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4725/sea
    Injected /Users/admin/node-tmp/.tmp.4725/sea-prep.blob into /Users/admin/node-tmp/.tmp.4725/sea
    Signed /Users/admin/node-tmp/.tmp.4725/sea
    [process 32998]: --- stderr ---
    
    [process 32998]: --- stdout ---
    
    [process 32998]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-exec-argv-empty.js:49:1)
        at Module._compile ...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-cli</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4727 sequential/test-single-executable-application-exec-argv-extension-cli
  ---
  duration_ms: 12023.41500
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4726/sea
    Injected /Users/admin/node-tmp/.tmp.4726/sea-prep.blob into /Users/admin/node-tmp/.tmp.4726/sea
    Signed /Users/admin/node-tmp/.tmp.4726/sea
    [process 33016]: --- stderr ---
    
    [process 33016]: --- stdout ---
    
    [process 33016]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-exec-argv-extension-cli.js:50:1)
        at ...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-env</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4728 sequential/test-single-executable-application-exec-argv-extension-env
  ---
  duration_ms: 11830.77500
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4727/sea
    Injected /Users/admin/node-tmp/.tmp.4727/sea-prep.blob into /Users/admin/node-tmp/.tmp.4727/sea
    Signed /Users/admin/node-tmp/.tmp.4727/sea
    [process 33036]: --- stderr ---
    
    [process 33036]: --- stdout ---
    
    [process 33036]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-exec-argv-extension-env.js:50:1)
        at ...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-exec-argv-extension-none</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4729 sequential/test-single-executable-application-exec-argv-extension-none
  ---
  duration_ms: 12136.49900
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4728/sea
    Injected /Users/admin/node-tmp/.tmp.4728/sea-prep.blob into /Users/admin/node-tmp/.tmp.4728/sea
    Signed /Users/admin/node-tmp/.tmp.4728/sea
    [process 33054]: --- stderr ---
    
    [process 33054]: --- stdout ---
    
    [process 33054]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-exec-argv-extension-none.js:50:1)
        a...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-snapshot</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4730 sequential/test-single-executable-application-snapshot
  ---
  duration_ms: 13000.68200
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4729/sea
    Injected /Users/admin/node-tmp/.tmp.4729/sea-prep.blob into /Users/admin/node-tmp/.tmp.4729/sea
    Signed /Users/admin/node-tmp/.tmp.4729/sea
    [process 33075]: --- stderr ---
    
    [process 33075]: --- stdout ---
    
    [process 33075]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-snapshot.js:90:3)
        at Module._compile (node:internal...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-snapshot-and-code-cache</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4731 sequential/test-single-executable-application-snapshot-and-code-cache
  ---
  duration_ms: 12609.58000
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4730/sea
    Injected /Users/admin/node-tmp/.tmp.4730/sea-prep.blob into /Users/admin/node-tmp/.tmp.4730/sea
    Signed /Users/admin/node-tmp/.tmp.4730/sea
    [process 33093]: --- stderr ---
    
    [process 33093]: --- stdout ---
    
    [process 33093]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-snapshot-and-code-cache.js:67:3)
        at ...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-snapshot-worker</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4732 sequential/test-single-executable-application-snapshot-worker
  ---
  duration_ms: 12292.15000
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4731/sea
    Injected /Users/admin/node-tmp/.tmp.4731/sea-prep.blob into /Users/admin/node-tmp/.tmp.4731/sea
    Signed /Users/admin/node-tmp/.tmp.4731/sea
    [process 33111]: --- stderr ---
    
    [process 33111]: --- stdout ---
    
    [process 33111]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-snapshot-worker.js:67:3)
        at Module._compile ...
```
</details>

-------

| Reason | <code>sequential/test-single-executable-application-use-code-cache</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59640/](https://ci.nodejs.org/job/node-test-pull-request/68906/), [https://github.com/nodejs/node/pull/59201/](https://ci.nodejs.org/job/node-test-pull-request/68910/), [https://github.com/nodejs/node/pull/59437/](https://ci.nodejs.org/job/node-test-pull-request/68914/), [https://github.com/nodejs/node/pull/59394/](https://ci.nodejs.org/job/node-test-pull-request/68916/)) |
| Appeared | [vm-qk5ph](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66498/console), [vm-zpdre](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66493/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68906/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68916/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66499/console">Example</a></summary>

```
not ok 4733 sequential/test-single-executable-application-use-code-cache
  ---
  duration_ms: 11870.50500
  severity: fail
  exitcode: 1
  stack: |-
    Copied /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/out/Release/node to /Users/admin/node-tmp/.tmp.4732/sea
    Injected /Users/admin/node-tmp/.tmp.4732/sea-prep.blob into /Users/admin/node-tmp/.tmp.4732/sea
    Signed /Users/admin/node-tmp/.tmp.4732/sea
    [process 33131]: --- stderr ---
    
    [process 33131]: --- stdout ---
    
    [process 33131]: status = null, signal = SIGSEGV
    /Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/common/child_process.js:98
        throw error;
        ^
    
    Error: - process terminated with status null, expected 0
    - process terminated with signal SIGSEGV, expected null
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-single-executable-application-use-code-cache.js:61:1)
        at Module._compile (n...
```
</details>

-------

| Reason | <code>parallel/test-fastutf8stream-flush-mocks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59576/](https://ci.nodejs.org/job/node-test-pull-request/68856/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68866/), [https://github.com/nodejs/node/pull/59603/](https://ci.nodejs.org/job/node-test-pull-request/68867/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36509/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68856/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68867/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2016-COMPILED_BY-vs2022-x86/36509/console">Example</a></summary>

```
not ok 319 parallel/test-fastutf8stream-flush-mocks
  ---
  duration_ms: 928.99500
  severity: fail
  exitcode: 1
  stack: |-
    Can't clean tmpdir: C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.302
    Files blocking: [
      'fastutf8stream-2252-1756150137626-0.log',
      'fastutf8stream-2252-1756150137632-2.log'
    ]
    
    C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:80
        throw e;
        ^
    
    Error: ENOTEMPTY: directory not empty, rmdir 'C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.302'
        at Object.rmdirSync (node:fs:1206:11)
        at _rmdirSync (node:internal/fs/rimraf:261:21)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at Object.rmSync (node:fs:1252:10)
        at rmSync (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:31:8)
        at onexit (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:65:5)
        at process.<anonymous> (C:\workspace\no...
```
</details>

-------

| Reason | <code>parallel/test-fastutf8stream-sync</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59576/](https://ci.nodejs.org/job/node-test-pull-request/68856/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68866/), [https://github.com/nodejs/node/pull/59603/](https://ci.nodejs.org/job/node-test-pull-request/68867/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36509/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68856/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68867/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36509/console">Example</a></summary>

```
not ok 314 parallel/test-fastutf8stream-sync
  ---
  duration_ms: 1050.01600
  severity: fail
  exitcode: 1
  stack: |-
    Can't clean tmpdir: C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.304
    Files blocking: [
      'fastutf8stream-4936-1756150148470-2.log',
      'fastutf8stream-4936-1756150148534-7.log'
    ]
    
    C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:80
        throw e;
        ^
    
    Error: ENOTEMPTY: directory not empty, rmdir 'C:\workspace\node-test-binary-windows-js-suites\node\test\.tmp.304'
        at Object.rmdirSync (node:fs:1206:11)
        at _rmdirSync (node:internal/fs/rimraf:261:21)
        at rimrafSync (node:internal/fs/rimraf:194:7)
        at Object.rmSync (node:fs:1252:10)
        at rmSync (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:31:8)
        at onexit (C:\workspace\node-test-binary-windows-js-suites\node\test\common\tmpdir.js:65:5)
        at process.<anonymous> (C:\workspace\node-tes...
```
</details>

-------

| Reason | <code>parallel/test-http-keep-alive-empty-line</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59609/](https://ci.nodejs.org/job/node-test-pull-request/68874/), [https://github.com/nodejs/node/pull/59611/](https://ci.nodejs.org/job/node-test-pull-request/68884/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68885/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18603/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60122/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60116/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68874/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68885/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console">Example</a></summary>

```
not ok 1725 parallel/test-http-keep-alive-empty-line
  ---
  duration_ms: 9082.96400
  severity: fail
  exitcode: 1
  stack: |-
    node:events:497
          throw er; // Unhandled 'error' event
          ^
    
    Error [ERR_STREAM_WRITE_AFTER_END]: write after end
        at _write (node:internal/streams/writable:489:11)
        at Writable.write (node:internal/streams/writable:510:10)
        at Timeout._onTimeout (file:///home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-keep-alive-empty-line.mjs:32:14)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7)
    Emitted 'error' event on Socket instance at:
        at emitErrorNT (node:internal/streams/destroy:170:8)
        at emitErrorCloseNT (node:internal/streams/destroy:129:3)
        at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
      code: 'ERR_STREAM_WRITE_AFTER_END'
    }
    
    Node.js v22.18.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-outgoing-end-cork</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59609/](https://ci.nodejs.org/job/node-test-pull-request/68874/), [https://github.com/nodejs/node/pull/59611/](https://ci.nodejs.org/job/node-test-pull-request/68884/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68885/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18603/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60122/console), [test-equinix-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60116/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68874/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68885/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console">Example</a></summary>

```
not ok 1760 parallel/test-http-outgoing-end-cork
  ---
  duration_ms: 5098.69300
  severity: fail
  exitcode: 1
  stack: |-
    Sending req no 1
    node:assert:202
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: () => {
        reject(new Error('Request timed out'));
      } at /home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-outgoing-end-cork.js:53
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail',
      diff: 'simple'
    }
    
    Node.js v22.18.1-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-streams</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/59582/](https://ci.nodejs.org/job/node-test-pull-request/68861/), [https://github.com/nodejs/node/pull/59616/](https://ci.nodejs.org/job/node-test-pull-request/68864/), [https://github.com/nodejs/node/pull/59570/](https://ci.nodejs.org/job/node-test-pull-request/68887/)) |
| Appeared | [test-ibm-aix72-ppc64_be-2](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58786/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68861/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68887/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/58786/console">Example</a></summary>

```
not ok 4791 wpt/test-streams
  ---
  duration_ms: 1526.54200
  severity: crashed
  exitcode: -5
  stack: |-
    [SKIPPED] queuing-strategies-size-function-per-global.window.js: Browser-specific test
    [SKIPPED] readable-streams/cross-realm-crash.window.js: Browser-specific test
    [SKIPPED] readable-streams/owning-type-video-frame.any.js: Browser-specific test
    [SKIPPED] readable-streams/read-task-handling.window.js: Browser-specific test
    [SKIPPED] transferable/deserialize-error.window.js: Browser-specific test
    [SKIPPED] transferable/transfer-with-messageport.window.js: Browser-specific test
    [SKIPPED] transform-streams/invalid-realm.tentative.window.js: Browser-specific test
    [PASS] a signal argument 'null' should cause pipeTo() to reject
    [PASS] a signal argument 'AbortSignal' should cause pipeTo() to reject
    [PASS] a signal argument 'true' should cause pipeTo() to reject
    [PASS] a signal argument '-1' should cause pipeTo() to reject
    [PASS] a signal argument '[object AbortSi...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59181/](https://ci.nodejs.org/job/node-test-pull-request/68911/), [https://github.com/nodejs/node/pull/59587/](https://ci.nodejs.org/job/node-test-pull-request/68946/)) |
| Appeared | [vm-yy37e](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66523/console), [vm-za6ac](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66496/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68911/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68946/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66523/console">Example</a></summary>

```
not ok 4328 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 892.28000
  severity: fail
  exitcode: 1
  stack: |-
    #6 eneded response for: 'https://local\rhost:62947/carriage-return-in-host'
    #5 eneded response for: 'https://local\nhost:62947/newline-in-host'
    #4 eneded response for: 'https://localhost:6\n2947/newline-in-port'
    #3 eneded response for: 'https://local\r\nhost:62947/crlf-in-host'
    #2 eneded response for: 'https://localhost:6\r2947/carriage-return-in-port'
    #1 eneded response for: 'https://localhost:6\r\n2947/crlf-in-port'
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + Set(8) {
    - Set(6) {
        {
    +     error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    +         at _write (node:internal/streams/writable:487:11)
    +         at Writable.write (node:internal/streams/writable:508:10)
    +      ...
```
</details>

-------

| Reason | <code>parallel/test-crypto-dh-generate-keys</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68866/), [https://github.com/nodejs/node/pull/59603/](https://ci.nodejs.org/job/node-test-pull-request/68867/)) |
| Appeared | [test-rackspace-win2016_vs2015-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36509/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68866/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68867/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2016-COMPILED_BY-vs2022-x86/36509/console">Example</a></summary>

```
not ok 1041 parallel/test-crypto-dh-generate-keys
  ---
  duration_ms: 120245.58200
  severity: fail
  exitcode: 1
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-break</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68862/), [https://github.com/nodejs/node/pull/59601/](https://ci.nodejs.org/job/node-test-pull-request/68878/)) |
| Appeared | [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/36527/console), [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18580/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68878/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/36527/console">Example</a></summary>

```
not ok 231 parallel/test-debugger-break
  ---
  duration_ms: 582.01500
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/process/promises:332
        triggerUncaughtException(err, true /* fromPromise */);
        ^
    
    AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
    
      assert.ok(cli.output.includes(`#1 ${script}:16`))
    
        at c:\workspace\node-test-binary-windows-js-suites\node\test\parallel\test-debugger-break.js:64:10
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '==',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-use-strict</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68862/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68885/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68885/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console">Example</a></summary>

```
not ok 929 parallel/test-debugger-use-strict
  ---
  duration_ms: 21752.49600
  severity: fail
  exitcode: 1
  stack: |-
    /home/iojs/build/workspace/node-test-binary-armv7l/test/common/debugger.js:95
              reject(new Error([
                     ^
    
    Error: Timeout (10000) while waiting for /break (?:on start )?in/i; found: < Debugger listening on ws://127.0.0.1:39621/01002ce0-a988-4850-854a-c4e3b9c77bc7
    < For help, see: https://nodejs.org/en/docs/inspector
    < 
    
    connecting to 127.0.0.1:39621 ...
     ok
    
    < Debugger attached.
    < 
    
    debug> 
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/debugger.js:95:18)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7)
    
    Node.js v22.18.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-debugger-watchers</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68862/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68885/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68862/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68885/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console">Example</a></summary>

```
not ok 935 parallel/test-debugger-watchers
  ---
  duration_ms: 22970.94700
  severity: fail
  exitcode: 1
  stack: |-
    /home/iojs/build/workspace/node-test-binary-armv7l/test/common/debugger.js:95
              reject(new Error([
                     ^
    
    Error: Timeout (10000) while waiting for /break (?:on start )?in/i; found: 
    < Debugger listening on ws://127.0.0.1:38265/60b84958-4cc6-4eea-bae2-554aa5c49f06
    < For help, see: https://nodejs.org/en/docs/inspector
    < 
    
    connecting to 127.0.0.1:38265 ..
    .
     ok
    
    < Debugger attached.
    < 
    
        at Timeout.<anonymous> (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/debugger.js:95:18)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7)
    
    Node.js v22.18.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-esm-loader-hooks-inspect-wait</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68941/), [https://github.com/nodejs/node/pull/59662/](https://ci.nodejs.org/job/node-test-pull-request/68952/)) |
| Appeared | [test-digitalocean-freebsd13-x64-1](https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/61662/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68941/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68952/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd13-x64/61662/console">Example</a></summary>

```
not ok 1041 parallel/test-esm-loader-hooks-inspect-wait
  ---
  duration_ms: 652.09600
  severity: fail
  exitcode: 1
  stack: |-
    [test] Connecting to a child Node process
    [test] Testing /json/list
    [err] Debugger listening on ws://127.0.0.1:61323/8b6a2472-b980-4191-8503-b4262f3ad2de
    [err] For help, see: https://nodejs.org/en/docs/inspector
    [err] 
    [err] Debugger attached.
    [err] 
    [err] Waiting for the debugger to disconnect...
    [err] 
    [err] child process crashed, signal SIGSEGV
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    null !== 0
    
        at runTest (/usr/home/iojs/build/workspace/node-test-commit-freebsd/nodes/freebsd13-x64/test/parallel/test-esm-loader-hooks-inspect-wait.js:27:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: null,
      expected: 0,
      operator: 'strictEqual'
    }
    1
  ...

```
</details>

-------

| Reason | <code>parallel/test-http-client-close-with-default-agent</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59611/](https://ci.nodejs.org/job/node-test-pull-request/68884/), [https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68885/)) |
| Appeared | [test-equinix-debian11_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18603/console), [test-equinix-rhel8_container-arm64-2](https://ci.nodejs.org/job/node-test-commit-arm/nodes=rhel8-arm64/60122/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68884/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68885/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=debian11-armv7l/18603/console">Example</a></summary>

```
not ok 1608 parallel/test-http-client-close-with-default-agent
  ---
  duration_ms: 7202.53200
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:202
      throw err;
      ^
    
    AssertionError [ERR_ASSERTION]: function should not have been called at /home/iojs/build/workspace/node-test-binary-armv7l/test/parallel/test-http-client-close-with-default-agent.js:23
        at Timeout.mustNotCall [as _onTimeout] (/home/iojs/build/workspace/node-test-binary-armv7l/test/common/index.js:495:12)
        at listOnTimeout (node:internal/timers:588:17)
        at process.processTimers (node:internal/timers:523:7) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: 'fail',
      diff: 'simple'
    }
    
    Node.js v22.18.1-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59179/](https://ci.nodejs.org/job/node-test-pull-request/68885/), [https://github.com/nodejs/node/pull/59551/](https://ci.nodejs.org/job/node-test-pull-request/68941/)) |
| Appeared | [vm-a1089](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66518/console), [vm-kbexh](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66515/console), [test-equinix-ubuntu2204_container-armv7l-2](https://ci.nodejs.org/job/node-test-binary-armv7l/RUN_SUBSET=js,nodes=ubuntu2204-armv7l/18603/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68885/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68941/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/66518/console">Example</a></summary>

```
not ok 3874 parallel/test-runner-output
  ---
  duration_ms: 120084.20400
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    TAP version 13
    # Subtest: test runner output
        # Subtest: test-runner/output/abort.js
        ok 1 - test-runner/output/abort.js
          ---
          duration_ms: 1597.982382
          ...

```
</details>

-------

| Reason | <code>parallel/test-snapshot-reproducible</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/59576/](https://ci.nodejs.org/job/node-test-pull-request/68856/), [https://github.com/nodejs/node/pull/59568/](https://ci.nodejs.org/job/node-test-pull-request/68858/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36501/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022_clang/36498/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/68856/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/68858/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/36501/console">Example</a></summary>

```
not ok 800 parallel/test-snapshot-reproducible
  ---
  duration_ms: 1823.00000
  severity: fail
  exitcode: 1
  stack: |-
    0x0: Write magic 143da19
    0x4: Write metadata
    0x35: Write snapshot blob
    0x23f2b8: Write IsolateDataSerializeInfo
    0x240ab9: Write EnvSerializeInfo
    0x2419af: Write CodeCacheInfo
    0x0: Write magic 143da19
    0x4: Write metadata
    0x35: Write snapshot blob
    0x23f2b8: Write IsolateDataSerializeInfo
    0x240ab9: Write EnvSerializeInfo
    0x2419af: Write CodeCacheInfo
    node:assert:147
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
    + actual - expected
    
    + [
    +   {
    +     offset: '0x40',
    +     slice1: '00155aafe26857e24431332e372e3135',
    +     slice2: '005c5a8eb06857e24431332e372e3135'
    +   },
    +   {
    +     offset: '0x1e9990',
    +     slice1: '00000000000300000084020000071502',
    +     slice2: '000000000003000000cd000000071502'
    +   }
    + ]...
```
</details>

-------

